import React,{useState} from 'react';
import {roleNames,rolePermissions,permissionNames} from './domain/permissions';

export function AccountPanel({actor,requests,act,busy}) {
 const [name,setName]=useState(actor.name);
 const completed=requests.filter(r=>['completed','rated'].includes(r.status)).length;
 const active=requests.filter(r=>['searching','pending_availability','proposed','confirmed','in_progress'].includes(r.status)).length;
 return <section className="account-overview" aria-label="Resumen de mi cuenta">
  <div className="account-heading"><div><span className="kicker">PANEL DE {roleNames[actor.role]?.toUpperCase()}</span><h3>Hola, {actor.name}</h3><p className="muted">{actor.role==='client'?'Solicita ayuda, confirma a tu profesional y sigue cada atención.':actor.role==='technician'?'Revisa tus oportunidades y lleva el control de tus servicios.':'Supervisa los servicios y controla quién puede acceder a la plataforma.'}</p></div><span className="status">{roleNames[actor.role]}</span></div>
  <div className="account-metrics"><div><strong>{requests.length}</strong><span>Solicitudes</span></div><div><strong>{active}</strong><span>En seguimiento</span></div><div><strong>{completed}</strong><span>Finalizadas</span></div></div>
  <details className="account-details"><summary>Mi perfil y permisos</summary><div className="profile-permissions"><form onSubmit={e=>{e.preventDefault();act('profile',{name:name.trim()})}}><label>Nombre completo<input value={name} onChange={e=>setName(e.target.value)} required minLength={2} maxLength={100}/></label>{actor.email&&<p className="muted">{actor.email}</p>}<button className="button outline" disabled={busy||name.trim().length<2}>Guardar perfil</button></form><div><h4>Acciones permitidas</h4><ul>{(actor.permissions||rolePermissions[actor.role]||[]).map(p=><li key={p}>{permissionNames[p]}</li>)}</ul><p className="muted">Los permisos corresponden a tu rol. Solo puedes gestionar los datos y servicios autorizados para tu cuenta.</p></div></div></details>
 </section>;
}

export function AccessManager({users=[],events=[],act,busy}) {
 const [search,setSearch]=useState(''),[role,setRole]=useState('all'),[pending,setPending]=useState(null);
 const filtered=users.filter(u=>(role==='all'||u.role===role)&&[u.name,u.email].join(' ').toLocaleLowerCase().includes(search.toLocaleLowerCase()));
 return <section className="access-manager" aria-labelledby="access-title"><h3 id="access-title">Usuarios y permisos</h3><p className="muted">Los roles definen el alcance de cada cuenta. Suspender revoca sus sesiones; reactivar permite volver a ingresar.</p>
 <div className="account-filters"><label>Buscar usuario<input type="search" value={search} onChange={e=>setSearch(e.target.value)} placeholder="Nombre o correo"/></label><label>Tipo de cuenta<select value={role} onChange={e=>setRole(e.target.value)}><option value="all">Todos los roles</option>{Object.entries(roleNames).map(([id,label])=><option key={id} value={id}>{label}</option>)}</select></label></div>
 {pending&&<div className="access-confirm" role="group" aria-label="Confirmar cambio de acceso"><p>¿{pending.active?'Suspender':'Reactivar'} el acceso de <b>{pending.name}</b>?</p><button className="button primary" disabled={busy} onClick={async()=>{if(await act('accounts',{userId:pending.id,active:!pending.active}))setPending(null)}}>Confirmar cambio</button><button className="button outline" disabled={busy} onClick={()=>setPending(null)}>Volver</button></div>}
 <div className="table-scroll"><table><caption>{filtered.length} cuentas encontradas</caption><thead><tr><th>Nombre</th><th>Correo</th><th>Rol</th><th>Acceso</th><th>Acción</th></tr></thead><tbody>{filtered.map(u=><tr key={u.id}><th scope="row">{u.name}</th><td>{u.email||'Perfil de demostración'}</td><td>{roleNames[u.role]}</td><td>{u.active?'Activo':'Suspendido'}</td><td>{u.role==='admin'?<span>Cuenta protegida</span>:<button className="button outline" disabled={busy} onClick={()=>setPending(u)}>{u.active?'Suspender':'Reactivar'}</button>}</td></tr>)}</tbody></table>{!filtered.length&&<p className="muted">No hay cuentas que coincidan con la búsqueda.</p>}</div>
 <details className="account-details"><summary>Matriz de permisos por rol</summary><div className="table-scroll"><table><caption>Acceso a operaciones y datos</caption><thead><tr><th>Operación</th>{Object.values(roleNames).map(r=><th key={r}>{r}</th>)}</tr></thead><tbody>{Object.entries(permissionNames).map(([id,label])=><tr key={id}><th scope="row">{label}</th>{Object.keys(roleNames).map(r=><td key={r}>{rolePermissions[r].includes(id)?'Permitido':'Sin acceso'}</td>)}</tr>)}</tbody></table></div></details>
 <details className="account-details"><summary>Historial de cambios de acceso</summary>{events.length?<ol className="access-history">{events.map((event,i)=><li key={event.id||i}>{new Date(event.created_at).toLocaleString('es-PE')} · {users.find(u=>String(u.id)===String(event.actor_id))?.name||'Administrador'} {event.action==='activate'?'reactivó':'suspendió'} a {users.find(u=>String(u.id)===String(event.user_id))?.name||'Usuario'}</li>)}</ol>:<p className="muted">Todavía no se han registrado cambios de acceso.</p>}</details>
 </section>;
}
