import React,{useEffect,useRef,useState} from 'react';
import {audiences,announcementStatuses,safeLink,visibleAnnouncements} from './domain/announcements';
import './announcements.css';
const blank=()=>({title:'',body:'',audience:'client',status:'draft',priority:0,image:'',linkLabel:'',linkUrl:''});
export function AnnouncementBanner({item}){
 const href=safeLink(item.linkUrl);
 return <article className={'announcement-banner '+(item.image?'has-image':'text-banner')}>
  {item.image&&<img className="announcement-image" src={item.image} alt="" />}
  <div className="announcement-copy"><span className="announcement-kicker">TÉCNICOYA / NOVEDADES</span><h3>{item.title||'El título de tu anuncio'}</h3><p>{item.body||'Aquí aparecerá el mensaje para tu comunidad.'}</p>{href&&item.linkLabel&&<a className="button primary" href={href} target="_blank" rel="noopener noreferrer">{item.linkLabel} <span aria-hidden="true">↗</span></a>}</div>
  {!item.image&&<div className="announcement-art" aria-hidden="true"><span>t</span><i/><i/></div>}
 </article>;
}
export function AnnouncementFeed({items=[],role}){
 const list=visibleAnnouncements(items,role),[index,setIndex]=useState(0);
 const signatures=list.map(a=>a.id).join(',');
 useEffect(()=>setIndex(0),[role,signatures]);
 if(!list.length)return null;
 const current=Math.min(index,list.length-1);
 return <section className="announcements-feed" aria-label="Anuncios para tu perfil" aria-roledescription="carrusel"><div className="announcements-heading"><div><span className="kicker">PARA TI</span><h2>Anuncios y novedades</h2></div><span>{audiences[role]}</span></div><div aria-live="polite" aria-atomic="true"><AnnouncementBanner item={list[current]}/></div>{list.length>1&&<div className="announcement-navigation"><button type="button" aria-label="Anuncio anterior" onClick={()=>setIndex((current-1+list.length)%list.length)}>←</button><div>{list.map((item,i)=><button type="button" className="announcement-dot" key={item.id} aria-label={'Ver anuncio '+(i+1)} aria-pressed={i===current} onClick={()=>setIndex(i)}/>)}</div><span>{current+1} / {list.length}</span><button type="button" aria-label="Anuncio siguiente" onClick={()=>setIndex((current+1)%list.length)}>→</button></div>}</section>;
}
export function AnnouncementManager({items=[],act,busy}){
 const [draft,setDraft]=useState(blank),[editing,setEditing]=useState(false),[filter,setFilter]=useState('all'),[statusFilter,setStatusFilter]=useState('all'),[error,setError]=useState(''),[reading,setReading]=useState(false),[previewRole,setPreviewRole]=useState('client');
 const readerRef=useRef(null),editorRef=useRef(null);
 useEffect(()=>()=>readerRef.current?.abort(),[]);
 const change=(key,value)=>setDraft(d=>({...d,[key]:value}));
 function open(item){readerRef.current?.abort();setReading(false);setError('');setDraft(item?{...blank(),...item}:blank());setEditing(true);}
 useEffect(()=>{if(editing)editorRef.current?.focus()},[editing,draft.id]);
 function imageFile(file){
  readerRef.current?.abort();setError('');if(!file){setReading(false);return;}
  if(!['image/png','image/jpeg','image/webp'].includes(file.type)||file.size>2*1024*1024){setReading(false);setError('Usa una imagen PNG, JPG o WebP de máximo 2 MB.');return;}
  const reader=new FileReader();readerRef.current=reader;setReading(true);
  reader.onload=()=>{const image=new Image();image.onload=()=>{if(readerRef.current!==reader)return;if(image.naturalWidth!==1600||image.naturalHeight!==420){setError('La imagen debe medir exactamente 1600 × 420 px. La seleccionada mide '+image.naturalWidth+' × '+image.naturalHeight+' px.');}else{change('image',reader.result)}setReading(false)};image.onerror=()=>{if(readerRef.current!==reader)return;setError('No se pudo abrir la imagen. Selecciona un archivo válido.');setReading(false)};image.src=reader.result};reader.onerror=()=>{setError('No se pudo leer la imagen.');setReading(false)};reader.readAsDataURL(file);
 }
 async function save(e){e.preventDefault();setError('');if(draft.linkUrl&&!safeLink(draft.linkUrl)){setError('El enlace debe comenzar con https:// o http://.');return;}const payload={...draft,title:draft.title.trim(),body:draft.body.trim(),linkUrl:draft.linkUrl?.trim()||'',linkLabel:draft.linkLabel?.trim()||'',priority:Number(draft.priority)};if(await act('announcement-save',payload)){setEditing(false);setDraft(blank())}}
 const filtered=items.filter(a=>(filter==='all'||a.audience===filter)&&(statusFilter==='all'||a.status===statusFilter));
 return <section className="announcement-manager" aria-labelledby="announcements-admin-title"><div className="announcements-heading"><div><span className="kicker">COMUNICACIÓN POR PERFIL</span><h2 id="announcements-admin-title">Centro de anuncios</h2><p className="muted">Decide qué ven tus clientes y técnicos al ingresar.</p></div><button type="button" className="button primary" disabled={busy||editing} onClick={()=>open()}>+ Crear anuncio</button></div>
 <div className="announcement-admin-stats">{Object.entries(announcementStatuses).map(([key,label])=><div key={key}><strong>{items.filter(a=>a.status===key).length}</strong><span>{label}</span></div>)}</div>
 {editing&&<div className="announcement-editor"><form onSubmit={save}><h3 tabIndex={-1} ref={editorRef}>{draft.id?'Editar anuncio':'Nuevo anuncio'}</h3><fieldset disabled={busy||reading}><label>Título del anuncio<input value={draft.title} onChange={e=>change('title',e.target.value)} required minLength={3} maxLength={120}/></label><label>Descripción<textarea rows={3} value={draft.body} onChange={e=>change('body',e.target.value)} required maxLength={600}/></label><div className="form-row"><label>Mostrar a<select value={draft.audience} onChange={e=>change('audience',e.target.value)}>{Object.entries(audiences).map(([id,name])=><option key={id} value={id}>{name}</option>)}</select></label><label>Estado del anuncio<select value={draft.status} onChange={e=>change('status',e.target.value)}>{Object.entries(announcementStatuses).map(([id,name])=><option key={id} value={id}>{name}</option>)}</select></label></div><label>Prioridad (0–100)<input type="number" min="0" max="100" step="1" value={draft.priority} onChange={e=>change('priority',e.target.value)} required/></label><p className="muted">Los anuncios con mayor prioridad aparecen primero. Solo los publicados son visibles.</p><label>Imagen del banner<input key={draft.id||'new'} type="file" accept="image/png,image/jpeg,image/webp" onChange={e=>imageFile(e.target.files?.[0])}/></label><p className="muted">Medida obligatoria: 1600 × 420 px. PNG, JPG o WebP · máximo 2 MB. Las imágenes con otras dimensiones serán rechazadas. Deja espacio en la izquierda para el texto y el botón.</p>{draft.image&&<button type="button" className="text-button" onClick={()=>change('image','')}>Quitar imagen</button>}<label>Texto del botón (opcional)<input maxLength={40} value={draft.linkLabel||''} required={Boolean(draft.linkUrl)} onChange={e=>change('linkLabel',e.target.value)}/></label><label>Enlace del botón<input type="url" placeholder="https://" maxLength={2048} value={draft.linkUrl||''} required={Boolean(draft.linkLabel)} onChange={e=>change('linkUrl',e.target.value)}/></label></fieldset>{reading&&<p role="status">Cargando imagen…</p>}{error&&<p className="error" role="alert">{error}</p>}<div className="announcement-editor-actions"><button className="button primary" disabled={busy||reading}>{busy?'Guardando…':draft.status==='published'?'Guardar y publicar':'Guardar anuncio'}</button><button type="button" className="button outline" disabled={busy||reading} onClick={()=>{setEditing(false);setDraft(blank())}}>Cancelar edición</button></div></form><aside><span className="kicker">VISTA PREVIA DEL BANNER</span><p className="muted">Audiencia: {audiences[draft.audience]} · {announcementStatuses[draft.status]}</p><AnnouncementBanner item={draft}/></aside></div>}
 <div className="account-filters"><label>Filtrar por audiencia<select value={filter} onChange={e=>setFilter(e.target.value)}><option value="all">Todas las audiencias</option>{Object.entries(audiences).map(([id,name])=><option key={id} value={id}>{name}</option>)}</select></label><label>Filtrar por publicación<select value={statusFilter} onChange={e=>setStatusFilter(e.target.value)}><option value="all">Todos los estados</option>{Object.entries(announcementStatuses).map(([id,name])=><option key={id} value={id}>{name}</option>)}</select></label></div>
 <div className="announcement-list">{filtered.map(item=><article key={item.id} className="announcement-list-item"><div><span className={'status announcement-status-'+item.status}>{announcementStatuses[item.status]}</span><h3>{item.title}</h3><p>{audiences[item.audience]} · Prioridad {item.priority}</p></div><button type="button" className="button outline" disabled={busy||editing} onClick={()=>open(item)}>Editar <span className="sr-only">{item.title}</span></button></article>)}</div>{!filtered.length&&<p className="empty-state">No hay anuncios en esta selección. Crea uno y elige quién podrá verlo.</p>}
 <details className="account-details"><summary>Comprobar qué ve cada perfil</summary><label className="announcement-preview-role">Vista del perfil<select value={previewRole} onChange={e=>setPreviewRole(e.target.value)}><option value="client">Cliente</option><option value="technician">Técnico</option></select></label><AnnouncementFeed items={items} role={previewRole}/>{!visibleAnnouncements(items,previewRole).length&&<p className="muted">Este perfil no tiene anuncios publicados.</p>}</details>
 </section>;
}
