import React,{useEffect,useState} from 'react';
import Marketplace from './Marketplace';
import {rules} from './domain/matching';
import ServiceCarousel from './ServiceCarousel';

export default function App(){const [specialty,setSpecialty]=useState('computo');const [route,setRoute]=useState(window.location.hash);const account=['#cuenta','#plataforma','#demo'].includes(route);useEffect(()=>{const change=()=>{setRoute(window.location.hash);if(['#cuenta','#plataforma','#demo'].includes(window.location.hash))window.scrollTo(0,0)};window.addEventListener('hashchange',change);return()=>window.removeEventListener('hashchange',change)},[]);useEffect(()=>{const hero=document.getElementById('inicio');if(!hero)return;let visible=true;const update=()=>hero.classList.toggle('motion-paused',!visible||document.hidden);const observer=new IntersectionObserver(([entry])=>{visible=entry.isIntersecting;update()});observer.observe(hero);document.addEventListener('visibilitychange',update);return()=>{observer.disconnect();document.removeEventListener('visibilitychange',update)}},[account]);if(account)return <div className="account-page"><header className="header"><a className="brand" href="#inicio"><span className="monogram">t</span><span>TécnicoYa<small>HUANCAYO</small></span></a><a className="button glass" href="#inicio">Volver al inicio ↗</a></header><main id="contenido"><Marketplace key={route==='#demo'?'demo':'live'} initialSpecialty={specialty} accountOnly={route!=='#demo'}/></main></div>;return <>
 <a className="skip" href="#contenido">Ir al contenido</a>
 <header className="header"><a className="brand" href="#inicio" aria-label="TécnicoYa Huancayo, inicio"><span className="monogram">t</span><span>Técnico<span className="brand-light">Ya</span><small>HUANCAYO</small></span></a><nav aria-label="Principal" className="nav glass"><a href="#servicios">Especialidades</a><a href="#proceso">Cómo funciona</a><a href="#tecnicos">Para técnicos</a></nav><div className="header-actions"><a className="button glass header-cta" href="#plataforma">Encontrar un técnico <span aria-hidden="true">↗</span></a><a className="button primary header-cta" href="#cuenta">Iniciar sesión</a></div></header>
 <main id="contenido"><section id="inicio" className="hero"><div className="eyebrow glass reveal">Para tu hogar. Para tu negocio. Para Huancayo.</div><h1 aria-label="El técnico indicado. Aquí, en Huancayo.">{'El técnico indicado. Aquí, en Huancayo.'.split(' ').map((word,i)=><span className="word" key={i} style={{'--delay':`${.4+i*.11}s`}}>{word} </span>)}</h1><p className="hero-copy reveal">Conectamos hogares y MYPES con técnicos independientes verificados.<br/>Cuéntanos la falla. Encuentra a quien puede resolverla.</p><div className="hero-actions reveal"><a className="button primary" href="#plataforma">Necesito un técnico <span aria-hidden="true">↗</span></a><a className="button glass" href="#tecnicos">Soy técnico independiente <span aria-hidden="true">↘</span></a></div><div className="hero-metrics reveal"><div className="glass"><span>RESPUESTA A LA SOLICITUD</span><strong>{rules.responseMinutes} min</strong><span>Para aceptar; si vence, reasignamos</span></div><div className="glass"><span>UNA SOLA PLATAFORMA</span><strong>3 rubros</strong><span>Cómputo · Refrigeración · Electricidad</span></div></div><div className="hero-bottom"><span>TALENTO LOCAL · CONEXIONES DE CONFIANZA</span><a href="#servicios">Conoce las especialidades <span aria-hidden="true">↓</span></a></div></section>
 <ServiceCarousel onSelect={setSpecialty}/>
 <section className="section process" id="proceso"><div><span className="kicker">02 / DEL PROBLEMA A LA SOLUCIÓN</span><h2>Menos búsqueda.<br/><em>Más claridad.</em></h2><p className="muted process-intro">Sin depender de mensajes dispersos. Cada respuesta y cada paso del servicio quedan registrados.</p></div><ol>{[['Cuéntanos qué sucede','Registra la falla y tu zona. El sistema busca perfiles verificados y disponibles.'],['Revisa y confirma',`Notificamos a un máximo de ${rules.maxSimultaneous} técnicos. Cada uno tiene ${rules.responseMinutes} minutos para responder; tú confirmas al técnico propuesto.`],['Sigue el servicio y califica',`Consulta el avance de la atención. Al finalizar, tienes ${rules.ratingHours} horas para compartir tu calificación.`]].map(([title,text],i)=><li key={title}><span>0{i+1}</span><div><h3>{title}</h3><p>{text}</p></div></li>)}</ol></section>
 <section className="section matching-section"><div><span className="kicker">03 / UNA ELECCIÓN CON CRITERIO</span><h2>El encuentro adecuado<br/><em>no es casualidad.</em></h2><p className="muted">El ranking combina cuatro factores. En un empate, prioriza la calificación promedio más alta.</p></div><div className="matching-factors">{[['proximity','Cercanía','Cobertura en tu zona'],['price','Tarifa','Costo de la visita'],['rating','Historial','Calificaciones recibidas'],['experience','Experiencia','Trayectoria en el oficio']].map(([key,title,text])=><div className="glass" key={key}><strong>{Math.round(rules.weights[key]*100)}<i>%</i></strong><b>{title}</b><span>{text}</span></div>)}</div><p className="matching-note">Si no hay disponibilidad, la búsqueda queda abierta hasta {rules.pendingHours} horas. El plazo de respuesta no es una promesa de llegada en {rules.responseMinutes} minutos.</p></section>
 <section className="section technician-invite" id="tecnicos"><div><span className="kicker">PARA TÉCNICOS INDEPENDIENTES</span><h2>Tu experiencia merece<br/><em>nuevas oportunidades.</em></h2><p>Define tu especialidad, zona y tarifa. Una vez verificado, activa tu disponibilidad, responde solicitudes y construye tu historial de calificaciones.</p></div><a className="button primary" href="#plataforma">Conocer mi espacio <span aria-hidden="true">↗</span></a></section>

 <section className="section faq"><span className="kicker">ANTES DE EMPEZAR</span><h2>Las cosas <em>claras.</em></h2>{[['¿TécnicoYa realiza directamente las reparaciones?','No. La plataforma conecta a clientes con técnicos independientes verificados. El trabajo lo realiza el profesional que acepta y tú confirmas.'],['¿Qué incluye la tarifa publicada?','Es la tarifa de visita declarada por el técnico. Los repuestos y trabajos adicionales se acuerdan con el cliente antes de realizarlos.'],['¿Qué sucede si nadie responde?',`Cuando vence el plazo de ${rules.responseMinutes} minutos, se buscan otros técnicos elegibles. Si no hay disponibilidad, la solicitud permanece pendiente hasta completar ${rules.pendingHours} horas desde su creación.`],['¿Cómo empiezo a usar TécnicoYa?','Entra en Iniciar sesión para crear una cuenta de cliente o técnico independiente. Desde tu cuenta podrás gestionar tus solicitudes y servicios.']].map(([q,a])=><details key={q}><summary>{q}</summary><p>{a}</p></details>)}</section>
 </main><footer className="footer"><a className="brand" href="#inicio"><span className="monogram">t</span><span>TécnicoYa<small>HUANCAYO</small></span></a><p>Talento local. Soluciones cerca.</p><span>Proyecto académico · Universidad Continental</span></footer>
 </>}
