import React,{useEffect,useState,useRef} from 'react';
import Auth from './Auth';
import TechnicianProfile from './TechnicianProfile';
import {AnnouncementFeed,AnnouncementManager} from './Announcements';
import {AccountPanel,AccessManager} from './AccountPanel';
import {can} from './domain/permissions';
import {actDemo,loadDemo,saveDemo,advance} from './domain/demo';
import {rules,specialtyNames,statusNames,subcategoriesFor,subcategoryName} from './domain/matching';
import {api,apiSession,storeSession} from './marketplace-api';

const date=value=>new Date(value).toLocaleString('es-PE',{day:'2-digit',month:'short',hour:'2-digit',minute:'2-digit'});
const money=value=>Number(value).toLocaleString('es-PE',{style:'currency',currency:'PEN'});
const remaining=(deadline,now)=>{const seconds=Math.max(0,Math.ceil((deadline-now)/1000));return `${Math.floor(seconds/60)}:${String(seconds%60).padStart(2,'0')}`};
const demoClient={id:'client-demo',name:'Cliente de demostración',role:'client'};
export default function Marketplace({initialSpecialty='computo',accountOnly=false}){
 const [sessionReady,setSessionReady]=useState(!accountOnly),[requestFilter,setRequestFilter]=useState('all'),[requestSearch,setRequestSearch]=useState(''),[mode,setMode]=useState(accountOnly?'live':'demo'),[state,setState]=useState(()=>accountOnly?{requests:[],technicians:[]}:loadDemo()),[actor,setActor]=useState(()=>accountOnly?(apiSession()?.actor||null):demoClient),[error,setError]=useState(''),[notice,setNotice]=useState(''),[busy,setBusy]=useState(false),[now,setNow]=useState(Date.now());
 const modeRef=useRef(mode);modeRef.current=mode;
 const refresh=async()=>{const token=apiSession()?.token;const result=await api('/state');if(apiSession()?.token!==token||modeRef.current!=='live')return;setState(result.state);setActor(result.actor);setSessionReady(true);storeSession({...apiSession(),actor:result.actor})};
 useEffect(()=>{const expired=()=>{setActor(null);setState({requests:[],technicians:[]});setError('Tu sesión terminó. Vuelve a ingresar.');};window.addEventListener('tecnicoya:session-expired',expired);return()=>window.removeEventListener('tecnicoya:session-expired',expired)},[]);
 useEffect(()=>{if(mode!=='demo')return;const tick=()=>setState(current=>{const updated=advance(structuredClone(current));if(JSON.stringify(updated)===JSON.stringify(current))return current;try{saveDemo(updated)}catch{setError('No pudimos guardar la demo en este navegador.')}return updated});tick();const timer=setInterval(tick,1000);const storage=()=>setState(loadDemo());window.addEventListener('storage',storage);return()=>{clearInterval(timer);window.removeEventListener('storage',storage)}},[mode]);
 useEffect(()=>{const timer=setInterval(()=>setNow(Date.now()),1000);return()=>clearInterval(timer)},[]);
 useEffect(()=>{if(mode!=='live'||!actor)return;refresh().catch(e=>setError(e.message));const timer=setInterval(()=>refresh().catch(e=>setError(e.message)),15000);return()=>clearInterval(timer)},[mode,actor?.id]);
 async function logout(){
  setBusy(true);setError('');
  try{await api('/logout',{})}catch(e){setError('Se cerró la sesión en este dispositivo, pero no se pudo confirmar su revocación en el servidor.')}
  finally{storeSession(null);setActor(null);setState({requests:[],technicians:[]});setSessionReady(false);setRequestFilter('all');setRequestSearch('');setNotice('Sesión cerrada. Puedes ingresar con otra cuenta.');setBusy(false)}
 }
 async function act(action,payload={}){setBusy(true);setError('');setNotice('');try{if(!can(actor,action))throw Error('No tienes permiso para realizar esta acción.');if(mode==='demo'){const updated=actDemo(state,actor,action,payload);saveDemo(updated);setState(updated);if(action==='profile')setActor({...actor,name:payload.name})}else{await api('/actions/'+action,payload);await refresh()}setNotice(action==='create'?'Solicitud registrada. Puedes seguir las respuestas aquí.':'Cambio guardado.');return true}catch(e){setError(e.message);return false}finally{setBusy(false)}}
 function switchMode(next){modeRef.current=next;setSessionReady(next==='demo');setError('');setNotice('');setMode(next);if(next==='demo'){setState(loadDemo());setActor(demoClient)}else{setState({requests:[],technicians:[]});setActor(apiSession()?.actor||null)}}
 const technicians=state.technicians||[], technician=technicians.find(t=>t.id===actor?.id);
 const requests=(state.requests||[]).filter(r=>actor?.role==='admin'||(actor?.role==='client'?r.clientId===actor.id:r.technicianId===actor?.id||r.offers.some(o=>o.technicianId===actor?.id)));
 const visibleRequests=requests.filter(r=>(requestFilter==='all'||r.status===requestFilter)&&[r.description,r.zone,specialtyNames[r.specialty],subcategoryName(r.subcategory),r.id].join(' ').toLocaleLowerCase().includes(requestSearch.toLocaleLowerCase()));
 const offers=requests.filter(r=>r.status==='searching'&&r.offers.some(o=>o.technicianId===actor?.id&&o.status==='pending'));
 return <section className="marketplace section" id="plataforma" aria-labelledby="platform-title">
  <div className={`section-heading ${!actor?'auth-heading-hidden':''}`}><div><span className="kicker">TU ESPACIO EN TÉCNICOYA</span><h2 id="platform-title">{!actor?<>Bienvenido a<br/><em>TécnicoYa.</em></>:<>Todo el servicio.<br/><em>En un solo lugar.</em></>}</h2></div>{!accountOnly&&<div className="mode-switch" aria-label="Modo de funcionamiento"><button aria-pressed={mode==='demo'} onClick={()=>switchMode('demo')}>Explorar demo</button><button aria-pressed={mode==='live'} onClick={()=>switchMode('live')}>Mi cuenta</button></div>}</div>
  {mode==='demo'?<div className="demo-banner"><span><b>Demostración interactiva</b> · Perfiles y tarifas ficticios. Los cambios se guardan solo en este navegador; no se contacta a técnicos reales.</span></div>:actor&&<div className="demo-banner"><span><b>Mi sesión</b> · {actor.name}<br/>Gestiona tu cuenta o sal para ingresar con otra.</span>{actor&&<button className="button outline" disabled={busy} onClick={logout}>{busy?'Saliendo…':'Cerrar sesión / Cambiar cuenta'}</button>}</div>}
  {error&&<p className="error" role="alert">{error}</p>}{notice&&<p className="notice" role="status">{notice}</p>}
  {!actor?<Auth onLogin={data=>{storeSession(data);setSessionReady(false);setActor(data.actor)}}/>:mode==='live'&&!sessionReady?<p role="status">Cargando tu cuenta y verificando permisos…</p>:<>
   <div className="workspace-bar">{mode==='demo'?<div className="role-tabs" aria-label="Rol de demostración">{[['client','Soy cliente'],['technician','Soy técnico'],['admin','Administración']].map(([role,label])=><button key={role} aria-pressed={actor.role===role} onClick={()=>{setError('');setNotice('');setRequestFilter('all');setRequestSearch('');setActor(role==='client'?(state.users?.find(u=>u.id===demoClient.id)||demoClient):role==='admin'?(state.users?.find(u=>u.id==='admin-demo')||{id:'admin-demo',name:'Administrador de demo',role}):{id:technicians[0]?.id,name:technicians[0]?.name||'Técnico',role})}}>{label}{role==='technician'&&offers.length>0?<span className="count">{offers.length}</span>:null}</button>)}</div>:<h3>{actor.name} <small>· {actor.role==='client'?'Cliente':actor.role==='technician'?'Técnico':'Administrador'}</small></h3>}
    {mode==='demo'&&actor.role==='technician'&&<label className="tech-select">Perfil de prueba<select value={actor.id} onChange={e=>{const t=technicians.find(t=>t.id===e.target.value);setActor({id:t.id,name:t.name,role:'technician'})}}>{technicians.map(t=><option key={t.id} value={t.id}>{t.name}</option>)}</select></label>}
   </div>
   {actor.role==='admin'?<AnnouncementManager items={state.announcements||[]} act={act} busy={busy}/>:<AnnouncementFeed items={state.announcements||[]} role={actor.role}/>}
   <AccountPanel key={actor.id+actor.name} actor={actor} requests={requests} act={act} busy={busy}/>
   {actor.role!=='admin'&&<div className="account-filters"><label>Buscar solicitud<input type="search" value={requestSearch} onChange={e=>setRequestSearch(e.target.value)} placeholder="Servicio, zona o descripción"/></label><label>Estado de la solicitud<select value={requestFilter} onChange={e=>setRequestFilter(e.target.value)}><option value="all">Todos los estados</option>{Object.entries(statusNames).map(([id,label])=><option key={id} value={id}>{label}</option>)}</select></label></div>}
   {actor.role!=='admin'&&requests.length>0&&!visibleRequests.length&&<p role="status">No hay solicitudes que coincidan con los filtros.</p>}
   {actor.role==='client'&&<div className="client-layout"><RequestForm specialty={initialSpecialty} busy={busy} onSubmit={payload=>act('create',payload)}/><div className="request-list"><div className="list-heading"><h3>Mis solicitudes</h3><span>{requests.length}</span></div>{!requests.length&&<Empty title="Tu primera solución empieza aquí" text="Cuéntanos la falla. Buscaremos hasta tres técnicos verificados de tu rubro y zona."/>}{visibleRequests.map(r=><RequestCard key={r.id} request={r} technicians={technicians} actor={actor} act={act} busy={busy} now={now}/>)}</div></div>}
   {actor.role==='technician'&&technician&&<><div className="technician-summary glass"><div className="avatar">{technician.name.split(' ').map(s=>s[0]).slice(0,2).join('')}</div><div><h3>{technician.name}</h3><p>{technician.specialties.map(s=>specialtyNames[s]).join(' · ')} · {technician.zone}</p><span>{technician.reviews?`${Number(technician.rating).toFixed(1)} ★ · ${technician.reviews} calificaciones`:'Sin calificaciones aún'} · {technician.years} años de experiencia</span></div><div className="availability"><span className={'status '+(technician.verified?'':'pending')}>{technician.verified?'Perfil verificado':'Verificación pendiente'}</span><label><input type="checkbox" checked={technician.available} disabled={busy||!technician.verified} onChange={e=>act('availability',{available:e.target.checked})}/> Disponible para solicitudes</label></div></div><TechnicianProfile key={technician.id} technician={technician} requests={requests} act={act} busy={busy}/><div className="list-heading"><h3>Solicitudes y atenciones</h3><span>{offers.length} por responder</span></div>{!requests.length&&<Empty title="Aquí llegarán tus oportunidades" text="Las solicitudes aparecerán cuando coincidan con tu especialidad, cobertura y disponibilidad."/>}<div className="job-grid">{visibleRequests.map(r=><RequestCard key={r.id} request={r} technicians={technicians} actor={actor} act={act} busy={busy} now={now}/>)}</div></>}
   {actor.role==='admin'&&<Admin state={state} actor={actor} act={act} busy={busy} now={now}/>}
  </>}
 </section>
}
function Empty({title,text}){return <div className="empty-state"><span aria-hidden="true">↗</span><h4>{title}</h4><p>{text}</p></div>}
export function RequestForm({specialty,busy,onSubmit}){const [category,setCategory]=useState(specialty);useEffect(()=>setCategory(specialty),[specialty]);return <form className="form-card glass" onSubmit={e=>{e.preventDefault();onSubmit(Object.fromEntries(new FormData(e.currentTarget)))}}><div className="form-title"><h3>¿Qué necesitas resolver?</h3></div><label>Rubro<select name="specialty" value={category} onChange={e=>setCategory(e.target.value)}>{Object.entries(specialtyNames).map(([id,name])=><option key={id} value={id}>{name}</option>)}</select></label><label>Subcategoría<select name="subcategory" key={category} required defaultValue=""><option value="" disabled>Selecciona el servicio</option>{subcategoriesFor(category).map(s=><option key={s.id} value={s.id}>{s.name}</option>)}</select></label><label>Zona de atención<select name="zone">{rules.zones.map(z=><option key={z}>{z}</option>)}</select></label><label>Dirección o referencia<input name="address" required minLength={5} maxLength={200} placeholder="Calle, número y una referencia"/></label><label>Describe la falla<textarea name="description" rows={4} required minLength={10} maxLength={2000} placeholder="¿Qué equipo o instalación presenta el problema?"/></label><button className="button primary submit" disabled={busy}>{busy?'Procesando…':'Encontrar un técnico'} <span>↗</span></button><p className="form-footnote">Primero revisas al técnico propuesto y confirmas la visita.</p></form>}
export function RequestCard({request:r,technicians,actor,act,busy,now}){
 const technician=technicians.find(t=>t.id===r.technicianId), offer=r.offers.find(o=>o.technicianId===actor.id),[rating,setRating]=useState('5');
 const client=actor.role==='client', assigned=actor.role==='technician'&&r.technicianId===actor.id;
 const candidates=r.offers.filter(o=>['pending','accepted'].includes(o.status));
 return <article className="request-card glass"><div className="request-top"><span className={'status status-'+r.status}>{statusNames[r.status]}</span><small>#{r.id.slice(0,8)}</small></div><h3>{specialtyNames[r.specialty]} <span>· {r.zone}</span></h3><p className="request-subcategory">{subcategoryName(r.subcategory)}</p><p>{r.description}</p><small>{date(r.createdAt)}</small>
  {['searching','pending_availability'].includes(r.status)&&<p className="deadline">{r.status==='searching'?`${r.offers.filter(o=>o.status==='pending').length} técnicos notificados · respuesta hasta en ${rules.responseMinutes} min`:`Buscaremos disponibilidad hasta ${date(r.pendingUntil)}`}</p>}
  {client&&candidates.length>0&&<details className="candidates"><summary>Ver perfiles y tarifas de visita</summary>{candidates.map(o=>{const t=technicians.find(t=>t.id===o.technicianId);return t&&<div key={t.id}><b>{t.name}</b><span>{t.reviews?Number(t.rating).toFixed(1)+' ★':'Sin reseñas'} · {t.years} años · {money(t.fee)}</span></div>})}<small>Repuestos y trabajos adicionales se acuerdan antes de ejecutarlos.</small></details>}
  {technician&&<div className="proposed-tech"><div className="avatar small">{technician.name.slice(0,1)}</div><div><b>{technician.name}</b><span>Tarifa de visita: {money(r.agreedFee??technician.fee)}</span></div></div>}
  {r.address&&(client||actor.role==='admin'||(assigned&&['confirmed','in_progress','completed','rated'].includes(r.status)))&&<p>Dirección: {r.address}</p>}
  <div className="request-actions">
   {client&&r.status==='proposed'&&<button className="button primary" disabled={busy} onClick={()=>act('confirm',{id:r.id})}>Confirmar servicio</button>}
   {client&&['searching','pending_availability','proposed','confirmed'].includes(r.status)&&<button className="button outline" disabled={busy} onClick={()=>act('cancel',{id:r.id})}>Cancelar solicitud</button>}
   {actor.role==='technician'&&r.status==='searching'&&offer?.status==='pending'&&<><span className="response-clock">Responde en {remaining(offer.expiresAt,now)}</span><button className="button primary" disabled={busy} onClick={()=>act('accept',{id:r.id})}>Aceptar</button><button className="button outline" disabled={busy} onClick={()=>act('decline',{id:r.id})}>Rechazar</button></>}
   {assigned&&r.status==='confirmed'&&<button className="button primary" disabled={busy} onClick={()=>act('start',{id:r.id})}>Iniciar servicio</button>}
   {assigned&&r.status==='in_progress'&&<button className="button primary" disabled={busy} onClick={()=>act('complete',{id:r.id})}>Finalizar servicio</button>}
  </div>
  {client&&r.status==='completed'&&(now<r.ratingUntil?<form className="rating-form" onSubmit={e=>{e.preventDefault();act('rate',{id:r.id,rating:Number(rating)})}}><label>Califica hasta {date(r.ratingUntil)}<select value={rating} onChange={e=>setRating(e.target.value)}>{[5,4,3,2,1].map(n=><option key={n} value={n}>{n} {n===1?'estrella':'estrellas'}</option>)}</select></label><button className="button primary" disabled={busy}>Enviar calificación</button></form>:<p className="deadline">El plazo de {rules.ratingHours} horas para calificar terminó.</p>)}
  {r.rating&&<p className="rating-result">Calificación del cliente: {r.rating} / 5 ★</p>}
  <details className="timeline"><summary>Historial de la solicitud</summary><ol>{r.events.map((event,i)=><li key={i}><time>{date(event.at)}</time><span>{event.text}</span></li>)}</ol></details>
 </article>
}
function Admin({state,actor,act,busy,now}){const [filter,setFilter]=useState('active');const active=state.requests.filter(r=>!['completed','rated','cancelled','unassigned'].includes(r.status));return <><AccessManager users={state.users||[]} events={state.accessEvents||[]} act={act} busy={busy}/><div className="admin-stats">{[['Solicitudes activas',active.length],['Técnicos verificados',state.technicians.filter(t=>t.verified).length],['Disponibles ahora',state.technicians.filter(t=>t.verified&&t.available).length],['Por verificar',state.technicians.filter(t=>!t.verified).length]].map(([label,value])=><div className="glass" key={label}><strong>{value}</strong><span>{label}</span></div>)}</div><h3>Verificación de técnicos</h3><div className="verification-list">{state.technicians.map(t=><div className="glass verification-row" key={t.id}><div><b>{t.name}</b><p>{t.specialties.map(s=>specialtyNames[s]).join(' · ')} · {t.zone}</p><small>{t.years} años · Tarifa de visita {money(t.fee)}</small></div><button className="button outline" disabled={busy} onClick={()=>act('verify',{technicianId:t.id,verified:!t.verified})}>{t.verified?'Suspender habilitación':'Verificar y habilitar'}</button></div>)}</div><h3>Cobertura por zona y especialidad</h3><p className="muted">Técnicos verificados y disponibles. Una persona puede cubrir más de una zona.</p><div className="table-scroll"><table><caption>Disponibilidad actual por rubro</caption><thead><tr><th>Zona</th>{Object.values(specialtyNames).map(s=><th key={s}>{s}</th>)}</tr></thead><tbody>{rules.zones.map(z=><tr key={z}><th scope="row">{z}</th>{rules.specialties.map(s=><td key={s}>{state.technicians.filter(t=>t.verified&&t.available&&t.zones.includes(z)&&t.specialties.includes(s)).length}</td>)}</tr>)}</tbody></table></div><div className="list-heading"><h3>Supervisión de solicitudes</h3><select aria-label="Filtrar solicitudes" value={filter} onChange={e=>setFilter(e.target.value)}><option value="active">Activas</option><option value="all">Todas</option></select></div><div className="job-grid">{(filter==='active'?active:state.requests).map(r=><RequestCard key={r.id} request={r} technicians={state.technicians} actor={actor} act={act} busy={busy} now={now}/>)}</div>{!state.requests.length&&<Empty title="No hay solicitudes registradas" text="Las nuevas solicitudes y sus cambios de estado aparecerán aquí."/>}</>}
