"""Genera documentación y DDL de referencia. No abre conexiones ni modifica bases."""
from pathlib import Path
import json, re, hashlib

ROOT=Path(__file__).resolve().parent
tables=[]
def col(n,t,d,null=False,default=None,ref=None,check=None,gen=None):
    return dict(name=n,type=t,description=d,nullable=null,default=default,reference=ref,check=check,generated=gen)
def f(n,target,d=None,null=False): return col(n,'BIGINT UNSIGNED',d or 'Referencia a '+target,null,ref=target+'.id')
def txt(n,d,size=255,null=False):return col(n,f'VARCHAR({size})',d,null)
def tm(n,d,null=False):return col(n,'DATETIME(6)',d,null)
def b(n,d,default=0):return col(n,'TINYINT UNSIGNED',d,default=str(default),check=f'`{n}` IN (0,1)')
def e(n,values,d,default=None):
    return col(n,'VARCHAR(32)',d+' Valores: '+', '.join(values)+'.',default=None if default is None else "'"+default+"'",check=f'`{n}` IN ('+','.join("'"+x+"'" for x in values)+')')
def num(n,d,default=None,null=False):return col(n,'INT UNSIGNED',d,null,default)
def money(n,d,null=False):return col(n,'DECIMAL(12,2)',d,null,check=f'`{n}` >= 0')
def js(n,d,null=False):return col(n,'JSON',d,null)
def body(n,d,null=False):return col(n,'TEXT',d,null)
def ver():return num('version','Control de concurrencia optimista; incrementa en cada cambio.','1')
def generated(n,t,expr,d):return col(n,t,d,True,gen=expr)
def T(name,kind,module,description,fields,uq=(),ix=(),checks=(),rules=(),privacy='Restringido por rol y pertenencia.',stamp='both',pk=None,identity=True):
    fields=list(fields)
    if identity:fields.insert(0,col('id','BIGINT UNSIGNED','Identificador interno inmutable.',default='AUTO_INCREMENT'))
    if stamp:fields.append(col('created_at','DATETIME(6)','Fecha de creación UTC.',default='CURRENT_TIMESTAMP(6)'))
    if stamp=='both':fields.append(col('updated_at','DATETIME(6)','Último cambio UTC; lo actualiza la aplicación.',default='CURRENT_TIMESTAMP(6)'))
    obj=dict(name=name,classification=kind,module=module,description=description,columns=fields,primary_key=list(pk or ['id']),unique=[list(x) for x in uq],indexes=[list(x) for x in ix],checks=list(checks),application_rules=list(rules),privacy=privacy)
    tables.append(obj);return obj

# Identidad, roles y perfiles.
T('roles','Independiente','F','Roles base del producto.',[txt('code','Código estable client, technician o admin.',40),txt('name','Nombre legible.',80),b('active','Disponible para cuentas nuevas.',1)],uq=[('code',)],rules=['Un rol vigente por cuenta, propuesta conservadora mientras P20 permanece abierto. El administrador responsable es un permiso adicional, no un cuarto actor.'],privacy='Catálogo interno; no admite alta pública de roles.')
T('permissions','Independiente','F','Acciones autorizables.',[txt('code','Ej.: requests.reassign, audit.read, admins.manage.',100),txt('description','Significado del permiso.')],uq=[('code',)],privacy='Catálogo de seguridad.')
T('users','Dependiente','F','Identidad y acceso; no contiene datos específicos de atención.',[f('role_id','roles'),txt('name','Nombre visible.'),txt('email','Correo normalizado en minúsculas y sin espacios.',254),txt('password','Hash bcrypt; nunca contraseña original.'),txt('phone','Teléfono normalizado; no público.',20,True),tm('email_verified_at','Verificación de correo, si se habilita.',True),b('is_active','Cuenta autorizada para acceso.',1),num('auth_version','Versión de autorización para invalidar acceso/canales.','1'),tm('anonymized_at','Anonimización ejecutada conforme a política validada.',True),txt('remember_token','Token de recordar sesión; opcional, no activar por defecto.',100,True),ver()],uq=[('email',)],ix=[('role_id','is_active')],rules=['Registro público admite solo client o technician. Rol, is_active y auth_version no son asignables desde perfil.','La cuenta se conserva como identidad seudónima si existen referencias históricas; cierre/retención requieren P08.','Bloqueo de cliente efectivo depende también de client_blocks; revocar sesiones y aumentar auth_version en transacción.'],privacy='Nombre/contacto/datos de acceso privados; contraseña solo para verificación de hash.')
T('role_permissions','Pivot','F','Relación muchos a muchos entre rol y permiso.',[f('role_id','roles'),f('permission_id','permissions')],pk=['role_id','permission_id'],identity=False,stamp='created',privacy='Solo administración de seguridad.',rules=['admins.manage no se asigna al rol admin general.'])
T('user_permissions','Pivot','F','Permisos excepcionales de administración por usuario.',[f('user_id','users'),f('permission_id','permissions'),f('granted_by','users','Administrador responsable que concedió el permiso.'),tm('granted_at','Fecha UTC de concesión.')],pk=['user_id','permission_id'],identity=False,stamp=False,rules=['Solo usuarios de rol admin reciben permisos excepcionales; comprobar mediante Policy, no CHECK entre tablas. Revocación auditada; mantener al menos un responsable habilitado.'],privacy='Solo responsable de cuentas administrativas.')
T('client_profiles','Dependiente','F','Datos del cliente MYPE u hogar.',[f('user_id','users'),e('client_type',['household','mype'],'Tipo de cliente.'),txt('business_name','Nombre del negocio si corresponde.',180,True),f('default_district_id','districts',null=True),body('default_address','Dirección habitual privada, editable en cada solicitud.',True),ver()],uq=[('user_id',)],rules=['user_id debe corresponder al rol client; la dirección de una solicitud se copia, no cambia al editar este perfil.'])
T('client_blocks','Dependiente','F','Historial explícito de bloqueos y levantamientos.',[f('client_id','client_profiles'),f('blocked_by','users'),body('reason','Motivo obligatorio.'),tm('blocked_at','Inicio del bloqueo.'),tm('expires_at','Fin automático si se aprueba bloqueo temporal; de otro modo NULL.',True),f('lifted_by','users',null=True),tm('lifted_at','Levantamiento efectivo.',True),body('lift_reason','Motivo del levantamiento.',True),e('status',['active','lifted','expired'],'Estado del bloqueo.','active'),generated('active_client_id','BIGINT UNSIGNED',"CASE WHEN status = 'active' THEN client_id ELSE NULL END",'Un único bloqueo activo por cliente.'),ver()],uq=[('active_client_id',)],ix=[('client_id','blocked_at'),('status','expires_at')],checks=['expires_at IS NULL OR expires_at > blocked_at'],rules=['Levantar o vencer actualiza status explícitamente; una columna generada no compara NOW(). Política temporal y efecto sobre servicios en curso pendientes P18.','Consulta protegida; acceso de cliente solo a explicación permitida.'])
T('technician_profiles','Dependiente','F/A','Prestador independiente o empresa de una cuenta.',[f('user_id','users'),e('provider_type',['independent','company'],'Tipo de prestador.','independent'),txt('display_name','Nombre profesional.',180),body('bio','Presentación pública.',True),e('status',['pending_verification','active','inactive','suspended'],'Estado operativo.','pending_verification'),e('verification_status',['pending','approved','rejected'],'Resultado de revisión separado del estado operativo.','pending'),num('experience_years','Experiencia declarada.','0'),f('primary_district_id','districts',null=True),b('available_now','Disposición a recibir atención inmediata; no sustituye agenda.'),txt('whatsapp','Contacto habilitado solo tras asignación.',20,True),tm('verified_at','Última habilitación.',True),f('verified_by','users',null=True),ver()],uq=[('user_id',)],ix=[('status','verification_status','available_now')],rules=['user_id corresponde a rol technician. Verificación rechazada se conserva en verification_status/reviews sin inventar un estado operativo fuera de F0 (P22).','Status active exige verification_status approved y cuenta habilitada. Disponibilidad exige además cobertura, subcategoría, franja y ausencia de pausa.'],privacy='Bio/nombre profesional públicos; WhatsApp restringido y revisión privada.')
T('technician_reviews','Dependiente','F','Decisiones de revisión del prestador, inmutables.',[f('technician_id','technician_profiles'),f('reviewer_id','users'),e('decision',['approve','reject','request_changes'],'Resultado de revisión.'),body('reason','Motivo y alcance de la revisión.'),js('checklist','Resultados de identidad/contacto, servicios, zona, tarifa, experiencia y evidencia; sin copiar documentos.'),tm('reviewed_at','Momento de revisión.')],ix=[('technician_id','reviewed_at')],stamp='created',rules=['Administrador autorizado; actualizar resumen de technician_profiles y auditoría en misma transacción. No acredita certificación profesional integral.'])
T('technician_status_events','Dependiente','F','Cambios operativos y motivos de suspensión.',[f('technician_id','technician_profiles'),f('actor_id','users'),txt('from_status','Estado anterior.',32),txt('to_status','Estado nuevo.',32),body('reason','Motivo del cambio.'),tm('occurred_at','Instante UTC.')],ix=[('technician_id','occurred_at')],stamp='created',rules=['Transición validada por dominio y políticas P18; append-only.'])

# Archivos, evidencia y catálogo.
T('media_files','Dependiente','F','Metadatos de archivo; los bytes se guardan fuera de MySQL.',[f('owner_id','users'),txt('disk','Almacenamiento autorizado.',40),txt('storage_key','Ruta interna generada, nunca aceptada del navegador.',255),txt('original_name','Nombre original saneado.',255),txt('mime_type','Tipo verificado por contenido.',120),col('byte_size','BIGINT UNSIGNED','Tamaño del archivo en bytes.'),col('sha256','CHAR(64)','Hash de integridad; no prueba seguridad.'),e('visibility',['private','public'],'Exposición permitida.','private'),e('scan_status',['pending','clean','rejected'],'Validación de archivo.','pending'),tm('retired_at','Retiro lógico.',True)],uq=[('disk','storage_key')],ix=[('owner_id','created_at'),('scan_status','created_at')],rules=['Un archivo private no se hace público reutilizándolo en carrusel o portafolio. Crear copia pública validada si corresponde.','Tipos, cantidad y tamaño definitivos P17; no servir archivo rechazado o aún sin validar.'],privacy='Storage_key nunca concede acceso; servir con Policy por vínculo.')
T('technician_documents','Dependiente','F','Documento privado presentado para verificación.',[f('technician_id','technician_profiles'),f('media_id','media_files'),txt('document_type','Tipo permitido de evidencia documental.',60),e('review_status',['pending','approved','rejected'],'Estado de revisión del documento.','pending'),f('reviewed_by','users',null=True),tm('reviewed_at','Fecha de evaluación.',True),body('review_note','Motivo administrativo.',True),tm('valid_until','Vencimiento documental si aplica.',True),ver()],uq=[('media_id',)],ix=[('technician_id','review_status')],rules=['Propietario del archivo debe ser prestador; visibility=private. Solo técnico titular y administrador de revisión.'])
T('review_documents','Pivot','F','Documentos efectivamente examinados en una revisión.',[f('review_id','technician_reviews'),f('document_id','technician_documents')],pk=['review_id','document_id'],identity=False,stamp='created',rules=['Ambas referencias pertenecen al mismo técnico; conservar aunque posteriormente se presente otro documento.'])
T('portfolio_items','Dependiente','F','Trabajo publicado en el portafolio del técnico.',[f('technician_id','technician_profiles'),f('subcategory_id','subcategories',null=True),txt('title','Título del trabajo.',160),body('description','Descripción pública sin datos de terceros.',True),col('performed_on','DATE','Fecha declarada del trabajo.',True),e('status',['draft','published','retired'],'Visibilidad del trabajo.','draft'),ver()],ix=[('technician_id','status','created_at')],rules=['Moderación y máximos de contenido P17. No reutilizar fotos privadas de clientes sin base autorizada.'])
T('portfolio_images','Pivot','F','Galería ordenada de imágenes de un trabajo.',[f('portfolio_id','portfolio_items'),f('media_id','media_files'),num('position','Orden visual.','0'),txt('caption','Pie de foto.',180,True)],pk=['portfolio_id','media_id'],identity=False,uq=[('portfolio_id','position')],stamp='created',rules=['Archivo público validado del mismo técnico; el trabajo debe estar publicado para mostrarlo.'])
T('specialties','Independiente','F','Tres especialidades base del marketplace.',[txt('code','Código estable.',40),txt('name','Nombre visible.',120),body('description','Descripción del rubro.',True),f('hero_media_id','media_files',null=True),b('active','Habilitada para nuevas solicitudes.',1),num('display_order','Orden de presentación.','0'),ver()],uq=[('code',)],ix=[('active','display_order')],rules=['Clasificación independiente por autonomía de catálogo; hero_media_id es dependencia opcional de imagen. No ampliar rubros sin cambio aprobado.'],privacy='Catálogo público activo.')
T('subcategories','Dependiente','F/A','Catálogo de aproximadamente 30 servicios con foto del carrusel.',[f('specialty_id','specialties'),txt('code','Código estable único; ej. computo-hardware.',80),txt('name','Nombre del servicio.',180),body('description','Alcance del servicio.',True),f('carousel_media_id','media_files',null=True),money('reference_fee','Tarifa orientativa del catálogo, no cobro.',True),col('currency','CHAR(3)','Código de moneda; propuesta PEN sujeta a P01.',default="'PEN'"),num('estimated_minutes','Estimación general; pendiente calibración P15.',null=True),b('active','Disponible para nuevas solicitudes.',1),num('display_order','Posición en carrusel.','0'),ver()],uq=[('code',),('specialty_id','name')],ix=[('specialty_id','active','display_order')],rules=['Al publicar se exige imagen pública válida (durante borrador puede ser NULL). Desactivar no elimina solicitudes previas.','Tarifa global es referencial; tarifas de cada técnico se registran en technician_services y versiones.'],privacy='Datos públicos; auditoría al modificar.')
T('districts','Independiente','F/A','Cobertura por distritos, sin geolocalización personal.',[txt('code','Código interno o ubigeo validado.',12),txt('name','Nombre del distrito.',120),b('active','Cobertura operativa.',1),ver()],uq=[('code',),('name',)],privacy='Catálogo público; Huancayo/El Tambo/Chilca propuestos, P03.')
T('district_distances','Pivot','B','Referencia dirigida de distancia aproximada entre centros de distrito.',[f('from_district_id','districts'),f('to_district_id','districts'),col('distance_km','DECIMAL(8,3)','Distancia aproximada.',check='distance_km >= 0'),txt('source','Procedencia/metodología de la referencia.',255),tm('measured_at','Fecha de referencia.')],identity=False,pk=['from_district_id','to_district_id'],rules=['Datos de referencia P15; no representa ruta ni posición del usuario. Simetría solo si metodología la justifica.'],privacy='Referencia pública no personal.')
T('technician_specialties','Pivot','A/F','Especialidades declaradas y revisadas del técnico.',[f('technician_id','technician_profiles'),f('specialty_id','specialties'),e('verification_status',['pending','approved','rejected'],'Habilitación por especialidad.','pending'),f('reviewed_by','users',null=True),tm('reviewed_at','Fecha de revisión.',True)],identity=False,pk=['technician_id','specialty_id'],rules=['Subcategorías ofrecidas deben pertenecer a una especialidad habilitada cuando se active el servicio.'])
T('technician_services','Pivot','A/B','Relación técnico-subcategoría con condiciones y tarifa vigente.',[f('technician_id','technician_profiles'),f('subcategory_id','subcategories'),money('reference_fee','Tarifa de visita/oferta referencial vigente.'),col('currency','CHAR(3)','Moneda propuesta.',default="'PEN'"),num('experience_years','Experiencia declarada en servicio.','0'),b('active','Servicio disponible para matching.',1),num('current_rate_version','Versión vigente de tarifa.','1'),ver()],uq=[('technician_id','subcategory_id')],ix=[('subcategory_id','active','technician_id')],rules=['Pivot enriquecida con PK sustituta por referencias a versiones de tarifa. Especialidad del servicio y habilitación técnica deben coincidir.'])
T('service_rate_versions','Dependiente','A/F','Historial inmutable de tarifas declaradas.',[f('technician_service_id','technician_services'),num('version_no','Secuencia de tarifa.'),money('reference_fee','Importe histórico.'),col('currency','CHAR(3)','Moneda de esa versión.'),f('changed_by','users'),body('reason','Motivo del cambio.',True),tm('effective_from','Inicio de vigencia.')],uq=[('technician_service_id','version_no')],ix=[('technician_service_id','effective_from')],stamp='created',rules=['Actualizar tarifa actual y agregar versión en transacción; versiones inmutables. Ventanas de vigencia se derivan del siguiente registro.'])
T('technician_districts','Pivot','A/B','Distritos atendidos por técnico.',[f('technician_id','technician_profiles'),f('district_id','districts'),b('active','Cobertura ofrecida.',1)],identity=False,pk=['technician_id','district_id'],rules=['Distrito principal debe estar cubierto al habilitar; no habilita distritos fuera del catálogo activo.'])
T('availability_slots','Dependiente','A/D','Horario declarado recurrente o franja puntual.',[f('technician_id','technician_profiles'),e('kind',['weekly','one_off'],'Patrón de disponibilidad.'),col('weekday','TINYINT UNSIGNED','1=lunes a 7=domingo; solo weekly.',True,check='weekday BETWEEN 1 AND 7'),col('local_start','TIME','Hora local para weekly.',True),col('local_end','TIME','Hora local final para weekly.',True),col('valid_from','DATE','Desde cuándo aplica weekly.',True),col('valid_until','DATE','Último día weekly; NULL sin límite.',True),tm('starts_at','Inicio UTC de one_off.',True),tm('ends_at','Fin UTC de one_off.',True),txt('timezone','Zona de interpretación; America/Lima.',60),b('active','Franja habilitada.',1),ver()],ix=[('technician_id','active','weekday'),('technician_id','starts_at')],checks=["(kind='weekly' AND weekday IS NOT NULL AND local_start IS NOT NULL AND local_end IS NOT NULL AND local_end>local_start AND valid_from IS NOT NULL AND starts_at IS NULL AND ends_at IS NULL) OR (kind='one_off' AND weekday IS NULL AND local_start IS NULL AND local_end IS NULL AND valid_from IS NULL AND valid_until IS NULL AND starts_at IS NOT NULL AND ends_at IS NOT NULL AND ends_at>starts_at)", 'valid_until IS NULL OR valid_until >= valid_from'],rules=['Diseño propuesto de horarios; dividir franjas que cruzan medianoche. La cita confirmada es appointments, no esta declaración. Solapamientos y duración P16.'])
T('technician_pauses','Dependiente','A/B','Pausas temporales de recepción de trabajo.',[f('technician_id','technician_profiles'),tm('starts_at','Inicio de pausa.'),tm('ends_at','Fin previsto; NULL hasta reanudación.',True),tm('cancelled_at','Fin anticipado/retirada.',True),txt('reason','Motivo privado de pausa.',255,True),ver()],ix=[('technician_id','starts_at','ends_at')],checks=['ends_at IS NULL OR ends_at > starts_at'],rules=['Elegibilidad evalúa intervalo y cancelación; el checkbox disponible no ignora una pausa vigente.'])

# Reglas versionadas, solicitudes y matching.
T('rule_parameters','Independiente','F','Definiciones de parámetros editables del negocio.',[txt('code','Ej.: offer_sla_minutes, pending_hours, rating_hours.',80),e('value_type',['integer','decimal','boolean','string'],'Tipo lógico del valor.'),txt('unit','Unidad: minutos, horas, cantidad, etc.',30),body('description','Significado y ámbito.'),col('min_value','DECIMAL(14,4)','Límite inferior si numérico.',True),col('max_value','DECIMAL(14,4)','Límite superior si numérico.',True),b('required','Obligatorio al publicar una versión.',1),b('editable','Puede cambiarse con permiso.',1)],uq=[('code',)],checks=['min_value IS NULL OR max_value IS NULL OR min_value <= max_value'],privacy='Lectura filtrada; escritura administrativa.')
T('rule_versions','Dependiente','F','Versiones de configuración; publicación no sobrescribe anteriores.',[num('version_no','Número global de versión.'),e('status',['draft','published','retired'],'Estado documental.','draft'),f('created_by','users'),f('published_by','users',null=True),body('change_reason','Justificación del cambio.'),tm('effective_at','Inicio acordado de vigencia.',True),tm('published_at','Momento de publicación.',True),col('content_hash','CHAR(64)','Hash del contenido canónico al publicar.',True)],uq=[('version_no',)],ix=[('status','effective_at')],rules=['Publicar comprueba parámetros obligatorios, tipo/rango, fila de pesos y actor; versiones publicadas son inmutables. Se elige última vigencia <= ahora, con secuencia determinista. P19 define aplicación a servicios abiertos.'])
T('rule_values','Pivot','F','Valor de cada parámetro dentro de una versión.',[f('rule_version_id','rule_versions'),f('parameter_id','rule_parameters'),js('value_json','Valor escalar, no objeto arbitrario; debe cumplir tipo de rule_parameters.')],identity=False,pk=['rule_version_id','parameter_id'],stamp='created',rules=['Validar tipo, unidad y rango al publicar; CHECK no consulta otra tabla. Los pesos están en matching_weights, no duplicados aquí.'])
T('matching_weights','Dependiente','F/B','Los cuatro pesos de una versión; suma comprobable en una fila.',[f('rule_version_id','rule_versions'),col('proximity_pct','DECIMAL(5,2)','Peso cercanía.',check='proximity_pct BETWEEN 0 AND 100'),col('price_pct','DECIMAL(5,2)','Peso tarifa.',check='price_pct BETWEEN 0 AND 100'),col('rating_pct','DECIMAL(5,2)','Peso historial.',check='rating_pct BETWEEN 0 AND 100'),col('experience_pct','DECIMAL(5,2)','Peso experiencia.',check='experience_pct BETWEEN 0 AND 100')],identity=False,pk=['rule_version_id'],checks=['proximity_pct + price_pct + rating_pct + experience_pct = 100.00'],stamp='created',rules=['Semilla inicial 35/20/30/15. Cuatro columnas justificadas por factores fijos del MVP; no mezclar números decimales aproximados FLOAT.'])
T('service_requests','Dependiente','A/D','Solicitud del cliente; datos privados y fotografía de tarifa/reglas.',[f('client_id','client_profiles'),f('subcategory_id','subcategories'),f('district_id','districts'),body('description','Falla descrita por cliente.'),body('address','Dirección exacta privada.'),e('mode',['asap','scheduled'],'Modalidad.','asap'),tm('preferred_start_at','Inicio deseado si programada.',True),tm('preferred_end_at','Fin deseado si programada.',True),e('source',['automatic','profile'],'Ruta inicial.','automatic'),f('target_technician_id','technician_profiles',null=True),e('status',['registered','sent','pending_availability','assigned','in_progress','completed','closed','unrated','cancelled','expired'],'Estado global.','registered'),money('reference_fee_snapshot','Tarifa referencial del catálogo al enviar.',True),col('currency','CHAR(3)','Moneda propuesta.',default="'PEN'"),f('rule_version_id','rule_versions',null=True),tm('submitted_at','Confirmación de envío.',True),tm('pending_since','Inicio del episodio de falta de disponibilidad.',True),tm('pending_expires_at','Límite persistido de 24 h según versión.',True),num('search_generation','Generación que invalida jobs antiguos.','0'),tm('cancelled_at','Momento de cancelación.',True),body('cancellation_reason','Motivo si se cancela.',True),tm('closed_at','Cierre global una vez resuelta regla de dos técnicos.',True),ver()],ix=[('client_id','created_at'),('status','pending_expires_at'),('subcategory_id','district_id','status')],checks=["(mode='asap' AND preferred_start_at IS NULL AND preferred_end_at IS NULL) OR (mode='scheduled' AND preferred_start_at IS NOT NULL AND preferred_end_at IS NOT NULL AND preferred_end_at>preferred_start_at)","(source='automatic' AND target_technician_id IS NULL) OR (source='profile' AND target_technician_id IS NOT NULL)",'(pending_since IS NULL AND pending_expires_at IS NULL) OR (pending_since IS NOT NULL AND pending_expires_at IS NOT NULL AND pending_expires_at > pending_since)'],rules=['Cliente, dirección y subcategoría validados antes de submission. Para states distintos de registered se exigen submitted_at y versión publicada en transacción.','Tarifa del catálogo es informativa; condición propuesta por técnico se copia en offers/participations. No guardar una única calificación en esta tabla.','P10/P11/P12/P13/P14/P19/P22 conservan límites, tiempos, cierre global y elección pendientes.'],privacy='Solo zona/descripcion/fotos permitidas a notificados; dirección y contacto únicamente asignados y gestión autorizada.')
T('request_attachments','Pivot','A','Galería de evidencias de la falla.',[f('request_id','service_requests'),f('media_id','media_files'),f('uploaded_by','users'),num('position','Orden visual.','0'),txt('caption','Descripción breve.',180,True)],identity=False,pk=['request_id','media_id'],uq=[('request_id','position')],stamp='created',rules=['Archivo privado validado y del cliente titular; comprobar pertenencia en lectura, carga y eliminación.'])
T('request_events','Dependiente','D','Historial cronológico del servicio, append-only.',[f('request_id','service_requests'),f('actor_id','users',null=True),txt('event_type','Tipo de evento de dominio.',80),txt('from_status','Estado anterior si hubo transición.',32,True),txt('to_status','Estado nuevo si hubo transición.',32,True),body('summary','Resumen sin información privada excesiva.'),js('metadata','IDs y datos mínimos estructurados; no archivos ni contraseñas.',True),tm('occurred_at','Instante del evento.'),txt('correlation_id','Correlación con petición o job.',64),num('request_version','Versión de solicitud resultante.')],ix=[('request_id','occurred_at','id')],stamp=False,rules=['Evento ordinario de negocio no sustituye auditoría de decisiones sensibles. actor NULL significa sistema; metadata indica job sin secretos.'])
T('matching_runs','Dependiente','B','Ejecución reproducible del ranking.',[f('request_id','service_requests'),f('rule_version_id','rule_versions'),num('generation','Generación de búsqueda.'),tm('started_at','Inicio del cálculo.'),tm('finished_at','Fin del cálculo.',True),e('status',['running','completed','failed'],'Resultado técnico.','running'),js('rules_snapshot','Fotografía de parámetros y pesos utilizados.'),txt('algorithm_version','Versión identificable del algoritmo.',60),num('duration_ms','Duración medida.',null=True),txt('failure_code','Código saneado, sin stack trace.',80,True)],uq=[('request_id','generation')],ix=[('status','started_at')],stamp='created',rules=['Nunca afirmar resultado calculado solo por existir fila; completed exige candidatos/finalización coherentes.'])
T('matching_candidates','Pivot','B','Factores y posición de un técnico en una ejecución.',[f('matching_run_id','matching_runs'),f('technician_id','technician_profiles'),f('technician_service_id','technician_services'),b('eligible','Cumple filtros de la fotografía.'),txt('exclusion_code','Motivo de exclusión si aplica.',80,True),col('proximity_factor','DECIMAL(9,6)','Factor normalizado.',True,check='proximity_factor BETWEEN 0 AND 1'),col('price_factor','DECIMAL(9,6)','Factor normalizado.',True,check='price_factor BETWEEN 0 AND 1'),col('rating_factor','DECIMAL(9,6)','Factor real/neutro.',True,check='rating_factor BETWEEN 0 AND 1'),col('experience_factor','DECIMAL(9,6)','Factor normalizado.',True,check='experience_factor BETWEEN 0 AND 1'),col('score','DECIMAL(9,6)','Puntaje ponderado de 0 a 100.',True,check='score BETWEEN 0 AND 100'),num('rank_position','Posición positiva si elegible.',null=True),js('input_snapshot','Datos numéricos originales, distancia/estimación y procedencia; sin dirección privada.')],uq=[('matching_run_id','technician_id'),('matching_run_id','rank_position')],ix=[('matching_run_id','eligible','score')],stamp='created',rules=['Pivot enriquecida con identidad para ofertas. Servicio debe pertenecer a técnico y subcategoría de solicitud. Elegible exige factores/score/posición completos; excluido sin posición.','P15 define normalización y empate persistente; versión de algoritmo conserva criterio exacto aplicado.'])
T('offer_rounds','Dependiente','C','Ronda de invitaciones con versión de búsqueda y vencimiento.',[f('request_id','service_requests'),f('matching_run_id','matching_runs',null=True),num('round_no','Secuencia dentro de solicitud.'),num('generation','Generación vigente.'),e('kind',['automatic','direct','manual','additional'],'Origen de ronda.'),e('status',['open','awaiting_choice','closed','withdrawn'],'Estado de la ronda.','open'),tm('opened_at','Disponibilidad persistida de ofertas.'),tm('expires_at','Límite del SLA de respuesta.'),tm('closed_at','Cierre/retirada.',True),generated('active_request_id','BIGINT UNSIGNED',"CASE WHEN status IN ('open','awaiting_choice') AND kind <> 'additional' THEN request_id ELSE NULL END",'Una ronda principal activa por solicitud.')],uq=[('request_id','round_no'),('active_request_id',)],ix=[('status','expires_at')],checks=['expires_at > opened_at'],rules=['Automatic hasta 3 según versión; direct empieza con un solo técnico. Rondas del adicional necesitan resolver P13; no se confunden con reemplazo del principal.'])
T('offers','Dependiente','C','Invitación individual; aceptación no equivale a asignación.',[f('round_id','offer_rounds'),f('technician_id','technician_profiles'),f('matching_candidate_id','matching_candidates',null=True),f('service_rate_version_id','service_rate_versions',null=True),money('reference_fee_snapshot','Condición referencial notificada.'),col('currency','CHAR(3)','Moneda notificada.'),e('status',['pending','accepted','rejected','expired','withdrawn'],'Respuesta de candidato.','pending'),tm('available_at','Instante disponible en sistema.'),tm('expires_at','Límite persistido del SLA.'),tm('responded_at','Respuesta del técnico.',True),body('response_reason','Motivo opcional.',True),ver()],uq=[('round_id','technician_id')],ix=[('technician_id','status','expires_at'),('status','expires_at')],checks=['expires_at > available_at'],rules=['Candidato, técnico y solicitud deben coincidir; no repetir candidato prohibido por política de ronda (P12).','Toda aceptación revalida status, elegibilidad, generación y reloj del servidor bajo transacción. No usar índice para prometer SLA exacto del worker.'])
T('additional_technician_proposals','Dependiente','D','Propuesta de un único técnico adicional.',[f('request_id','service_requests'),f('proposed_by_participation_id','participations'),f('proposed_technician_id','technician_profiles'),body('reason','Motivo de incorporación.'),e('status',['pending_client','rejected','approved','awaiting_technician','accepted','withdrawn'],'Etapa de autorización.','pending_client'),f('client_decided_by','users',null=True),tm('client_decided_at','Decisión del titular.',True),f('offer_id','offers',null=True),generated('open_request_id','BIGINT UNSIGNED',"CASE WHEN status IN ('pending_client','approved','awaiting_technician') THEN request_id ELSE NULL END",'Una propuesta adicional abierta por solicitud.'),ver()],uq=[('open_request_id',)],rules=['Proponente es principal actual de la solicitud; cliente debe ser titular; destino no puede ser el mismo principal. Aceptación y relojes del adicional pendientes P13.'])
T('participations','Dependiente','D','Asignación/atención por técnico; permite principal y adicional, además de historial de sustituciones.',[f('request_id','service_requests'),f('technician_id','technician_profiles'),f('offer_id','offers'),e('slot',['primary','additional'],'Puesto en el servicio.'),e('status',['assigned','in_progress','completed','cancelled','replaced'],'Estado de atención.','assigned'),f('authorized_by','users'),tm('assigned_at','Asignación confirmada.'),tm('started_at','Inicio de atención.',True),tm('completed_at','Finalización individual.',True),tm('ended_at','Retirada o sustitución.',True),money('reference_fee_snapshot','Condición informada al asignar; no total pagado.'),col('currency','CHAR(3)','Moneda de condición.'),e('rating_status',['not_open','open','rated','unrated'],'Evaluación de esta participación.','not_open'),tm('rating_due_at','48 h desde finalización según versión.',True),f('replaces_id','participations',null=True),generated('occupied_slot','VARCHAR(32)',"CASE WHEN status NOT IN ('cancelled','replaced') THEN slot ELSE NULL END",'Puesto ocupado o completado; libera solo sustitución/cancelación.'),generated('current_technician_id','BIGINT UNSIGNED',"CASE WHEN status NOT IN ('cancelled','replaced') THEN technician_id ELSE NULL END",'Impide que el mismo técnico ocupe dos puestos actuales.'),ver()],uq=[('offer_id',),('request_id','occupied_slot'),('request_id','current_technician_id')],ix=[('technician_id','status','assigned_at'),('rating_status','rating_due_at')],checks=['completed_at IS NULL OR (started_at IS NOT NULL AND completed_at >= started_at)','rating_due_at IS NULL OR (completed_at IS NOT NULL AND rating_due_at > completed_at)'],rules=['Oferta aceptada, técnico y solicitud coincidentes. El cliente elige; aceptación no crea esta fila automáticamente.','Dos puestos máximos por solicitud, no dos filas históricas: sustituciones conservan filas previas. Estado global y técnico adicional pendientes P13.'])
T('appointments','Dependiente','D','Reserva concreta de agenda vinculada a participación.',[f('participation_id','participations'),f('technician_id','technician_profiles'),tm('starts_at','Inicio reservado UTC.'),tm('ends_at','Fin reservado UTC.'),e('status',['confirmed','completed','cancelled'],'Estado de reserva.','confirmed'),ver()],uq=[('participation_id',)],ix=[('technician_id','status','starts_at','ends_at')],checks=['ends_at > starts_at'],rules=['Técnico debe coincidir con participación. No solapar confirmadas: bloquear fila de technician_profiles en todas las operaciones de reserva y evaluar intervalos [inicio,fin).','Cambios actualizan esta reserva y conservan originales en reschedule_requests; duración P16.'])
T('reschedule_requests','Dependiente','D','Propuesta de nueva franja con copia de la anterior.',[f('appointment_id','appointments'),f('proposed_by','users'),tm('original_start_at','Inicio anterior.'),tm('original_end_at','Fin anterior.'),tm('proposed_start_at','Nuevo inicio.'),tm('proposed_end_at','Nuevo fin.'),body('reason','Motivo.'),e('status',['pending','accepted','rejected','expired','withdrawn'],'Decisión.','pending'),tm('expires_at','Ventana de 24 h.'),tm('resolved_at','Resolución.',True),generated('open_appointment_id','BIGINT UNSIGNED',"CASE WHEN status='pending' THEN appointment_id ELSE NULL END",'Una propuesta pendiente por cita.'),ver()],uq=[('open_appointment_id',)],ix=[('status','expires_at')],checks=['original_end_at > original_start_at','proposed_end_at > proposed_start_at'],rules=['Máximo de reprogramaciones y cita que ocurre antes de respuesta P06/P14. Actualizar cita solo al aceptar y tras revisar disponibilidad.'])
T('reschedule_responses','Pivot','D','Respuestas de las contrapartes requeridas para una reprogramación.',[f('reschedule_id','reschedule_requests'),f('user_id','users'),e('decision',['accept','reject'],'Decisión expresa.'),tm('responded_at','Momento de respuesta.')],identity=False,pk=['reschedule_id','user_id'],stamp=False,rules=['El proponente no responde por la contraparte. Participantes requeridos y coordinación con adicional P13; no basta cualquier usuario autenticado.'])
T('service_reports','Dependiente','D','Reporte de cierre de la atención de cada técnico.',[f('participation_id','participations'),f('author_id','users'),body('work_description','Trabajo efectuado.'),body('result_description','Resultado y limitaciones declaradas.'),tm('submitted_at','Registro del reporte.')],uq=[('participation_id',)],stamp='created',rules=['Autor es usuario del técnico asignado; reporte y finalización se registran juntos. No reutilizar reporte para otro técnico.'])
T('service_report_evidence','Pivot','D','Galería privada de evidencias de la atención.',[f('report_id','service_reports'),f('media_id','media_files'),num('position','Orden.','0'),txt('caption','Pie de evidencia.',180,True)],identity=False,pk=['report_id','media_id'],uq=[('report_id','position')],stamp='created',rules=['Archivo privado del autor permitido; cliente titular y administrador autorizado pueden consultarlo.'])
T('incidents','Dependiente','D/F','Inasistencia, cancelación técnica u otro problema de servicio.',[f('request_id','service_requests'),f('participation_id','participations',null=True),f('reported_by','users'),txt('type','Código permitido: no_show, technician_withdrawal, service_problem.',60),body('description','Relato de incidencia.'),e('status',['open','under_review','resolved','dismissed'],'Gestión de incidencia.','open'),f('reviewed_by','users',null=True),body('resolution','Intervención motivada.',True),tm('resolved_at','Fecha de cierre.',True),ver()],ix=[('request_id','created_at'),('status','created_at')],rules=['Una denuncia no cambia automáticamente verificación o asignación; administración revisa antes de intervenir.'])
T('incident_evidence','Pivot','D/F','Archivos de respaldo de incidencia.',[f('incident_id','incidents'),f('media_id','media_files')],identity=False,pk=['incident_id','media_id'],stamp='created',rules=['Validar propietario, relación de usuario y finalidad privada.'])
T('reassignment_records','Dependiente','C/F','Trazabilidad de reasignación automática o administrativa.',[f('request_id','service_requests'),f('previous_participation_id','participations',null=True),f('new_participation_id','participations',null=True),f('target_technician_id','technician_profiles',null=True),f('actor_id','users',null=True),e('origin',['automatic','manual'],'Quién la inicia.'),body('reason','Motivo explícito.'),f('incident_id','incidents',null=True),f('new_round_id','offer_rounds',null=True),e('status',['awaiting_response','awaiting_choice','assigned','failed','cancelled'],'Resultado.','awaiting_response'),tm('resolved_at','Cierre del intento.',True),ver()],ix=[('request_id','created_at'),('origin','created_at')],rules=['Manual exige actor con permiso; automática identifica job en auditoría. Todas las participaciones/rondas deben pertenecer a request_id.','No forzar consentimiento salvo excepción aprobada P11/P14. Insertar auditoría y cambiar generación de búsqueda atómicamente.'])

# Calificaciones y reputación.
T('ratings','Dependiente','E','Reseña y puntaje canónicos actuales de una participación.',[f('participation_id','participations'),f('author_id','users'),col('score','TINYINT UNSIGNED','Puntaje vigente.',check='score BETWEEN 1 AND 5'),body('comment','Comentario vigente del cliente.'),num('current_version_no','Versión vigente.','1'),e('status',['active','annulled'],'Vigencia de evaluación.','active'),tm('first_rated_at','Instante original de calificación.'),tm('editable_until','Límite persistido de edición; propuesta primera fecha + 48 h.'),ver()],uq=[('participation_id',)],ix=[('author_id','first_rated_at')],checks=['editable_until > first_rated_at'],rules=['Author es cliente titular; participación finalizada dentro de ventana. Score/comentario actuales son proyección de versión, actualizados con rating_versions en una transacción.','No crear reseña ficticia de cero para sin calificar. La nota de técnicos se deriva de reseñas válidas; neutralidad de matching no es una reseña.'])
T('rating_versions','Dependiente','E','Contenido histórico inmutable de cada versión de reseña.',[f('rating_id','ratings'),num('version_no','Secuencia por reseña.'),col('score','TINYINT UNSIGNED','Puntaje de la versión.',check='score BETWEEN 1 AND 5'),body('comment','Comentario de la versión.'),f('changed_by','users'),e('change_kind',['initial','client_edit','admin_adjust','admin_annul'],'Origen de versión.'),body('reason','Obligatorio para intervención administrativa.',True),tm('changed_at','Instante de modificación.')],uq=[('rating_id','version_no')],ix=[('rating_id','changed_at')],stamp='created',rules=['Append-only; current_version_no de ratings es referencia lógica al par rating_id/version_no, validada en la transacción para evitar FK circular obligatoria al primer insert.'])
T('rating_replies','Dependiente','E','Respuesta identificada del técnico a una reseña.',[f('rating_id','ratings'),f('author_id','users'),body('text','Respuesta del prestador, no modifica puntaje.'),e('status',['published','hidden'],'Visibilidad por moderación.','published'),ver()],uq=[('rating_id',)],rules=['Propuesta una respuesta vigente por reseña; cambios auditados; confirmar extensión/edición P17. Solo técnico de participación.'])
T('rating_appeals','Dependiente','E','Solicitud de revisión de una calificación.',[f('rating_id','ratings'),f('submitted_by','users'),f('submitted_version_id','rating_versions'),body('reason','Motivo de apelación.'),e('status',['open','under_review','resolved','withdrawn'],'Estado.','open'),tm('submitted_at','Recepción de apelación.'),tm('appeal_deadline_at','Plazo aplicado si se acuerda, no asumir cinco días.',True),generated('open_rating_id','BIGINT UNSIGNED',"CASE WHEN status IN ('open','under_review') THEN rating_id ELSE NULL END",'Propuesta una apelación abierta por reseña.'),ver()],uq=[('open_rating_id',)],ix=[('status','submitted_at')],rules=['Técnico evaluado; versión inicial pertenece a reseña. Al resolver se revisa versión vigente, no necesariamente la presentada. Plazo/calendario/nuevas apelaciones P07.'])
T('appeal_evidence','Pivot','E','Archivos privados para sustentar una apelación.',[f('appeal_id','rating_appeals'),f('media_id','media_files')],identity=False,pk=['appeal_id','media_id'],stamp='created',rules=['Propietario vinculado a apelación; solo partes autorizadas/administración, no galería pública.'])
T('rating_resolutions','Dependiente','E/F','Resolución administrativa de apelación.',[f('appeal_id','rating_appeals'),f('reviewed_version_id','rating_versions'),f('resolved_by','users'),e('decision',['maintain','adjust','annul'],'Resultado.'),body('reason','Justificación obligatoria.'),f('result_version_id','rating_versions',null=True),tm('resolved_at','Instante de decisión.')],uq=[('appeal_id',)],stamp='created',rules=['Todas las versiones son de la reseña apelada. Ajustar/anular crea versión resultante; mantener puede dejar result_version_id NULL.','Bloquear reseña y apelación, validar versión actual, registrar auditoría y recalcular reputación; no resolver sobre una pantalla obsoleta.'])

# Notificaciones y comunicados.
T('notifications','Polimórfica','F/C','Bandeja persistida por usuario, con referencia a distintos recursos del dominio.',[col('event_uuid','CHAR(36)','ID estable del evento lógico.'),f('recipient_id','users'),txt('event_type','Tipo conocido de notificación.',80),txt('subject_type','Alias de morph map, nunca nombre de clase recibido del cliente.',40),col('subject_id','BIGINT UNSIGNED','ID de request, offer, participation, rating, appeal, announcement o support_ticket.'),txt('title','Título mínimo sin datos privados.',160),js('data','Payload mínimo: ID, versión y deadline; no dirección/documentos.'),tm('read_at','Primera lectura reconocida.',True),tm('withdrawn_at','Retirada por invalidación del evento.',True)],uq=[('event_uuid','recipient_id')],ix=[('recipient_id','read_at','created_at'),('subject_type','subject_id')],rules=['Relación recipient sí tiene FK; subject_type/subject_id es polimórfica, sin FK nativa: validar morph map y pertenencia.','Esquema propio con ID bigint; requiere modelo/canal de persistencia adaptado, no asumir estructura estándar UUID/notifiable de Laravel. Una única bandeja puede tener intentos por múltiples canales.'])
T('notification_attempts','Dependiente','F/C','Intentos de entrega por canal, independientes de lectura.',[f('notification_id','notifications'),e('channel',['in_app','email','push'],'Canal de entrega.'),col('attempt_no','TINYINT UNSIGNED','1 inicial; hasta 3 reintentos propuestos.',check='attempt_no BETWEEN 1 AND 4'),e('status',['queued','delivered','failed','skipped'],'Resultado del intento.','queued'),tm('scheduled_at','Momento previsto.'),tm('attempted_at','Ejecución real.',True),txt('failure_code','Error saneado.',80,True),txt('provider_reference','Referencia de sandbox si existe.',160,True)],uq=[('notification_id','channel','attempt_no')],ix=[('status','scheduled_at')],rules=['Número máximo interpreta RNF-07 como tres reintentos además del inicial, sujeto a P12. No reenviar ofertas retiradas/vencidas. delivered no significa read.'])
T('notification_preferences','Pivot','F','Preferencias por usuario, canal y tipo de evento.',[f('user_id','users'),e('channel',['in_app','email','push'],'Canal.'),txt('topic','Tipo de evento o all.',80),b('enabled','Preferencia elegida.',1)],identity=False,pk=['user_id','channel','topic'],rules=['Falta de fila usa política del sistema; prioridades y avisos obligatorios P12. Preferencia no permite acceso a otro usuario.'])
T('announcements','Dependiente','F','Comunicados con imagen y vigencia.',[txt('title','Título del comunicado.',160),body('body','Contenido como texto escapado.'),f('image_id','media_files',null=True),txt('link_url','URL http/https permitida.',2048,True),txt('link_label','Etiqueta del enlace.',80,True),e('status',['draft','published','retired'],'Estado.','draft'),tm('starts_at','Inicio de publicación, NULL en borrador.',True),col('duration_days','SMALLINT UNSIGNED','Vigencia en días.',default='1',check='duration_days > 0'),generated('ends_at','DATETIME(6)','DATE_ADD(starts_at, INTERVAL duration_days DAY)','Fin de vigencia derivado, no editable.'),num('priority','Orden de presentación.','0'),f('created_by','users'),f('updated_by','users'),tm('retired_at','Retiro lógico.',True),ver()],ix=[('status','starts_at','ends_at')],rules=['Publicado exige starts_at y audiencia. Eliminar desde interfaz equivale a retirar; auditar y conservar según retención.','Duplicar crea borrador con nueva identidad; no copiar lectura ni publicación efectiva.'])
T('announcement_audiences','Pivot','F','Roles destinatarios de un comunicado.',[f('announcement_id','announcements'),f('role_id','roles')],identity=False,pk=['announcement_id','role_id'],stamp='created',rules=['Ambos se representa con client y technician; no texto ambiguo all sin evaluación por rol. Cambio de audiencia surte efecto en lectura y envío.'])

# Registro de método y pagos de demostración, sin pasarela.
T('payment_methods','Independiente','F','Catálogo de métodos declarables; no credenciales financieras.',[txt('code','Código de método.',40),txt('name','Nombre visible.',100),b('active','Seleccionable.',1),num('display_order','Orden.','0')],uq=[('code',)],privacy='Catálogo público/usuario; lista definitiva P16.')
T('user_payment_methods','Pivot','F','Métodos favoritos del cliente, no instrumentos bancarios.',[f('user_id','users'),f('payment_method_id','payment_methods'),txt('label','Apodo sin números de cuenta o tarjeta.',80,True),b('is_default','Preferencia predeterminada.'),generated('default_user_id','BIGINT UNSIGNED','CASE WHEN is_default=1 THEN user_id ELSE NULL END','Solo un favorito predeterminado por usuario.')],identity=False,pk=['user_id','payment_method_id'],uq=[('default_user_id',)],rules=['User debe ser cliente. No PAN, CVV, token de pasarela, cuenta bancaria o saldo.'])
T('request_payment_methods','Dependiente','F','Método seleccionado para una solicitud.',[f('request_id','service_requests'),f('payment_method_id','payment_methods'),f('selected_by','users'),tm('selected_at','Fecha de selección.'),ver()],uq=[('request_id',)],rules=['Titular de solicitud; cambios auditados si el servicio ya fue asignado. No implica pago.'])
T('simulated_payments','Dependiente','F','Registro de pago ficticio solicitado expresamente para la demostración.',[f('participation_id','participations'),f('payment_method_id','payment_methods'),f('created_by','users'),money('amount','Monto sintético; nunca verificado por entidad financiera.'),col('currency','CHAR(3)','Moneda propuesta PEN, P01.',default="'PEN'"),e('status',['simulated_pending','simulated_declared','simulated_confirmed','simulated_void'],'Estado exclusivamente simulado.','simulated_pending'),b('is_simulated','Marcador obligatorio de simulación.',1),txt('simulation_reference','Referencia ficticia única.',80),f('confirmed_by','users',null=True),tm('confirmed_at','Confirmación de prueba, no confirmación bancaria.',True),tm('confirmation_due_at','Plazo si se ratifica flujo de declaración de R13.',True),ver()],uq=[('simulation_reference',)],ix=[('participation_id','created_at'),('status','created_at')],checks=['is_simulated = 1'],rules=['Nueva petición autoriza modelar pagos simulados; no habilita pagos reales ni confirma todas las reglas pendientes P02.','Roles que crean/confirman, monto final y plazo de confirmación requieren ratificación. La participación identifica cliente/técnico sin duplicarlos. Registros no suman ingresos verificados.','Usar datos sintéticos; no introducir proveedor, webhook, tarjeta ni reembolso financiero.'])
T('simulated_payment_events','Dependiente','F','Historia inmutable de cambios de un pago simulado.',[f('simulated_payment_id','simulated_payments'),f('actor_id','users'),txt('from_status','Estado anterior.',32,True),txt('to_status','Estado nuevo simulado.',32),body('reason','Motivo.'),tm('occurred_at','Momento UTC.')],ix=[('simulated_payment_id','occurred_at')],stamp=False,rules=['Transición permitida y evento en misma transacción. No permite convertir is_simulated a false.'])
T('simulated_receipts','Dependiente','F','Constancia de demostración sin validez tributaria ni prueba de cobro.',[f('simulated_payment_id','simulated_payments'),f('media_id','media_files'),txt('reference','Código propio de constancia ficticia.',80),tm('issued_at','Generación del documento.'),b('is_simulated','Siempre 1.',1),js('snapshot','Monto, moneda, estado y referencias sintéticas usados al emitir.')],uq=[('reference',),('media_id',)],checks=['is_simulated = 1'],stamp='created',rules=['PDF privado rotulado SIMULADO / SIN VALIDEZ TRIBUTARIA; no llamar factura. Múltiples emisiones conservan referencias/versiones y no duplican pagos.'])

# Soporte, auditoría y operación.
T('support_tickets','Dependiente','F','Bandeja de ayuda e incidencias de usuario; sin chat integrado.',[f('opened_by','users'),f('request_id','service_requests',null=True),txt('subject','Asunto.',180),body('description','Detalle privado.'),e('status',['open','in_progress','resolved','closed'],'Estado del ticket.','open'),e('priority',['low','normal','high'],'Prioridad administrativa.','normal'),f('assigned_admin_id','users',null=True),tm('resolved_at','Resolución.',True),tm('closed_at','Cierre.',True),ver()],ix=[('opened_by','created_at'),('assigned_admin_id','status'),('status','created_at')],rules=['Usuario tiene relación con solicitud vinculada; admin de soporte debe tener permiso. No crear conversaciones de chat por esta tabla.'])
T('support_ticket_updates','Dependiente','F','Seguimiento y resolución del ticket.',[f('ticket_id','support_tickets'),f('author_id','users'),e('kind',['note','status_change','resolution'],'Tipo de intervención.'),body('body','Nota o resolución.'),b('is_internal','Oculta a solicitante si nota administrativa.',1),txt('new_status','Estado resultante si cambia.',32,True)],ix=[('ticket_id','created_at')],stamp='created',rules=['El usuario no puede crear notas internas como admin. Las respuestas visibles se consultan en detalle; no chat libre en tiempo real.'])
T('support_attachments','Pivot','F','Evidencias adjuntas al ticket.',[f('ticket_id','support_tickets'),f('media_id','media_files'),f('uploaded_by','users')],identity=False,pk=['ticket_id','media_id'],stamp='created',rules=['Archivo privado del solicitante o administrador autorizado.'])
T('audit_entries','Polimórfica','F','Registro append-only de acciones sensibles sobre recursos heterogéneos.',[f('actor_id','users',null=True),e('actor_kind',['user','system'],'Tipo de ejecutor.'),txt('action','Código de acción sensible.',100),txt('permission_used','Permiso comprobado.',100,True),txt('subject_type','Alias de entidad auditada, no clase arbitraria.',60),col('subject_id','BIGINT UNSIGNED','Identificador del objeto; sin FK polimórfica.',True),body('reason','Motivo de acción o denegación.'),js('before_values','Campos anteriores mínimos y redactados.',True),js('after_values','Campos posteriores mínimos y redactados.',True),txt('correlation_id','Petición/job/evento que originó la acción.',64),tm('occurred_at','Momento de decisión.'),txt('source_code','Job o componente, sin secretos.',100,True)],ix=[('subject_type','subject_id','occurred_at'),('actor_id','occurred_at'),('action','occurred_at'),('correlation_id',)],stamp=False,rules=['No UPDATE/DELETE para cuenta de aplicación; cuenta de migración separada. Esto no asegura inmutabilidad ante DBA.','Registro y cambio sensible en una transacción; si falla auditoría, rollback. No contraseñas, cookies, tokens, documentos ni direcciones completas.','subject_id NULL solo si no existe recurso materializado (intento denegado); conservación de polimorfismo controlada por aplicación.'])
T('operations','Dependiente','F','Trabajos largos consultables, como exportaciones.',[f('requested_by','users'),txt('type','Tipo permitido de operación.',60),e('status',['pending','running','completed','failed'],'Progreso.','pending'),js('parameters','Filtros validados, sin SQL arbitrario.'),tm('started_at','Inicio.',True),tm('finished_at','Fin.',True),txt('failure_code','Error saneado.',80,True),ver()],ix=[('requested_by','created_at'),('status','created_at')],rules=['Autorización al crear, consultar y descargar; no basta conocer el ID.'])
T('export_files','Dependiente','F','Resultado privado de un reporte.',[f('operation_id','operations'),f('media_id','media_files'),e('format',['pdf','xlsx'],'Formato.'),tm('expires_at','Retención operativa de descarga.')],uq=[('operation_id',),('media_id',)],ix=[('expires_at',)],stamp='created',rules=['Expiración no elimina evidencia auditada del reporte. Política de limpieza operativa a definir, P08.'])
T('outbox_events','Polimórfica','F/transversal','Eventos duraderos confirmados con el negocio, pendientes de publicación.',[col('event_uuid','CHAR(36)','Identidad estable para deduplicación.'),txt('event_type','Evento permitido.',100),txt('aggregate_type','Alias de recurso.',60),col('aggregate_id','BIGINT UNSIGNED','ID del recurso origen; no FK polimórfica.'),num('aggregate_version','Versión resultante.'),num('schema_version','Versión del contrato de evento.','1'),js('payload','Mensaje mínimo con IDs/plazos; sin datos sensibles.'),tm('occurred_at','Momento del cambio.'),tm('available_at','Inicio previsto de publicación.'),e('status',['pending','processing','published','failed'],'Estado de distribución.','pending'),tm('published_at','Cuando se procesaron entregas requeridas.',True),num('attempts','Intentos técnicos.','0')],uq=[('event_uuid',)],ix=[('status','available_at'),('aggregate_type','aggregate_id','aggregate_version')],stamp=False,rules=['Insertar en la misma transacción del cambio. La entrega es al menos una vez; consumidores deduplican y refrescan por API. No confundir publicado con leído.'])
T('outbox_deliveries','Pivot','F','Control por evento y destinatario para publicación privada.',[f('outbox_event_id','outbox_events'),f('recipient_id','users'),e('status',['pending','sent','failed','skipped'],'Resultado.','pending'),num('attempts','Intentos.','0'),tm('next_attempt_at','Próximo intento.',True),tm('sent_at','Publicación.',True),txt('failure_code','Fallo saneado.',80,True)],identity=False,pk=['outbox_event_id','recipient_id'],ix=[('status','next_attempt_at')],rules=['Resolver auth_version y permisos del destinatario en el momento de publicar; invalidaciones solo contienen referencias mínimas.'])
T('idempotency_records','Dependiente','F/transversal','Evita duplicación de comandos por reintento.',[f('user_id','users'),txt('operation','Nombre canónico de operación incluyendo recurso, no texto libre.',160),col('key_hash','CHAR(64)','Hash SHA-256 de Idempotency-Key.'),col('request_hash','CHAR(64)','Hash canónico del cuerpo.'),e('status',['processing','completed'],'Estado de resultado.','processing'),col('response_status','SMALLINT UNSIGNED','HTTP del resultado.',True),js('response_body','Resultado mínimo; no direcciones/tokens.',True),tm('expires_at','Fin de retención técnica; siete días propuestos en diseño.')],uq=[('user_id','operation','key_hash')],ix=[('expires_at',)],rules=['Misma clave con cuerpo distinto: 409. Cambio de negocio y respuesta completada se confirman juntos; revalidar permiso antes de devolver resultado guardado.'])

# Tablas técnicas del framework: excepciones explícitas a IDs/fechas del dominio.
T('sessions','Dependiente','Infraestructura','Sesiones de Laravel para la SPA.',[col('id','VARCHAR(255)','Identificador opaco de sesión.'),f('user_id','users',null=True),txt('ip_address','Dirección IP bajo política de privacidad.',45,True),body('user_agent','Agente del navegador.',True),col('payload','LONGTEXT','Contenido serializado del driver de sesión, acceso restringido.'),col('last_activity','INT','Epoch segundos usado por Laravel.')],identity=False,pk=['id'],stamp=False,ix=[('last_activity',)],rules=['No usar esta tabla como token Bearer. user_id puede ser NULL antes de autenticación. Alinear migración con versión Laravel fijada.'],privacy='Acceso exclusivo al servidor; no exportar payload.')
T('password_reset_tokens','Dependiente','Infraestructura','Tokens temporales de recuperación; identidad lógica por correo.',[col('email','VARCHAR(254)','Correo del usuario; vínculo lógico con users.email, sin FK para respetar driver.'),txt('token','Hash del token; nunca token original.'),tm('created_at','Emisión; driver puede dejar NULL, debe invalidarse en ese caso.',True)],identity=False,pk=['email'],stamp=False,rules=['Dependencia lógica sin FK nativa. Expiración por configuración; limpiar al cambiar correo y al consumir. No responder si el correo existe.'],privacy='Solo servidor; entrega en sandbox.')
T('jobs','Independiente','Infraestructura','Cola de trabajos Laravel persistida en MySQL.',[txt('queue','Nombre de cola.',255),col('payload','LONGTEXT','Contrato serializado con IDs, no copias de documentos.'),col('attempts','TINYINT UNSIGNED','Número de reservas/ejecuciones.'),col('reserved_at','INT UNSIGNED','Epoch segundos de reserva.',True),col('available_at','INT UNSIGNED','Epoch segundos a partir del cual se procesa.'),col('created_at','INT UNSIGNED','Epoch segundos de encolado.')],stamp=False,ix=[('queue',)],rules=['Contrato técnico del driver; verificar versión. No poner FK de payload; cada job relee dominio. Independiente físicamente, no fuente del estado del servicio.'],privacy='Servidor; puede contener metadatos internos.')
T('failed_jobs','Independiente','Infraestructura','Errores de trabajos conservados para diagnóstico.',[col('uuid','VARCHAR(255)','Identidad del job.'),body('connection','Conexión usada.'),body('queue','Cola.'),col('payload','LONGTEXT','Payload fallido; minimizar datos sensibles.'),col('exception','LONGTEXT','Error saneado, acceso restringido.'),col('failed_at','DATETIME(6)','Fecha UTC de fallo.',default='CURRENT_TIMESTAMP(6)')],uq=[('uuid',)],stamp=False,rules=['No es prueba de fallo definitivo del negocio. Reintentar debe ser seguro por idempotencia; conservación técnica definida aparte de registros de servicio.'])
T('cache','Independiente','Infraestructura','Caché de base de datos Laravel; datos reconstruibles.',[col('key','VARCHAR(255)','Clave de caché.'),col('value','MEDIUMTEXT','Valor serializado.'),col('expiration','INT','Epoch segundos de expiración.')],identity=False,pk=['key'],stamp=False,ix=[('expiration',)],rules=['No usar como autoridad de asignación, permisos persistentes o SLA. Borrarla no borra hechos del negocio.'])
T('cache_locks','Independiente','Infraestructura','Bloqueos temporales del driver de caché.',[col('key','VARCHAR(255)','Nombre del bloqueo.'),txt('owner','Propietario temporal.',255),col('expiration','INT','Epoch segundos de fin.')],identity=False,pk=['key'],stamp=False,ix=[('expiration',)],rules=['Evita scheduler solapado; no sustituye transacciones/bloqueos de filas del dominio.'])
T('migrations','Independiente','Infraestructura','Registro del esquema aplicado por Laravel.',[col('id','INT UNSIGNED','Identificador técnico.',default='AUTO_INCREMENT'),txt('migration','Nombre del archivo.',255),col('batch','INT','Lote de ejecución.')],identity=False,pk=['id'],stamp=False,rules=['Generada por framework. El DDL documental no inserta filas que simulen migraciones ejecutadas.'])

HEADER='''# CANVAS | Diccionario de datos de TécnicoYa Huancayo

**Versión:** 1.0 · **Fecha:** 4 de octubre de 2026 · **Motor objetivo:** MySQL 8.4 / InnoDB, propuesta de referencia compatible con la arquitectura solicitada.

**Estado:** diseño físico propuesto; no refleja automáticamente las tablas actuales ni acredita una migración ejecutada. Los tipos y longitudes son decisiones de diseño revisables. Se entrega un DDL de referencia para revisión, no un script autorizado para ejecutar sobre la base del proyecto.

## 1. Fuentes, precedencia y alcance

Base vigente: Fuente 0; CANVAS de análisis; CANVAS de Diseño Técnico; Resumen Ejecutivo del MVP y última petición que incorpora expresamente registros de pago simulados. Se contrastaron los antecedentes de la colección de 17 documentos v2, sus fuentes editables, el diccionario físico anterior y los apartados de datos/arquitectura del informe final. Las propuestas anteriores de chat, LLM, pagos reales, PostgreSQL/FastAPI y Bearer propios no sustituyen el alcance y stack confirmados posteriormente.

El modelo incluye tablas de negocio y soporte de ejecución. No exige construirlas todas en una primera iteración: se implementan con las historias correspondientes. Las tablas técnicas del framework se revisan con la versión fijada antes de generar migraciones. No se agregan multitenencia empresarial, pasarelas, suscripciones ni reembolsos reales.

**Cambios explícitos frente a antecedentes:** catálogo normalizado en lugar de listas JSON; tarifa por técnico/subcategoría; oferta distinta de asignación; hasta dos puestos con historial de sustituciones; calificación por atención con versiones; notificaciones persistidas; sesión de SPA; pagos únicamente simulados. El diccionario amplía el detalle de Diseño Técnico sin modificar su archivo ni resolver silenciosamente P01–P23.

## 2. Convenciones y clasificación

| Elemento | Regla |
|---|---|
| Independiente | Catálogo/registro autónomo; puede tener referencias auxiliares opcionales sin depender del ciclo de otro registro. |
| Dependiente | Pertenece al ciclo de vida de otra entidad; tiene FK o dependencia lógica expresamente indicada. |
| Pivot | Asociación M:N; puede contener atributos y PK sustituta cuando necesita historial/referencias. |
| Polimórfica | Un par tipo/ID apunta a varias entidades. MySQL no puede imponer una única FK para ese par; se valida un mapa cerrado de tipos en aplicación. |
| Motor y texto | InnoDB, utf8mb4, collation propuesta utf8mb4_0900_as_cs. Correos/códigos se normalizan; las comparaciones técnicas no dependen de mayúsculas accidentales. |
| IDs | BIGINT UNSIGNED AUTO_INCREMENT salvo pivots compuestas/tablas framework. En JSON se exponen como cadena. |
| Fechas de dominio | DATETIME(6), UTC; interfaz America/Lima. created_at/updated_at detallados en cada tabla; actualización de updated_at a cargo de aplicación. |
| Fechas del driver | Epoch en segundos solo en jobs, cache, cache_locks y last_activity de sessions; no mezclar con milisegundos. |
| Importes | DECIMAL(12,2), no FLOAT. PEN es propuesta pendiente P01; no conversión de moneda. |
| Nulabilidad/default | Sí permite NULL; — significa sin default y el servidor debe suministrar valor. Generadas no admiten escritura directa. |
| Claves e índices | PK, UNIQUE (UQ), FK y BTREE no único (IX). Índices de FK se materializan si no existe prefijo adecuado. No duplicar automáticamente un índice ya cubierto. |
| Acciones referenciales | Toda FK física usa ON DELETE RESTRICT y ON UPDATE RESTRICT. Preservar IDs y anonimizar donde se autorice; limpieza de hijos en orden explícito. No borrar historia por cascada. |
| Retención | Datos personales y registros sujetos a P08; no se adopta automáticamente el plazo propuesto de 12 meses. Jobs/caché/sesiones tienen limpieza operativa separada. |
| Seguridad | Claves, índices e IDs no sustituyen Policies. Datos privados requieren rol, pertenencia, estado y momento del servicio. |

MySQL permite CHECK de fila y relaciones FK con condiciones de tipos/índices; no usar CHECK para consultar otra tabla, evaluar permisos o comparar continuamente con el reloj. Referencias: [CHECK](https://dev.mysql.com/doc/refman/8.4/en/create-table-check-constraints.html), [FK](https://dev.mysql.com/doc/refman/8.4/en/create-table-foreign-keys.html). Las columnas generadas y su unicidad condicionada se apoyan en [índices de columnas generadas](https://dev.mysql.com/doc/refman/8.4/en/create-table-secondary-indexes.html). Su expresión depende del estado persistido, nunca de NOW().

> **Guía:** una FK comprueba que el registro referido existe. No comprueba que ese técnico pertenezca a la solicitud correcta ni que el usuario tenga permiso: esas reglas se validan en una transacción.

## 3. Inventario y navegación

'''

def q(s):return '`'+s+'`'
def name(prefix,*parts):
    s=prefix+'_'+'_'.join(parts)
    return s if len(s)<=60 else s[:49]+'_'+hashlib.sha1(s.encode()).hexdigest()[:10]
def esc(s):return str(s).replace('|','\\|').replace('\n',' ')

def generate():
    by={t['name']:t for t in tables}
    assert len(by)==len(tables)
    for t in tables:
        cols={c['name']:c for c in t['columns']}
        assert len(cols)==len(t['columns']),t['name']
        for group in [t['primary_key']]+t['unique']+t['indexes']:
            assert group and set(group)<=set(cols),(t['name'],group)
        for key in t['primary_key']:assert not cols[key]['nullable']
        for c in t['columns']:
            if c['reference']:
                tn,cn=c['reference'].split('.')
                assert tn in by,(t['name'],tn)
                target=next(x for x in by[tn]['columns'] if x['name']==cn)
                assert target['type']==c['type'],(t['name'],c['name'],'FK TYPE')
                assert [cn] in [by[tn]['primary_key']]+by[tn]['unique']
                groups=[t['primary_key']]+t['unique']+t['indexes']
                if not any(g[0]==c['name'] for g in groups):t['indexes'].append([c['name']])
    stats=f"**Modelo:** {len(tables)} tablas físicas, {sum(len(t['columns']) for t in tables)} atributos y {sum(bool(c['reference']) for t in tables for c in t['columns'])} FK físicas. Incluye 7 tablas del framework y una vista de historial descrita en §7. No son 79 funcionalidades: las asociaciones, versiones y registros técnicos se separan para preservar integridad e historia."
    md=[HEADER,stats,'','| Tabla | Clase | Módulo | Propósito |','|---|---|---|---|']
    for i,t in enumerate(tables,1):md.append(f"| [{t['name']}](#t{i:02}) | {t['classification']} | {t['module']} | {esc(t['description'])} |")
    md.append('\n## 4. Definiciones completas\n')
    sql=['-- TécnicoYa Huancayo: MySQL 8.4 / InnoDB. DISEÑO PROPUESTO, NO EJECUTADO.', '-- No ejecutar en una base existente. Revisar pendientes del documento y generar migraciones.', '-- Sin CREATE DATABASE, USE, DROP, datos personales ni credenciales.', "SET NAMES utf8mb4 COLLATE utf8mb4_0900_as_cs;", "SET time_zone = '+00:00';",'']
    fk_sql=[];seen_names=set()
    for i,t in enumerate(tables,1):
        tn=t['name'];md += [f'<a id="t{i:02}"></a>',f"### T{i:02}. `{tn}`",f"**Clase:** {t['classification']} · **Módulo:** {t['module']}",t['description'],f"**Visibilidad:** {t['privacy']}",'','| Atributo | Tipo MySQL | NULL | Default / generación | Clave | Descripción |','|---|---|---|---|---|---|']
        defs=[]
        for c in t['columns']:
            cn=c['name'];keys=[]
            if cn in t['primary_key']:keys.append('PK')
            if any(cn in u for u in t['unique']):keys.append('UQ (ver grupo)')
            if c['reference']:keys.append('FK → '+c['reference'])
            default='GENERATED: '+c['generated'] if c['generated'] else (c['default'] if c['default'] is not None else '—')
            md.append('| '+ ' | '.join([f'`{cn}`',f"`{c['type']}`",'Sí' if c['nullable'] else 'No',esc(default),esc('; '.join(keys) or '—'),esc(c['description'])])+' |')
            d=q(cn)+' '+c['type']
            if c['generated']:d+=' GENERATED ALWAYS AS ('+c['generated']+') STORED'
            else:
                d+= ' NULL' if c['nullable'] else ' NOT NULL'
                if c['default']=='AUTO_INCREMENT':d+=' AUTO_INCREMENT'
                elif c['default'] is not None:d+=' DEFAULT '+c['default']
            defs.append(d)
            if c['reference']:
                dest,dc=c['reference'].split('.');n=name('fk',tn,cn)
                assert n not in seen_names;seen_names.add(n)
                fk_sql.append(f'ALTER TABLE {q(tn)} ADD CONSTRAINT {q(n)} FOREIGN KEY ({q(cn)}) REFERENCES {q(dest)} ({q(dc)}) ON DELETE RESTRICT ON UPDATE RESTRICT;')
        defs.append('PRIMARY KEY ('+', '.join(map(q,t['primary_key']))+')')
        md += ['', '**Claves, relaciones e índices:**', '- PK: `('+', '.join(t['primary_key'])+')`.']
        for u in t['unique']:
            n=name('uq',tn,*u);defs.append('UNIQUE KEY '+q(n)+' ('+', '.join(map(q,u))+')');md.append('- UNIQUE `'+n+'`: `('+', '.join(u)+')`.')
        for idx in t['indexes']:
            n=name('ix',tn,*idx);defs.append('KEY '+q(n)+' ('+', '.join(map(q,idx))+')');md.append('- IX `'+n+'`: `('+', '.join(idx)+')`.')
        fks=[c for c in t['columns'] if c['reference']]
        if not fks:md.append('- FK físicas: ninguna; revisar dependencias lógicas indicadas.')
        for c in fks:md.append(f"- FK `{c['name']}` → `{c['reference']}`; N:1, opcional={'sí' if c['nullable'] else 'no'}; DELETE/UPDATE RESTRICT. La UQ correspondiente convierte en 1:1 cuando aplique.")
        checks=[c['check'] for c in t['columns'] if c['check']]+t['checks']
        md+=['','**Restricciones de base de datos:**']
        if not checks:md.append('- PK/FK, nulabilidad, tipos y unicidad definidos arriba; no hay CHECK adicional.')
        for k,chk in enumerate(checks,1):
            n=name('ck',tn,str(k));assert n not in seen_names;seen_names.add(n)
            defs.append('CONSTRAINT '+q(n)+' CHECK ('+chk+')');md.append('- `'+n+'`: `'+esc(chk)+'`.')
        md+=['','**Reglas de aplicación / transacción:**']+[('- '+r) for r in (t['application_rules'] or ['Validar rol, propietario, contenido y consistencia con el recurso asociado; no exponer escrituras genéricas de estado.'])]+['']
        sql += [f'-- {t["classification"]} / {t["module"]}: {t["description"]}',f'CREATE TABLE {q(tn)} (\n  '+',\n  '.join(defs)+'\n) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_as_cs;','']
    sql+=['-- FK añadidas al final para resolver dependencias circulares del DDL. No elimina la necesidad de ordenar INSERT.']+fk_sql
    sql += ['', '-- Vista dependiente de consulta. La API debe filtrar por rol y pertenencia.', '''CREATE SQL SECURITY INVOKER VIEW `v_service_history` AS
SELECT r.id AS request_id, r.client_id, r.subcategory_id, r.district_id,
       r.status AS request_status, r.submitted_at,
       p.id AS participation_id, p.technician_id, p.slot,
       p.status AS participation_status, p.assigned_at, p.completed_at,
       CASE WHEN p.id IS NULL THEN r.reference_fee_snapshot ELSE p.reference_fee_snapshot END AS reference_fee,
       CASE WHEN p.id IS NULL THEN r.currency ELSE p.currency END AS currency,
       rt.id AS rating_id,
       CASE WHEN rt.status = 'active' THEN rt.score ELSE NULL END AS rating_score,
       rt.status AS rating_status
FROM service_requests r
LEFT JOIN participations p ON p.request_id = r.id
LEFT JOIN ratings rt ON rt.participation_id = p.id;''']
    return md,sql,by

if __name__=='__main__':
    md,sql,by=generate()
    extra=(ROOT/'diccionario-mysql-anexos.md').read_text(encoding='utf-8')
    md.append(extra)
    (ROOT/'CANVAS-Diccionario-Datos-MySQL-TecnicoYa.md').write_text('\n'.join(md)+'\n',encoding='utf-8')
    (ROOT/'Esquema-MySQL-TecnicoYa-REFERENCIA.sql').write_text('\n'.join(sql)+'\n',encoding='utf-8')
    (ROOT/'Diccionario-MySQL-TecnicoYa.json').write_text(json.dumps({'version':'1.0','engine':'MySQL 8.4 InnoDB','status':'proposed_not_executed','tables':tables},ensure_ascii=False,indent=2),encoding='utf-8')
    print(f'{len(tables)} tablas; {sum(len(t["columns"]) for t in tables)} atributos; {sum(bool(c["reference"]) for t in tables for c in t["columns"])} FK.')
