"""Colección v2: fuentes locales, decisiones explícitas y planes no confundidos con ejecución."""
from pathlib import Path
import json, csv, hashlib, shutil, re
from xml.sax.saxutils import escape
from reportlab.platypus import SimpleDocTemplate, Paragraph, Spacer, PageBreak, Table, TableStyle, KeepTogether
from reportlab.lib.styles import ParagraphStyle
from reportlab.lib import colors
from reportlab.pdfbase import pdfmetrics
from reportlab.pdfbase.ttfonts import TTFont
from pypdf import PdfReader

ROOT=Path(__file__).resolve().parents[1]
OUT=ROOT/'docs/documentacion'
EDIT=OUT/'editables/v2'
EDIT.mkdir(parents=True,exist_ok=True)
DATE='29/09/2026'
inventory_path=ROOT/'tmp/pdfs/articulos/inventory.json'
if not inventory_path.exists():inventory_path=OUT/'fuentes/articulos/manifest.json'
inventory=json.loads(inventory_path.read_text(encoding='utf-8'))
docs=[]
def sec(title,text):return {'title':title,'text':text}
def table(title,heads,rows):return {'title':title,'heads':heads,'rows':rows}
def page(title,*sections):return {'title':title,'sections':list(sections)}
def doc(name,title,pages):docs.append({'name':name,'title':title,'pages':pages})

# Juicios analíticos del expediente; no son conclusiones atribuibles a todos los autores.
ART=[
('A01','Velásquez Chacón (2025). Adopción digital en micro y pequeñas empresas post pandemia en Arequipa, Perú','Encuesta cuantitativa exploratoria a 267 MYPES.','Identifica barreras de conocimiento y capacitación en adopción digital.','Arequipa y contexto pospandemia; no mide demanda de técnicos en Huancayo ni demuestra causalidad.','Diseñar alta guiada y probar comprensión con MYPES locales.','1-2, 14','10.31637/epsir-2025-1849'),
('A02','Widell, Dhakal, Thakur y Hafner (2019). Refrigeration to prevent food losses','Síntesis técnica sobre cadena de frío, con foco en China e India.','Relaciona pérdidas alimentarias con limitaciones de la cadena de frío y propone capacitación y mejora técnica.','Cifras globales e históricas; no cuantifica pérdidas de comercios huancaínos.','Justifica incluir refrigeración; medir tiempo sin servicio y no prometer ahorro económico.','1-2, 7','10.18462/iir.icr.2019.424'),
('A03','Aveklouris, DeValve, Stock y Ward. Matching Impatient and Heterogeneous Demand and Supply (arXiv:2102.02710v5)','Modelo matemático de demanda y oferta heterogénea con abandono; aproximación fluida.','El equilibrio entre rapidez y calidad depende de la distribución de paciencia.','Resultados asintóticos bajo supuestos; no validan 10 minutos ni los pesos de TécnicoYa.','Mantener plazos configurables y medir aceptación, espera y abandono.','1, 31','arXiv:2102.02710v5'),
('A05','Liu, Li, Wu y Zhang (2021). Two Basic Queueing Models of Service Platforms in Digital Sharing Economy','Dos modelos de colas y ejemplos numéricos.','Analiza estabilidad, espera, oferta ociosa y beneficios bajo distintas políticas.','Modelos simplificados; no representan una medición de carga del servidor.','Separar capacidad del marketplace de capacidad informática; simular ausencia de técnicos.','1-3','arXiv:2108.02852v1'),
('A06','Demsyn-Jones (2022). Measurement and Applications of Position Bias in a Marketplace Search Engine','Estudio aplicado en Thumbtack con intervención aleatoria en posiciones.','La posición influye en interacción y puede contaminar señales históricas del ranking.','Una plataforma concreta; no implica que el ranking local ya sea imparcial.','Medir exposición por zona y nuevos técnicos; documentar pesos y desempates.','1, 13','arXiv:2206.11720v2'),
('A07','Kido y Ohtsubo (2026). Reputation and institutional certification as complementary trust mechanisms in a single online market','Estudio transversal de casi un millón de anuncios de cartas Pokémon en eBay y modelo de señalización.','Reputación y certificación cumplen funciones complementarias según contexto y valor.','Preprint; mercado de coleccionables, sin identificación causal de todos los mecanismos.','Distinguir verificación administrativa de puntuación; una bandera no equivale a certificación profesional.','1, 10-11','arXiv:2608.17312v2'),
('A08','Micha, Trombetta y Pereyra (2024). Digital Labor Platforms, Domestic Work and Formalization: Evidence from Argentina','Documento de trabajo RedNIE 330; 300 trabajadoras, 1048 observaciones empleo-persona, efectos fijos.','Encuentra asociación favorable entre uso de la plataforma y formalización en el caso estudiado.','El documento declara no haber sido revisado por pares; sector y marco argentino.','No afirmar que registrar técnicos formaliza su trabajo; documentar independencia y alcance de la plataforma.','2-3','RedNIE 330'),
('A09','Luca (2017). Designing Online Marketplaces: Trust and Reputation Mechanisms','Síntesis económica sobre mecanismos de reputación e información.','El diseño de reseñas y de información visible influye en confianza y discriminación.','No es evaluación experimental de TécnicoYa ni prescribe un stack.','Una calificación por servicio propio; trazabilidad y canal de revisión propuesto.','1-2, 15-16','Capítulo NBER, pp. 77-93'),
('A10','Herrera Zuasnábar, Uribe Kajatt y Rey-de-Castro Hidalgo (2023). Pagos digitales e inclusión financiera','Estudio transversal descriptivo-correlacional; método: muestra de 164 microempresarios de una población de 283, en Pueblo Libre.','Reporta correlación 0,858 entre pagos digitales e inclusión financiera.','Correlación no equivale a causalidad. El resumen llama población a 164; el método precisa muestra de 164 sobre 283.','Pagos como ampliación sujeta a validación; no imponer suscripción por esta evidencia.','2, 6-7, 10','10.15381/idata.v26i2.25582'),
('A11','Ibarra-Fretell y Grijalva-Salazar (2025). Hacia una economía plataformizada: el impacto de las plataformas digitales en las MYPEs de Lima, Perú','Encuesta descriptiva no experimental a 385 MYPES de ropa en Gamarra.','El 67,5% reporta redes sociales como principal plataforma; hay barreras técnicas y financieras.','Sector textil de Lima; no mide directamente tiempos de reparación ni Huancayo.','Usar lenguaje familiar y flujo corto; contrastar canal informal mediante estudio local.','1, 5, 7','10.15649/2346030X.3530'),
('A12','Dedema y Rosenbaum (2024). Socio-technical issues in the platform-mediated gig economy','Revisión sistemática: 515 registros, 132 trabajos codificados, nueve bases.','Agrupa problemas en entorno laboral digital, gestión algorítmica y diseño ético.','Heterogeneidad de plataformas; síntesis no sustituye requisitos verificables.','Incluir privacidad, transparencia, revisión de decisiones y autonomía del técnico.','1, 20, 23','10.1002/asi.24868'),
('A13','Valente y colaboradores (2026). Fairness in the Latin American platform economy','Evaluación Fairwork con fuentes públicas, trabajadores y gestores; 68 plataformas.','Discute remuneración, condiciones, contratos, gestión y representación.','El resumen habla de nueve países y la conclusión de ocho sudamericanos; conservar discrepancia, no unificar cifras.','Incorporar reglas de suspensión explicables y revisión humana; no prometer empleo justo solo por digitalizar.','1-2, 18','10.5209/crla.103717'),
('A14','Peña-García, Losada-Otálora, Pérez Auza y Cruz (2024). Reviews, trust, and customer experience in online marketplaces','326 respuestas válidas; muestra por conveniencia de compradores de Mercado Libre Colombia; PLS-SEM.','La calidad percibida de reseñas se relaciona con confianza; se estudia percepción de reseñas falsas.','Hay diferencias entre la redacción de limitaciones y la tabla de hipótesis; no convertir toda relación en causalidad.','Vincular calificación a servicio completado y mostrar cantidad de reseñas.','1, 10-11','10.3389/fcomm.2024.1460321'),
('A15','Taylor (2018). On-Demand Service Platforms','Modelo analítico de precios, remuneración, sensibilidad a espera e independencia del proveedor.','Las decisiones óptimas dependen de incertidumbre y características del mercado.','No entrega tiempos universales ni precios válidos para Huancayo.','Distinguir respuesta del técnico de llegada al domicilio y de duración del trabajo.','1-3','10.1287/msom.2017.0678'),
('A17','Yan, Liu, Shi y Liu (2022). On-demand service platform operations management: a literature review and research agendas','Revisión de 72 artículos de cuatro bases; compara plataformas individuales y múltiples.','Identifica agendas dinámicas, métodos empíricos y modelización combinada.','No establece un tamaño de servidor ni un algoritmo ganador universal.','Evaluar el ranking con datos locales y carga reproducible antes de cambiar arquitectura.','1, 11-12','10.1108/MSCRA-01-2022-0002'),
('A18','Sterner (2026). Biases in online reputation systems: a survey of the empirical literature','Revisión de literatura empírica sobre reputación.','Distingue manipulación, reciprocidad, influencia social, selección y ruido.','Sesgo hacia literatura inglesa y plataformas consolidadas; transferibilidad limitada.','Registrar exposición, volumen de reseñas y riesgos del arranque sin historial.','1, 49-50','10.1007/s10660-026-10176-7'),
('A19','Teng, Botelho y Sudhir (borrador 2025 según archivo). Can customer ratings be discrimination amplifiers?','Modelo analítico y datos de una plataforma de trabajo; segmentos de clientes.','Los promedios mostrados pueden amplificar sesgos de valoraciones anteriores.','Borrador; magnitudes dependen del modelo y población; no trasladar brechas porcentuales a TécnicoYa.','No usar puntuación como único criterio; investigar apelaciones y exposición de perfiles nuevos.','1-2; discusión final','Borrador local, sin DOI confirmado'),
('A20','Fuentes y González (2025). Transitions into and out of the gig economy','Datos longitudinales de la Encuesta Nacional de Empleo de Chile, 2021T1-2024T1; modelos probit.','Describe alta rotación y transiciones entre trabajo de plataformas, empleo y desempleo.','Contexto chileno y asociaciones observacionales; no garantiza ingresos sostenibles.','Disponibilidad voluntaria y métricas de permanencia, sin promesas de empleo estable.','2, 12','10.1080/1369118X.2025.2496896'),
('A21','Peng, Kalliamvakou, Cihon y Demirer (2023). The Impact of AI on Developer Productivity: Evidence from GitHub Copilot','Experimento controlado con 95 desarrolladores asignados; tarea de servidor HTTP en JavaScript.','Reporta menor tiempo de realización con asistencia en esa tarea.','No evalúa calidad del código ni demuestra utilidad de un chatbot para contratar técnicos.','IA como apoyo de desarrollo con revisión y pruebas; no justificación principal de un LLM de negocio.','1, 5, 7-8','arXiv:2302.06590v1'),
('A22','Ibrahim y Zaki (2026, versión suministrada). Understanding AI Provider Recommendations in Local Service Markets','Auditoría de recomendaciones con registros oficiales en 100 áreas metropolitanas de EE. UU.','La configuración de recuperación cambia la existencia y selección de proveedores recomendados.','Preprint reciente; dominios y registros de EE. UU.; no certifica resultados para técnicos peruanos.','LLM opcional solo para estructurar texto; técnicos, precios y permisos deben salir de la base real.','1, 8, 10','arXiv:2609.18341v1'),
('A23','Aji y colaboradores (2022). Quick Reacher: An Application for Home Services','Prototipo de servicios y tiendas; ubicación, opiniones y módulos por rol.','Describe selección de proveedores y quejas en una aplicación web.','Conclusión de desarrollo sin evaluación de impacto local reproducible; incluye comercio ajeno al MVP.','Tomar separación de roles y solicitud; excluir tienda e inventario del núcleo.','2, 7','10.22214/ijraset.2022.43552'),
('A24','Raj y Koushik (2025). AI-Driven Optimization of On-Demand Services','Propuesta de DBSCAN, predicción y precios dinámicos; resultados tabulados.','Reporta mejoras de asignación y tiempos; menciona simulaciones con datos reales.','El resumen dice 30% y el cuerpo 40% para rapidez/tiempo con métricas no equivalentes; faltan detalles suficientes de dataset y réplica.','Antecedente exploratorio; mantener baseline determinista y exigir benchmark antes de usar DBSCAN.','1, 5-6','IJCRT25A3180'),
('A25','Gothankar y colaboradores (2024). HomeServe: The On-Demand Home Services Platform','Descripción de plataforma, matching, rutas y pantallas.','Integra roles, reservas y búsqueda de servicios domésticos.','Resultados principalmente descriptivos y capturas; no demuestra aumento cuantificado de ingresos.','Referencia funcional; no copiar ruteo ni agenda sin un requisito aprobado.','1, 4-6','IJRAR24B1713'),
('A26','Tambe y colaboradores (2020). An Online System for Home Services','Propuesta de sistema doméstico, autenticación, servicios y puntuaciones.','Presenta centralización de búsqueda y comunicación entre proveedor y cliente.','Sin prueba comparativa sólida de reducción de espera en el contexto de TécnicoYa.','Referencia de flujo; validar mediante casos de aceptación locales.','1, 4','IJSDR2009067'),
('A27','Rathod y colaboradores (2025). Android Application for Home Services: Cappie','Prototipo Flutter con categorías, GPS, reservas y pagos.','Identifica dificultades en dispositivos modestos e integración de pagos.','Describe satisfacción y carga sin suficiente protocolo numérico en la conclusión.','Priorizar web móvil liviana; medir en dispositivos modestos antes de añadir apps nativas.','1, 4','IRJMETS, vol. 7, núm. 4, p. inicial 11437'),
('A28','Krishna Veni y Bharathkumarmr (2025). Home Services Management System','Descripción de sistema web/móvil con cliente, proveedor y administración.','Enumera reservas, pagos, opiniones y supervisión.','La bibliografía incluye agricultura y clima sin relación directa clara; baja fuerza para justificar decisiones técnicas.','Usar solo como antecedente funcional secundario; no como evidencia de escalabilidad o seguridad.','1, 4-5','10.56726/IRJMETS87015'),
('A29','Anasune, Shaikh, Sharma y Singh (2026). Reparo: A Hyper-Local, On-Demand Home Service Platform','Prototipo Next.js/NestJS/Supabase; menciona evaluación con 30 usuarios.','Reporta tiempos y disponibilidad, además de RBAC y matching local.','No trasladar 99,7% ni 500 ms sin duración, carga y réplica; referencias poco detalladas.','Comparar responsabilidades, no reemplazar stack; medir nuestro despliegue.','1, 5-6','10.48175/IJARSCT-34358'),
('A30','Bejarano Gavilanes (2022). Implementación de una aplicación web para gestión de servicios técnicos a domicilio y control de inventario','Proyecto de titulación, Instituto San Gabriel; caso Centro Comercial Machado, Riobamba.','Documenta Laravel/MySQL y levantamiento de necesidades del negocio.','Caso institucional con inventario; no comparación de motores ni marketplace regional validado.','Antecedente de implementación Laravel; PostgreSQL se conserva por arquitectura actual, no por superioridad demostrada.','1, 68-69','Tesis local, octubre de 2022'),
('A31','Navarro Rossel y Tang Gómez (2019). Plataforma digital que conecte responsables del hogar con técnicos de servicios del hogar','Trabajo de suficiencia profesional, Universidad de Lima; propuesta de negocio, diseño y encuestas.','Anexos presentan 56 responsables del hogar y 53 técnicos; destaca confianza y dificultad de contacto.','Encuestas de Lima y antigüedad del estudio; no estimación representativa de Huancayo.','Antecedente nacional más próximo al servicio; repetir diagnóstico y prueba de valor en Huancayo.','1, 116-117, 128-130','Universidad de Lima, octubre de 2019'),
('A32','Einav, Farronato y Levin (2015). Peer-to-Peer Markets','Documento de trabajo NBER 21496; revisión y modelo económico.','Explica búsqueda, matching, precios y reputación como decisiones del diseño de mercados.','Versión de trabajo no revisada por NBER; no prescribe software ni beneficios locales.','Definir marketplace de dos lados y separar confianza, asignación y monetización.','1-4, 24-25','NBER Working Paper 21496')
]
articles=[]
for a in ART:
 id,title,method,finding,limit,use,pages,ref=a
 inv=next(x for x in inventory if x['id']==id)
 articles.append(dict(id=id,title=title,method=method,finding=finding,limit=limit,application=use,pages=pages,reference=ref,filename=Path(inv['path']).name))

CONTROL='Versión 2.0 | Corte documental: 29/09/2026. Documento técnico para revisión académica. Implementado significa observado en código; no equivale a validación productiva. Las iteraciones son planes de trabajo, no actas ejecutadas.'
CURRENT='React/Vite en frontend/web; Laravel en backend/api; FastAPI en python/api. PostgreSQL es referencia de despliegue; SQLite local y de pruebas no demuestra los bloqueos de PostgreSQL. No existe multitenencia empresarial, agenda por horas, chat, LLM de negocio, suscripción ni cobro integrado en el código inspeccionado.'
RULES='Respuesta: 10 minutos; máximo 3 ofertas simultáneas; ventana global: 24 horas; calificación: 48 horas desde finalización. Pesos: cercanía 35%, tarifa 20%, valoración 30%, experiencia 15%. Fuente única: domain/rules.json. Son decisiones del proyecto, no valores demostrados por los artículos.'
REFS='Las referencias [Axx] remiten a las fichas del documento 01 y al catálogo trazabilidad/v2/articulos.csv. Páginas citadas: numeración física del PDF, salvo indicación expresa. Los originales se conservan en fuentes/articulos/Axx.pdf; SHA-256 en fuentes/articulos/manifest.json.'
STANDARDS=[['ISO 9001:2026','Gestión de procesos, riesgos, mejora y control documental. Nueva edición verificada; base anterior 2015 conservada como antecedente.','https://www.iso.org/standard/9001'],['ISO/IEC/IEEE 29148:2018','Requisitos identificables, verificables y trazables.','https://www.iso.org/standard/72089.html'],['ISO/IEC 25010:2023','Modelo de calidad de producto para organizar RNF.','https://www.iso.org/standard/78176.html'],['ISO/IEC/IEEE 29119-3:2021','Estructurar plan, casos, incidentes y resultados de pruebas.','https://www.iso.org/standard/79429.html'],['OWASP ASVS','Requisitos verificables de seguridad; fijar versión y controles antes de auditoría.','https://owasp.org/projects/asvs'],['WCAG 2.2 AA','Objetivo de accesibilidad; requiere evaluación manual y automática.','https://www.w3.org/TR/WCAG22/'],['Scrum Guide 2020','Marco de iteraciones y revisión del incremento; no metodología de base de datos.','https://scrumguides.org/scrum-guide.html']]

p1=[page('Propósito, problema y alcance',sec('Control documental',CONTROL),sec('Producto','TécnicoYa Huancayo conecta hogares y MYPES con técnicos independientes de cómputo, refrigeración comercial y electricidad. El problema declarado por el proyecto es la búsqueda dispersa, la información desigual sobre calidad y tarifa, y la falta de seguimiento. Es una hipótesis contextual que debe validarse en Huancayo, no una prevalencia ya demostrada.'),sec('Objetivo general','Diseñar, implementar y evaluar un marketplace que permita solicitar, asignar, confirmar, ejecutar y calificar servicios, con permisos por rol y trazabilidad. Medir reducción de fricción frente al proceso actual mediante un piloto acordado; no prometer resultados aún no medidos.'),table('Objetivos específicos',['ID','Resultado verificable','Medición'],[['O1','Registrar una falla y revisar condiciones','Tarea completada, errores, pasos y tiempo'],['O2','Asignar únicamente técnicos elegibles','Casos de filtro, ranking y vencimiento'],['O3','Controlar quién puede operar y ver datos','Pruebas por rol, propietario y estado'],['O4','Trazar la atención hasta calificación','Secuencia de eventos y límites temporales'],['O5','Evaluar calidad y operación','Pruebas, piloto local y despliegue QA reproducible']]),sec('Arquitectura de partida',CURRENT)),
page('Método de revisión del corpus',sec('Universo documental','32 archivos PDF, 894 páginas físicas incluyendo duplicados. Se detectaron dos pares idénticos por SHA-256: A04=A03 y A16=A15. La revisión considera 30 documentos únicos (813 páginas sin duplicados), incluyendo artículos, revisiones, preprints y tesis. No es una revisión sistemática exhaustiva: el corpus fue entregado por el usuario, sin búsqueda bibliográfica completa ni protocolo PRISMA.'),sec('Procedimiento','Se extrajo el texto de los 32 archivos, se identificaron título, método, resultados y limitaciones pertinentes, y se elaboró una ficha crítica por documento único. Se contrastaron hallazgos con el código y requisitos previos. A32 presentó codificación deficiente con pypdf y se recuperó con pdfplumber. No se realizó metaanálisis ni réplica de experimentos.'),sec('Jerarquía de uso','Revisiones y estudios empíricos sustentan riesgos y principios; prototipos ilustran funciones; tesis aportan contexto e implementación; preprints se identifican expresamente. El índice de impacto impreso en una portada no acredita por sí solo calidad metodológica. La clasificación es una evaluación de este expediente.'),sec('Límites','Los estudios peruanos se concentran en Lima y Arequipa; no demuestran el diagnóstico de Huancayo. La justificación de electricidad y cómputo es principalmente funcional; faltan mediciones sectoriales locales. No se verificó externamente cada DOI ni la revisión por pares de cada revista. Se conservan las versiones suministradas.'),sec('Lectura de citas',REFS)),
page('Síntesis crítica y decisiones',table('Del hallazgo al requisito',['Evidencia','Decisión para TécnicoYa','Validación pendiente'],[['A01, A11: barreras digitales','Registro corto, lenguaje claro, web móvil','Piloto con hogares y MYPES de Huancayo'],['A09, A14, A18: confianza y sesgos','Reseñas ligadas a servicios; mostrar cantidad','Revisión de fraude, apelaciones y arranque sin historial'],['A03, A05, A15: espera y oferta','Temporizadores y reasignación','Calibrar plazos con datos locales'],['A06, A12, A13, A19: exposición y gobernanza','Explicar ranking y suspensiones; revisión humana','Evaluar equidad sin recolectar datos sensibles innecesarios'],['A22: referencias inventadas por IA','Catálogo real y parser opcional sin autoridad','Evaluar alucinación e inyección antes de activar IA'],['A23-A31: prototipos de servicios','Roles y flujo integrado','No importar porcentajes ni stacks por imitación']]),sec('Alertas de lectura','A24 presenta métricas de rapidez que requieren reconciliación (resumen 30%, tabla 58 a 35 segundos y texto 40%). A28 incluye bibliografía de agricultura y clima; se limita a referencia secundaria. A29 no sustenta por sí solo disponibilidad de nuestro servidor. A13 difiere en el número de países según sección. Estas observaciones reducen la fuerza de la inferencia; no invalidan automáticamente cada trabajo.'),sec('Lo que no se concluye','No se concluye que TécnicoYa genere empleo formal, reduzca pérdidas en una proporción determinada, garantice seguridad técnica de una reparación o requiera un LLM. Ninguna fuente del corpus justifica los pesos 35/20/30/15 como óptimos.')),
page('Investigación local y fronteras del MVP',table('Incluye / no incluye',['Núcleo actual','Fuera del núcleo / ampliación'],[['Tres roles y técnicos habilitados','Certificación externa automática de competencias'],['Solicitudes, ofertas, confirmación, ejecución y calificación','Inventario, tienda, múltiples técnicos simultáneos'],['Disponibilidad booleana y cobertura por zonas','Agenda horaria, GPS en vivo y optimización de rutas'],['Tarifa de visita fijada al aceptar','Pasarela real, comisiones y suscripciones'],['Registro y formularios deterministas','Chat y LLM: ampliaciones documentadas, no implementadas']]),sec('Plan de validación del problema','Preparar entrevistas y observación del flujo AS-IS con hogares, MYPES y técnicos de los cinco distritos. Propuesta exploratoria: 12 clientes (6 hogares y 6 MYPES) y 8 técnicos, con diversidad de rubros; muestra por conveniencia, sin representatividad estadística. Acordar consentimiento, anonimización y preguntas antes de reclutar. Registrar tiempo de contacto, intentos, criterios de confianza, falla y costo de interrupción declarado.'),sec('Evaluación del valor','Comparar tareas equivalentes con el canal habitual y con el prototipo, alternando orden para reducir aprendizaje. Reportar mediana, dispersión, abandonos y sesgos; no atribuir causalidad con una muestra exploratoria. Separar tiempo hasta recibir oferta, confirmación y atención efectiva. Los 10 minutos son respuesta, no llegada.'),sec('Aprobación','Product Owner, docente y equipo deben confirmar alcance y criterios de salida. No se inventan responsables nominales, firmas, fechas de sprints ni resultados del piloto.'))]
for i in range(0,len(articles),2):
 sections=[]
 for a in articles[i:i+2]:
  sections += [sec(a['id']+' | '+a['title'], 'Método: '+a['method']+'\nHallazgo: '+a['finding']+'\nLímite: '+a['limit']+'\nAplicación propuesta: '+a['application']+'\nLocalización: PDF pp. '+a['pages']+'. Referencia: '+a['reference']+'. Archivo: '+a['filename'])]
 p1.append(page('Fichas de evidencia '+str(i+1)+'-'+str(min(i+2,len(articles))),*sections))
doc('01-Analisis-del-MVP-TecnicoYa-Huancayo.pdf','Análisis del MVP y sustento científico',p1)

doc('02-Analisis-MVP-Matching-y-Asistencia.pdf','Análisis detallado: matching y asistencia',[
page('Propósito y principio rector',sec('Propósito',CONTROL+' '+REFS),sec('Principio rector','El servidor determina identidad, permisos, elegibilidad, tarifa y transición del servicio. El cliente confirma la contratación. Un asistente, si se incorpora, solo ayuda a capturar información: no inventa técnicos ni acepta servicios en nombre del usuario.'),sec('Estado actual',CURRENT),sec('Reglas clave',RULES),table('Actores y casos de uso',['Actor','Caso principal','Restricción'],[['Cliente','CU1 solicitar; CU2 confirmar; CU3 seguir; CU4 calificar','Solo sus solicitudes; no inicia ni termina trabajos'],['Técnico','CU5 responder; CU6 ejecutar; CU7 cambiar disponibilidad y tarifa','Solo ofertas propias y trabajos asignados'],['Administrador','CU8 verificar; CU9 suspender/reactivar; CU10 supervisar','No convierte registro público en cuenta admin'],['Sistema','CU11 vencer ofertas y reasignar','Respeta plazo global y no repite candidato']]),sec('Separación del ejemplo sanitario','No se usa paciente, consulta médica ni consultorio como entidad. El aislamiento entre usuarios es autorización por propiedad, no multitenencia. La suscripción del ejemplo se sustituye por habilitación del técnico; cualquier cobro futuro requiere decisión propia.')),
page('Procesos AS-IS y TO-BE',sec('AS-IS declarado, pendiente de campo','Cliente detecta falla -> consulta contactos o redes -> busca técnico -> negocia -> recibe atención -> conserva referencias dispersas. Los puntos de dolor son hipótesis del proyecto a contrastar con A01, A11 y A31 y con investigación local.'),sec('TO-BE actual','Cliente autenticado registra rubro, zona, dirección y falla. Laravel filtra elegibles y ordena el ranking; envía hasta tres ofertas internas. Un técnico acepta antes de vencer. Se fija agreed_fee y se requiere confirmación del cliente. Técnico inicia y finaliza; cliente puede calificar hasta 48 horas. Cada transición agrega evento.'),sec('Excepciones','Sin candidatos: pendiente de disponibilidad hasta 24 horas. Oferta rechazada o vencida: buscar siguiente sin repetir técnico. Dos aceptaciones concurrentes: una sola debe ganar bajo bloqueo; pendiente demostrarlo con PostgreSQL real. Cliente cancela antes de ejecución: liberar disponibilidad y cancelar ofertas. Calificación vencida: no inventar puntuación.'),sec('BPMN textual para Bizagi','Pools: Cliente, Plataforma, Técnico. Lane administrativa para habilitación. Evento de mensaje: solicitud. Tarea de servicio: calcular ranking. Compuerta exclusiva: ¿hay candidatos? Tarea de envío: hasta tres ofertas. Evento temporizador: 10 min por oferta y 24 h global. Compuerta basada en eventos: aceptación/rechazo/vencimiento. Confirmación cliente -> ejecución -> cierre -> temporizador de calificación. Modelar errores y cancelación en subproceso; el BPMN previo no cubre aún todas estas ramas.'),sec('Entregable de proceso','Conservar archivo BPMN editable, exportación PDF, versión de herramienta y prueba de recorrido con cada rol. Esta descripción no acredita validación de un diagrama en Bizagi.')),
page('Reglas de ranking y datos conceptuales',sec('Cálculo vigente','Elegibles: verificados, disponibles, especialidad y zona coincidentes, no excluidos por ronda anterior. Cercanía=1 en zona principal y 0,5 en otra cubierta; no son kilómetros. Precio=1 si todas las tarifas son iguales; en otro caso (máximo-tarifa)/(máximo-mínimo). Valoración=rating/5. Experiencia=min(años/10,1). Puntaje ponderado redondeado a 6 decimales.'),sec('Desempate y conflicto heredado','El código desempata por mayor valoración y después ID ascendente. RF-09 previo menciona antigüedad como criterio adicional. Se conserva como discrepancia D-01: decidir entre adecuar el requisito o añadir antigüedad validada. No declarar coincidencia total del código con el plan previo.'),sec('Modelo conceptual','Usuario 1 -> 0..1 Perfil técnico. Cliente 1 -> N Solicitudes. Solicitud 1 -> N Ofertas; técnico 1 -> N Ofertas. Solicitud 0..1 -> Técnico asignado. Calificación y eventos residen hoy en Solicitud. Administrador 1 -> N cambios de acceso y anuncios. Chat, reservas horarias y pagos son entidades futuras separadas.'),sec('Riesgos de ranking','Rating cero en nuevos técnicos reduce puntuación sin indicar mala calidad. La tarifa mínima puede favorecer precios no sostenibles. Exposición previa influye en reseñas [A06, A18, A19]. Proponer métricas y revisión humana; no alterar pesos sin datos y versionado.'),sec('TDD transversal','Definir un caso que falla (RED), implementar lo mínimo (GREEN), refactorizar conservando pruebas. Usar reloj fijo, identidades sintéticas y fixture compartido JS/PHP/Python. Que existan pruebas hoy no demuestra que el desarrollo histórico siguiera TDD.')),
page('Ampliaciones y criterios de cierre',table('Decisiones de producto',['Código','Propuesta','Condición'],[['E1','Chat determinista para registrar falla','Reusar validación y confirmación; no reemplazar formulario'],['E2','LLM solo extracción de campos','E1 estable, corpus etiquetado, presupuesto y proveedor aprobados'],['E3','Pagos integrados','Definir quién cobra, concepto, devolución y conciliación'],['E4','Agenda por franjas','Requisito nuevo, conflictos, zona horaria y pruebas concurrentes'],['E5','Empresas con varias cuentas','Tenants y membresías explícitos; no inferidos de roles']]),sec('Criterios de finalización del núcleo','Flujo cliente-técnico-admin reproducible en QA, pruebas negativas aprobadas, reglas sincronizadas, migraciones verificadas con PostgreSQL, respaldo restaurado, errores visibles y accesibilidad revisada. Cada requisito tiene evidencia o una exclusión aprobada. Chat, pagos y LLM no bloquean el núcleo mientras estén formalmente fuera de alcance.'),sec('Estado de pruebas conocido','El 28/09/2026 se ejecutaron 30 pruebas frontend y 19 Laravel (156 aserciones), además del build. Referencia: ejecución de la tarea de desarrollo; no se adjunta aquí un log nuevo ni se afirma cobertura porcentual. La suite Laravel usa SQLite. Se requiere generar evidencia persistente con commit, fecha y entorno en cada iteración.'),sec('Referencias',REFS))])

ITER=[
dict(n=1,slug='Base-de-datos',title='Base de datos: núcleo del marketplace',goal='Reproducir el esquema real y garantizar integridad en PostgreSQL.',state='Migraciones existentes; validación de concurrencia y recuperación en PostgreSQL pendiente.',refs='O2-O4; RF-01, RF-13, RF-23, RF-25; RNF-14. A09, A31.',deps='Base de código y copias de prueba; ninguna ampliación de negocio.',stories=[('HU-01','Como cliente quiero que mi solicitud se conserve sin mezclarse con la de otra cuenta.'),('HU-02','Como técnico quiero que una oferta y su aceptación queden registradas una sola vez.')],fe='Revisar tipos y nulabilidad consumidos en Marketplace.jsx. Mantener estados vacíos cuando no existan solicitudes. No crear tablas desde React.',be='Revisar las tres migraciones de backend/api/database/migrations; probar up/down únicamente en BD desechable. Mantener FK, unique(request_id, technician_id) e índices. Corregir diferencias de database/init.sql mediante migración nueva, no editando una ya aplicada.',py='Validar que las estructuras recibidas por /match mantengan IDs y números; no otorgar al microservicio acceso directo a la BD.',data='users, api_tokens, technicians, requests, offers, access_events y announcements. Diccionario físico en documento 04; tablas futuras en documento 05.',tests=[('I01-01','Insertar oferta duplicada para misma solicitud y técnico','La restricción unique rechaza la segunda fila'),('I01-02','Crear referencia a cliente inexistente','FK rechaza dato huérfano'),('I01-03','Restaurar respaldo en BD vacía de QA','Conteos y relaciones coinciden; guardar log sin secretos')],deploy='Desplegar BD QA aislada; ejecutar php artisan migrate --force con variables de QA y comprobar migrate:status. Nunca ejecutar migrate:fresh en la base del usuario.',risk='SQLite no demuestra lockForUpdate. No ampliar esquema de pagos/chat sin decisión de alcance.'),
dict(n=2,slug='Autenticacion-roles-y-permisos',title='Autenticación, roles y aislamiento de datos',goal='Asegurar que cada identidad solo opere sobre recursos autorizados.',state='Registro, login, revocación, permisos y propiedad implementados; endurecimiento productivo pendiente.',refs='O3; RF-28, RF-33; RNF-08, RNF-09. A09, A12.',deps='I01 y catálogo de permisos revisado.',stories=[('HU-03','Como usuario quiero iniciar sesión y ver el panel de mi rol.'),('HU-04','Como administrador quiero suspender una cuenta sin permitir reutilizar sus tokens.')],fe='Auth.jsx maneja registro e inicio; marketplace-api.js elimina sesión ante 401; Marketplace.jsx confirma actor mediante /state antes de mostrar datos. Probar cambio de cuenta con respuesta anterior demorada.',be='AuthController, ApiToken y Permissions son autoridad. Registro público solo client/technician; admin se crea con marketplace:admin. profile ignora role y userId arbitrarios. Suspensión revoca tokens; no suspender administradores ni cuentas con trabajo activo.',py='No recibe contraseñas, Bearer tokens ni direcciones para ranking. Su ruta debe estar restringida a red interna.',data='api_tokens guarda SHA-256 del token y expiración; users usa password hasheado e is_active. No existe tenant_id: aislamiento actual por propiedad. Multitenencia futura requiere diseño y migración específicos.',tests=[('I02-01','Cliente B intenta cancelar solicitud de A','403 y ningún cambio de estado'),('I02-02','Registro público envía role=admin','422; no crear usuario'),('I02-03','Suspender, reactivar y reutilizar token anterior','401; debe iniciar sesión otra vez'),('I02-04','Técnico no asignado consulta solicitud ofrecida','Dirección no revelada; no puede iniciar trabajo')],deploy='Migrar acceso en QA; crear administrador por comando interactivo sin contraseña predeterminada; smoke de tres roles. Tokens y secretos fuera de Git.',risk='Sin recuperación de contraseña ni MFA observados. No confundir ocultar botones con autorización real.'),
dict(n=3,slug='Habilitacion-y-condiciones-del-servicio',title='Habilitación y condiciones del servicio',goal='Controlar elegibilidad y mostrar condiciones económicas antes de confirmar.',state='Habilitación, disponibilidad, tarifa y cobertura implementadas. Cobros y suscripción no existen.',refs='O2-O3; RF-07, RF-18, RF-30. A07, A09, A13.',deps='I01-I02; definir qué evidencia revisa realmente el administrador.',stories=[('HU-05','Como técnico quiero gestionar tarifa y cobertura sin cambiar acuerdos activos.'),('HU-06','Como cliente quiero confirmar la tarifa de visita del técnico propuesto.')],fe='TechnicianProfile.jsx permite tarifa y zonas; bloquea edición con ofertas pendientes o atenciones. Admin muestra verificación y AccessManager suspensión. Mostrar que visita no incluye necesariamente materiales ni reparación completa.',be='technician-profile obtiene identidad de sesión, incluye zona principal y valida fee 0..100000. Bloquear cambio con ofertas pendientes o estados proposed/confirmed/in_progress. verify solo admin; nuevas cuentas técnicas no verificadas ni disponibles.',py='Elegibilidad exige verified y available; no aceptar un pago como prueba de competencia. Probar exclusiones antes del ranking.',data='technicians.fee es referencia actual; requests.agreed_fee se copia al aceptar. La revisión documental detallada no tiene entidad propia: proponer verification_reviews antes de afirmar certificación.',tests=[('I03-01','Técnico añade verified=true al editar tarifa','No se modifica verificación'),('I03-02','Cambiar fee teniendo oferta pendiente','409 y tarifa intacta'),('I03-03','Aceptar con fee=40 y revisar servicio','agreed_fee=40; futuras tarifas no alteran ese acuerdo')],deploy='Publicar incremento en QA; administrador habilita una cuenta sintética; técnico activa disponibilidad y cliente revisa condiciones.',risk='Sustituye el gating de suscripción de la plantilla sanitaria. No introducir plan de pago obligatorio ni prometer certificación externa.'),
dict(n=4,slug='Matching-disponibilidad-y-solicitudes',title='Matching, disponibilidad y ciclo de solicitudes',goal='Asignar y reasignar sin duplicados, respetando plazos y confirmación.',state='Algoritmo y ciclo implementados; integración real, concurrencia y calibración local pendientes.',refs='O2-O4; RF-06 a RF-19, RF-23. A03, A05, A06, A15.',deps='I01-I03; fixture y reglas versionados.',stories=[('HU-07','Como cliente quiero recibir una propuesta de un técnico elegible.'),('HU-08','Como técnico quiero responder antes del vencimiento sin doble asignación.')],fe='Mostrar estado y plazo real en RequestCard; no convertir contador en autoridad. Deshabilitar envío mientras procesa y mostrar 409 si otro actor ganó. Explicar ausencia de cobertura.',be='Marketplace::dispatch, tick y action conservan ventana global. Procesador cada segundo mediante schedule:work. Mantener bloqueo de solicitud y técnico. Evaluar idempotencia de create antes de reintento automático; hoy no se observa clave idempotente.',py='POST /match ordena elegibles y devuelve rulesVersion. Laravel contrasta IDs y puntajes con fallback local; timeout total 2 s, conexión 1 s. Probar caída, JSON inválido y versión divergente.',data='Ofertas pending/accepted/declined/expired/cancelled; no reiniciar pending_until al reasignar. Agreed_fee fija condición. Dirección solo asignado después de confirmación.',tests=[('I04-01','Cuatro técnicos elegibles al crear','Como máximo tres ofertas pendientes'),('I04-02','Aceptar en 10 minutos exactos','Oferta rechazada como vencida'),('I04-03','Avanzar reloj hasta 24 horas','unassigned; ninguna oferta pendiente'),('I04-04','Dos aceptaciones simultáneas en PostgreSQL','Una sola asignación; perdedor recibe conflicto'),('I04-05','Python caído o ranking alterado','Fallback PHP coincide con fixture')],deploy='Desplegar API y Python juntos en QA; ejecutar worker de plazos supervisado y reiniciarlo durante una solicitud de prueba. Verificar recuperación sin reiniciar ventanas.',risk='El score usa zonas, no GPS. La agenda del ejemplo se adapta a disponibilidad inmediata; reservas horarias quedan fuera del núcleo.'),
dict(n=5,slug='Frontend-tecnico-y-administrador',title='Frontend de técnico, administrador y UX',goal='Hacer operables las tareas de proveedor y supervisión con estados claros.',state='Paneles y anuncios por audiencia implementados; auditoría móvil y accesibilidad integral pendiente.',refs='O1-O3; RF-25, RF-30, RF-31; RNF-03, RNF-04. A01, A12, A27.',deps='I02-I04 y contratos estables.',stories=[('HU-09','Como técnico quiero distinguir ofertas, trabajos activos e historial.'),('HU-10','Como administrador quiero verificar perfiles y revisar cobertura por rubro.')],fe='Marketplace.jsx, AccountPanel.jsx, TechnicianProfile.jsx y Announcements.jsx. Revisar filtros, vacíos, busy, errores, teclado y foco visible. Mantener landing separada del panel y demo rotulada. No añadir roles elegibles en login real.',be='state filtra solicitudes por propietario/ofertas; users y accessEvents solo admin. announcement-save valida audiencia, texto, URL e imagen; borrar/archivar no equivale a perder historial de servicios.',py='No agregar endpoints de interfaz al motor de matching. Verificar que fallos de ranking no dejen pantalla sin mensaje.',data='Anuncios draft/published/archived para client/technician/both; catálogo de acceso visible sin hashes ni tokens.',tests=[('I05-01','Usuario cambia de cuenta con /state antiguo en vuelo','Respuesta antigua no reemplaza actor actual'),('I05-02','Cliente inspecciona respuesta API','Sin listado de usuarios ni auditoría administrativa'),('I05-03','Navegar formularios con teclado y móvil','Controles alcanzables, etiquetas y foco; sin desbordamiento'),('I05-04','Anuncio borrador o de otra audiencia','No visible al destinatario incorrecto')],deploy='Compilar Vite y publicar QA; smoke técnico y admin con identidades sintéticas. Registrar capturas de escritorio y móvil y defectos de accesibilidad.',risk='Verificado debe significar revisión definida; no usar badge como garantía absoluta. No asumir WCAG AA por tener foco visible.'),
dict(n=6,slug='Asistente-determinista-sin-LLM',title='Asistente determinista y registro guiado',goal='Proponer captura conversacional de una falla sin IA generativa.',state='Ampliación propuesta, no implementada. Requiere aprobación del Product Owner antes de desarrollo.',refs='O1; extensión EX-CHAT-01, relacionada con RF-01/02. A23, A25, A31.',deps='I02-I04; validar que el formulario actual resulta insuficiente.',stories=[('HU-11','Como cliente quiero describir mi necesidad paso a paso y revisar el resumen antes de enviarlo.')],fe='Crear componente propuesto ServiceAssistant con pasos rubro -> zona -> dirección -> descripción -> resumen. Atrás no pierde campos. Mantener formulario alternativo. Las respuestas son plantillas; no diagnósticos técnicos.',be='Reusar validación de create; añadir borrador persistente solo si se aprueba. Crear la solicitud únicamente al confirmar y con idempotencia del envío. No abrir chat libre entre usuarios en esta iteración.',py='Sin LLM y sin nuevo servicio obligatorio; la clasificación manual por catálogo es suficiente. El ranking sigue por /match al confirmar.',data='Propuesta service_drafts: owner, paso, datos y expiración. No almacenar conversación completa por defecto. Definir retención y borrado antes de activar.',tests=[('I06-01','Retroceder desde resumen y corregir zona','Resumen cambia; no hay solicitud prematura'),('I06-02','Repetir confirmación con misma clave','Una sola solicitud, misma respuesta'),('I06-03','Zona desconocida o texto vacío','Preguntar/corregir; no inventar valores')],deploy='Bandera de función apagada por defecto; habilitar en QA para usuarios de prueba. Rollback apaga bandera sin borrar solicitudes ya creadas.',risk='No confundir asistente guiado con chat técnico-cliente. Toda acción sigue autenticada y confirmada.'),
dict(n=7,slug='LLM-parseo-y-controles',title='LLM opcional: parseo y controles',goal='Evaluar extracción de campos desde texto manteniendo decisiones deterministas.',state='Experimento propuesto, no implementado ni aprobado para producción.',refs='O1-O3; EX-IA-01. A22 como riesgo de referencias inventadas; A21 solo apoyo al desarrollo.',deps='I06; dataset etiquetado, proveedor, costo y tratamiento de datos aprobados.',stories=[('HU-12','Como cliente quiero una sugerencia de rubro que pueda revisar y corregir antes de enviar.')],fe='Mostrar campos sugeridos y corrección manual. Pedir zona/dirección por controles explícitos; no inferir identidad. Si falla el parser, volver al flujo determinista sin perder borrador.',be='Proponer adaptador server-side que valida JSON cerrado y lista permitida de especialidades. No entregar credenciales al navegador. No permitir tool calls, SQL, confirmación, tarifas o asignación por salida del modelo.',py='Si se aloja parser en FastAPI, separar /parse propuesto de /match existente. Entrada limitada; salida {specialty, description, needsClarification}; validar enum y tamaño. Regla incierta -> null/pregunta, nunca inventar técnico.',data='Guardar solo resultado aceptado y versión del parser si se aprueba; registro de evaluación anonimizado, sin direcciones ni tokens enviados al proveedor por defecto.',tests=[('I07-01','Texto pide ignorar reglas y asignar admin','Sin cambio de permisos ni acción'),('I07-02','Modelo inventa técnico, precio o campo adicional','Esquema rechaza; fallback determinista'),('I07-03','Timeout o salida no JSON','Formulario usable; ninguna solicitud creada'),('I07-04','Corpus etiquetado con ambigüedades','Reporte por rubro de precisión, abstenciones y errores')],deploy='Solo QA, bandera apagada, cupo de costo y timeout fijados antes del ensayo. Comparar con baseline sin LLM. Activar únicamente si existe mejora medida sin pérdida de seguridad.',risk='No hay evidencia suficiente para prometer beneficio local de un LLM. No se ofrecen instrucciones peligrosas de reparación eléctrica ni diagnósticos automáticos.'),
dict(n=8,slug='Frontend-cliente-y-flujo-integral',title='Frontend cliente y flujo completo',goal='Validar de extremo a extremo la experiencia de solicitud a calificación.',state='Formulario y ciclo básico implementados; asistente opcional y E2E integral pendientes.',refs='O1-O4; RF-01, RF-18, RF-22, RF-23, RF-25. A01, A14, A31.',deps='I02-I05; I06 solo si se habilita asistente. I07 no es obligatorio.',stories=[('HU-13','Como cliente quiero revisar tarifa, confirmar, seguir y calificar mi atención con claridad.')],fe='RequestForm, RequestCard y Auth: mantener sesión, errores de red y datos ingresados; confirmar tarifa de visita y estado sin falsa promesa de llegada. Revisar video con movimiento reducido y acceso directo al formulario.',be='Verificar create, confirm, cancel y rate con autorización; calificar una vez, entero 1..5 y antes de 48 h. El historial no debe atribuir pagos inexistentes ni reporte técnico que todavía no se captura.',py='Probar flujo con Python activo y caído sin cambiar resultado esperado del ranking.',data='Una calificación por solicitud en requests; promedio y reviews del técnico se actualizan en transacción. El estado completed permanece si no se califica: resolver discrepancia RF-24 antes de afirmar cierre automático.',tests=[('I08-01','Crear -> aceptar -> confirmar -> iniciar -> finalizar -> calificar','Estados correctos, eventos y promedio consistente'),('I08-02','Cliente ajeno intenta confirmar o calificar','403 sin modificación'),('I08-03','Calificar a 48 horas exactas y duplicar envío','409 y no duplicar promedio'),('I08-04','Fallo de red durante envío','Mensaje claro; no reintento automático que duplique solicitud')],deploy='Smoke completo en QA con cliente, técnico y admin distintos. Conservar IDs sintéticos y capturas sin datos personales. Publicar evidencia de camino feliz y excepciones.',risk='Un éxito en demo localStorage no equivale a E2E real ni verifica privacidad. La prueba debe usar API y BD QA.'),
dict(n=9,slug='Pagos-y-operacion-productiva',title='Pagos y operación productiva: extensión condicionada',goal='Diseñar cobro verificable sin alterar el núcleo hasta aprobar el modelo comercial.',state='No implementado; diseño propuesto. No hay suscripción ni pasarela configurada.',refs='RF-32 previo (método de pago), EX-PAY-01 (cobro real nuevo). A10, A15, A32.',deps='Decidir si se cobra visita, comisión o suscripción; proveedor y obligaciones operativas; I02/I08/I10.',stories=[('HU-14','Como cliente quiero conocer qué pago y recibir un estado verificable sin cargos duplicados.')],fe='Proponer checkout alojado por proveedor; mostrar pendiente, pagado y fallido desde servidor. Redirección exitosa no prueba pago. No pedir tarjeta en formularios propios.',be='Proponer pagos, intentos y eventos únicos por proveedor. Verificar firma de webhook, monto, moneda y recurso; transacción idempotente. Conciliación y reembolso con auditoría. No activar una suscripción inexistente al volver de checkout.',py='Matching no participa en cobros ni recibe datos financieros. No cambiar ranking para privilegiar pagos sin regla de producto explícita.',data='payment_intents, payment_events y refunds propuestos. Importe en unidades menores enteras, moneda, referencia única, estado; sin PAN/CVV. Tabla de suscripciones solo tras aprobación independiente.',tests=[('I09-01','Webhook repetido y fuera de orden','No duplicar cargo ni degradar pago confirmado'),('I09-02','Firma inválida o monto diferente','Rechazar, registrar incidente y no activar nada'),('I09-03','Proveedor timeout después de aceptar pago','Conciliar antes de reintentar cargo'),('I09-04','Cliente intenta consultar pago ajeno','403/404 consistente sin filtración')],deploy='Sandbox de proveedor primero; documentación y secretos separados. Producción requiere decisión comercial, QA de seguridad y responsable de conciliación. No se realizan pagos reales en esta tarea.',risk='RF-32 no autoriza por sí solo cobro integrado. La evidencia de correlación en A10 no justifica imponer comisiones ni suscripción.'),
dict(n=10,slug='Seguridad-calidad-y-despliegue',title='Seguridad, calidad y despliegue previo al lanzamiento',goal='Cerrar riesgos del núcleo con evidencia y autorizar una versión candidata.',state='Pruebas unitarias/HTTP parciales existentes; carga, PostgreSQL real, restauración y auditoría integral pendientes.',refs='O3-O5; RF-33; RNF-01 a RNF-14. A12, A18, A29.',deps='I01-I05/I08 para núcleo. I06/I07/I09 únicamente si entran en la versión.',stories=[('HU-15','Como responsable de operación quiero desplegar y revertir una versión sin perder datos ni exponer cuentas.')],fe='Auditar teclado, reflujo móvil, errores, contraste y movimiento reducido; comprobar que videos no bloqueen login. Revisar dependencias, tamaño y carga de secuencias.',be='Pruebas negativas, límites, contraseñas y tokens; restringir debug y datos en logs. Ensayar aceptación concurrente y tareas de plazos en PostgreSQL. Revisar acceso al matching, uploads de anuncios y recuperación.',py='Pruebas de contrato, payloads límite, versión de reglas y caída. Restringir red y medir consumo; no exponer /match directamente a Internet.',data='Respaldo cifrado y restauración ensayada con objetivos acordados; política de retención y eliminación pendiente de revisión. Datos sintéticos para pruebas de carga.',tests=[('I10-01','Flujo E2E tras desplegar imagen versionada','Funciona con API, BD y worker reales'),('I10-02','Restauración en QA y rollback de aplicación','Integridad y compatibilidad comprobadas'),('I10-03','Carga objetivo de 200 concurrentes','Reportar mezcla, duración, p95, errores y recursos; no declarar éxito sin ensayo'),('I10-04','Auditoría de permisos y accesibilidad','Sin defectos críticos abiertos; hallazgos priorizados')],deploy='Puerta de salida: build, pruebas, migraciones, smoke, respaldo restaurado, seguridad y aceptación. Registrar imagen/commit, entorno, aprobador y reversión. Producción requiere aprobación final del responsable.',risk='No declarar certificación ISO, 99% mensual ni cobertura >=70% sin medición definida y evidencia. Toda excepción debe tener dueño y fecha de revisión.')
]

backlog=[page('Cómo trabajar este backlog',sec('Control',CONTROL),sec('Orden y alcance','Las diez iteraciones son paquetes de trabajo, no diez sprints ya realizados ni un calendario aprobado. I01-I05 e I08/I10 consolidan el núcleo. I06/I07/I09 son extensiones condicionadas. I09 depende de la puerta de calidad I10; sus números no obligan a publicar pagos antes de endurecer el sistema.'),sec('Scrum propuesto','Product Owner ordena valor y alcance; Developers estiman y producen incremento; Scrum Master facilita el marco. Proponer sprints de dos semanas, capacidad y fechas por acordar. Cada sprint incluye planificación, Daily Scrum, revisión y retrospectiva. Una iteración puede dividirse en varios sprints si supera capacidad.'),sec('Para un desarrollador junior','1. Leer historia y caso esperado. 2. Ubicar archivos. 3. Crear prueba que falla. 4. Cambiar una capa y validar contrato. 5. Ejecutar regresión. 6. Documentar migración y error. 7. Entregar en QA con evidencia. No copiar IDs, roles ni precios confiando en el navegador.'),sec('Definition of Ready','Historia con actor y valor, reglas, criterios positivos/negativos, dependencias, dataset y alcance aprobados. Sin un criterio comprobable, refinar antes de desarrollar.'),sec('Definition of Done','Código revisado, pruebas pertinentes aprobadas, contrato y diccionario actualizados, permisos probados, QA desplegado y evidencia vinculada a commit. Se documenta también lo pendiente. Un build exitoso no cierra aceptación ni rendimiento.'))]
for it in ITER:
 backlog.append(page('I%02d | %s'%(it['n'],it['title']),sec('Objetivo y estado',it['goal']+' '+it['state']),sec('Dependencias y trazabilidad',it['deps']+' '+it['refs']),table('Historias',['ID','Necesidad'],it['stories']),table('Trabajo por capa',['Área','Tarea concreta'],[['Frontend',it['fe']],['Laravel',it['be']],['Python',it['py']],['Datos',it['data']]]),sec('Cierre esperado',it['tests'][0][0]+': '+it['tests'][0][2]+'. '+it['deploy'])))
doc('03-Backlog-tecnico-de-implementacion.pdf','Backlog técnico de implementación',backlog)

# Diccionario físico extraído de las declaraciones reales de Blueprint.
meaning={
'users':'Identidades de los tres roles y habilitación de acceso.', 'api_tokens':'Sesiones revocables; nunca almacenar el token en claro.', 'technicians':'Perfil de oferta profesional; relación 1:1 opcional con usuario.', 'requests':'Solicitud y ciclo de atención del cliente.', 'offers':'Invitaciones individuales a técnicos y su respuesta.', 'access_events':'Auditoría de suspensión o reactivación de cuenta.', 'announcements':'Mensajes administrativos dirigidos por audiencia.'}
fieldmeaning={'name':'Nombre visible','email':'Correo de acceso único','password':'Hash de contraseña','role':'client, technician o admin (validación de aplicación)','is_active':'Permiso de acceso a la cuenta','token_hash':'SHA-256 del token Bearer','expires_at':'Caducidad de sesión (timestamp) u oferta (ms), según tabla','user_id':'Usuario al que pertenece el registro','actor_id':'Administrador que ejecutó cambio','zone':'Zona principal o zona solicitada','zones':'Arreglo JSON de zonas cubiertas','specialties':'Arreglo JSON de rubros técnicos','specialty':'Rubro solicitado','fee':'Tarifa vigente de visita en PEN','rating':'Promedio técnico o calificación del servicio, según tabla','reviews':'Número de calificaciones','years':'Años declarados de experiencia','verified':'Habilitación administrativa','available':'Disponibilidad operativa','client_id':'Propietario de la solicitud','address':'Dirección privada del servicio','description':'Descripción de falla','technician_id':'Técnico invitado o asignado','agreed_fee':'Tarifa de visita fijada al aceptar','created_ms':'Instante de registro en epoch ms','pending_until':'Fin de ventana de 24 h en epoch ms','completed_at':'Instante de finalización en epoch ms','rating_until':'Fin de plazo de 48 h en epoch ms','events':'Arreglo JSON {at,text} del ciclo','request_id':'Solicitud que originó la oferta','sent_at':'Instante de envío en epoch ms','score':'Puntaje redondeado a 6 decimales','action':'activate o suspend','title':'Título del anuncio','body':'Texto del anuncio','audience':'client, technician o both','priority':'Orden de presentación (0..100 API)','image':'Imagen data URL validada; no archivo externo','link_url':'URL http/https opcional','link_label':'Texto del enlace opcional','updated_by':'Administrador que modificó anuncio','status':'Estado del catálogo correspondiente','id':'Identificador primario'}
schema={}
for file in sorted((ROOT/'backend/api/database/migrations').glob('*.php')):
 text=file.read_text(encoding='utf-8')
 for match in re.finditer(r"Schema::(create|table)\('([^']+)',function\(Blueprint \$t\)\{(.*?)\}\);",text,re.S):
  kind,name,body=match.groups();fields=schema.setdefault(name,[])
  for m in re.finditer(r"\$t->(id|uuid|foreignId|string|text|json|decimal|unsignedInteger|unsignedTinyInteger|boolean|timestamp|bigInteger|longText|timestamps)\((.*?)\)([^;]*);",body,re.S):
   typ,args,chain=m.groups();names=re.findall(r"'([^']+)'",args);fname=names[0] if names else ('id' if typ=='id' else 'timestamps')
   if typ=='timestamps':
    fields.extend([dict(name=n,type='timestamp',null='Sí',rule='Marca temporal Eloquent',meaning='Fecha de creación' if n=='created_at' else 'Fecha de última modificación',source=file.name) for n in ['created_at','updated_at']]);continue
   typeval={'id':'bigint identidad','foreignId':'bigint FK','string':'varchar(255)','text':'text','longText':'text (PostgreSQL)','json':'json','uuid':'uuid','decimal':'numeric','unsignedInteger':'integer*','unsignedTinyInteger':'smallint*','boolean':'boolean','timestamp':'timestamp','bigInteger':'bigint'}.get(typ,typ)
   numeric=re.findall(r'\b\d+\b',args)
   if typ=='string' and numeric:typeval='varchar('+numeric[-1]+')'
   if typ=='decimal':typeval='numeric('+','.join(numeric)+')'
   constraints=[]
   if typ=='id' or 'primary()' in chain:constraints.append('PK')
   if 'unique()' in chain:constraints.append('UNIQUE')
   if 'index()' in chain:constraints.append('INDEX')
   if typ=='foreignId':constraints.append('FK; ver relaciones')
   default=re.search(r'->default\((.*?)\)',chain)
   if default:constraints.append('default '+default[1])
   fields.append(dict(name=fname,type=typeval,null='Sí' if 'nullable()' in chain else 'No',rule='; '.join(constraints) or 'Sin restricción adicional declarada',meaning=fieldmeaning.get(fname,'Ver contrato de dominio'),source=file.name))
physical=[page('Fuente de verdad y convenciones',sec('Alcance',CONTROL+' Este diccionario describe las tres migraciones Laravel inspeccionadas. No es un esquema MySQL ni una migración a otro motor.'),sec('Jerarquía de fuentes','Las migraciones aplicadas son la referencia del esquema evolutivo. database/init.sql es una referencia anterior y no incluye todas las incorporaciones recientes. PostgreSQL de despliegue y SQLite de desarrollo se distinguen; una columna unsigned de Blueprint no garantiza restricción de no negativos en PostgreSQL sin CHECK.'),sec('Notación','PK: clave primaria. FK: clave foránea. UNIQUE: unicidad. Nulo Sí/No describe declaración. epoch ms: milisegundos UTC desde Unix; visualización America/Lima. Montos en PEN con dos decimales; agreed_fee no representa cobro realizado. *: Blueprint unsigned requiere verificar SQL generado por motor.'),table('Relaciones',['Origen','Destino','Cardinalidad'],[['technicians.user_id','users.id','0..1 perfil por usuario, UNIQUE'],['requests.client_id','users.id','N solicitudes por cliente'],['requests.technician_id','technicians.id','0..1 asignado por solicitud'],['offers.request_id / technician_id','requests / technicians','N ofertas; par único'],['access_events.actor_id / user_id','users.id','Actor y cuenta afectada'],['announcements.updated_by','users.id','Administrador autor']]),sec('Seguridad de datos','No exponer password ni token_hash. Dirección accesible al cliente, admin y técnico asignado solo tras confirmación. Minimizar datos en logs. Catálogos de roles y estados están en aplicación; faltan CHECK equivalentes para varias reglas.'))]
for name,fields in schema.items():
 physical.append(page('Tabla: '+name,sec('Responsabilidad',meaning[name]),table('Columnas',['Campo / tipo','Nulo','Regla / significado'],[[f['name']+' ('+f['type']+')',f['null'],f['rule']+'. '+f['meaning']] for f in fields]),sec('Fuente','backend/api/database/migrations/: '+', '.join(dict.fromkeys(f['source'] for f in fields)))))
physical.append(page('Integridad y cambios pendientes',table('Restricciones adicionales',['Objeto','Declaración'],[['offers','UNIQUE(request_id, technician_id); índice expires_at; FK request con cascada de eliminación'],['requests','Índice status; technician_id FK nullable; client_id FK users'],['api_tokens','token_hash único; user_id FK con cascada'],['announcements','Índice compuesto (status, audience); updated_by FK']]),sec('Brechas del esquema','Validación de role, status, rangos y formatos reside principalmente en Laravel. Proponer CHECK para importes y calificaciones, restricciones de estados y política de eliminación antes de carga directa. Revisión de verificación profesional, chat y pagos no tiene tablas actuales. No incluirlas como ejecutadas.'),sec('Procedimiento de cambio','Crear migración nueva; probar con copia de QA, datos inválidos y rollback compatible; actualizar diccionario y contratos; registrar commit e imagen. No editar una migración ya desplegada para ocultar diferencias.')))
doc('04-Diccionario-de-datos-fisico-PostgreSQL.pdf','Diccionario de datos físico: PostgreSQL',physical)

doc('05-Diccionario-conceptual-y-contratos.pdf','Diccionario conceptual y contratos de datos',[
page('Conceptos y propiedad',sec('Propósito',CONTROL+' Complementa el diccionario físico: define significado de negocio y datos intercambiados, no duplica columnas.'),table('Concepto',['Entidad de negocio','Responsable','Regla'],[['Cuenta','Usuario autenticado','Un rol vigente; acceso revocable'],['Perfil profesional','Técnico','Habilitación y disponibilidad son independientes'],['Solicitud','Cliente','Una falla en un rubro y zona; propietario inmutable'],['Oferta','Sistema / técnico destinatario','Una invitación por técnico y solicitud'],['Acuerdo','Cliente y técnico','Asignación propuesta por aceptación y confirmada por cliente'],['Calificación','Cliente propietario','Única, 1..5, tras finalización y antes del vencimiento'],['Evento','Sistema','Traza temporal; no sustituye auditoría completa'],['Anuncio','Administrador','Audiencia y estado controlan visibilidad']]),sec('Modelo de relaciones','Cuenta cliente -> Solicitud -> Oferta <- Perfil técnico <- Cuenta técnica. Solicitud -> Perfil asignado es opcional hasta aceptación. No hay entidad de paciente, consultorio ni tenant. La dirección pertenece al contexto de la solicitud y no se envía al motor de ranking.'),sec('Glosario','Habilitado: verified=true; no certificación legal automática. Disponible: puede recibir ofertas. Propuesto: técnico aceptó, falta cliente. Tarifa: visita, no presupuesto total. Sin cobertura: no se asignó dentro del plazo, no significa ausencia definitiva de técnicos.')),
page('Contrato de escritura y lectura actual',table('Payload de acción',['Acción','Campos','Origen confiable'],[['create','specialty, zone, address, description','client_id sale de sesión'],['accept/decline/confirm/start/complete/cancel','id de solicitud','Permisos y estado en servidor'],['rate','id, rating entero 1..5','Cliente dueño; ventana de 48 h'],['technician-profile','zone, zones[], fee','Perfil identificado por usuario de sesión'],['verify','technicianId, verified boolean','Solo admin'],['accounts','userId, active boolean','Solo admin; protege trabajo activo'],['profile','name','Solo propio usuario'],['announcement-save','id opcional, título, texto, audiencia, estado y otros','Solo admin; ver validación del servicio']]),sec('GET /api/state','actor contiene id, name, role, email, permissions. state contiene requests, technicians, announcements, users y accessEvents. users y accessEvents están vacíos para no administradores. Técnicos ven solicitudes asignadas o con oferta previa; dirección es null antes de confirmación o si no son asignados. No se afirma anonimización completa del resto del historial.'),sec('Convención de IDs','actor.id técnico usa UUID del perfil; actor.id cliente/admin usa ID de users convertido a texto. userId de accounts usa ID numérico de users. No intercambiar identificadores; esta diferencia merece pruebas de contrato.'),sec('Errores','401 sesión ausente/vencida; 403 falta de autorización; 409 transición o condición incompatible; 422 datos inválidos. Validar mensajes legibles; no depender de texto exacto para lógica de permisos.')),
page('Estados y tiempos',table('Transición principal',['Desde','Evento autorizado','Hacia'],[['Sin solicitud','create cliente','searching o pending_availability'],['searching','accept técnico elegible','proposed'],['searching','decline/vencimiento','searching, pending_availability o unassigned'],['pending_availability','candidato disponible / 24 h','searching / unassigned'],['proposed','confirm propietario','confirmed'],['confirmed','start asignado','in_progress'],['in_progress','complete asignado','completed'],['completed','rate propietario dentro de plazo','rated'],['searching/pendiente/proposed/confirmed','cancel propietario','cancelled']]),sec('Reglas de tiempo',RULES),sec('Datos derivados','count de ofertas pendientes, contador de respuesta y cobertura se calculan; no son autoridad del navegador. rating del técnico es promedio incremental y reviews el denominador. No mezclar milisegundos con segundos ni timestamp SQL con epoch sin conversión.'),sec('Discrepancia de cierre','completed sin calificación no cambia automáticamente a rated ni a un nuevo estado al vencer. RF-24 previo exige cierre sin puntuación: conservar brecha y acordar semántica antes de implementar.')),
page('Modelo futuro separado del vigente',table('Extensión propuesta',['Concepto','Entidad propuesta','Campos mínimos','Condición'],[['Borrador guiado','service_drafts','id, owner, step, payload, expires_at','I06 aprobado; no contiene credenciales'],['Mensajería libre','conversations / messages','participantes autorizados, texto, fecha, retención','No incluida por defecto en I06'],['Pago','payment_intents / events','request, minor_amount, currency, provider_ref, status','I09; firma e idempotencia'],['Reembolso','refunds','payment, amount, reason, audit','Proceso aprobado y conciliación'],['Agenda','availability_slots / bookings','técnico, inicio, fin, zona horaria, estado','Fuera del núcleo; resolver solapamientos'],['Multitenencia','organizations / memberships','organización, usuario, rol de membresía','Nueva necesidad empresarial explícita']]),sec('Compatibilidad','Campos futuros no deben aparecer como tablas actuales ni migraciones ejecutadas. El parser LLM propuesto devuelve campos sugeridos, no IDs de técnicos ni precios. Los ejemplos de payload deben usar datos sintéticos y no copiar información personal de los artículos.'),sec('Referencias',REFS))])

doc('06-Diseno-tecnico-arquitectura.pdf','Diseño técnico: React, Laravel, FastAPI y PostgreSQL',[
page('Arquitectura y límites',sec('Control',CONTROL),table('Componente',['Ruta','Tecnología','Responsabilidad','Límite'],[['frontend/web','React + Vite','Landing, acceso, paneles y demo','No autoriza operaciones reales'],['backend/api','Laravel','Identidad, permisos, estados y transacciones','Fuente de verdad del servicio'],['python/api','FastAPI','Ranking numérico','No opera cuentas ni solicitudes'],['database + migraciones','PostgreSQL','Persistencia e integridad','No sustituye validación de API']]),sec('Recorrido de datos','Navegador -> web/proxy -> Laravel -> PostgreSQL. Laravel -> FastAPI /match, con fallback PHP si falla. Worker Laravel procesa plazos. JS calcula ranking solo para demo localStorage. En producción, API y matching deben quedar detrás de los controles de red previstos.'),sec('Decisión de stack','Se mantiene la arquitectura académica del monorepo por separación de responsabilidades y trabajo previo. A30 ilustra un caso Laravel/MySQL, pero no demuestra que MySQL sea obligatorio ni superior. A29 usa otro stack: se comparan capacidades, no marcas. Cambiar motor requiere ADR, migraciones y evaluación propias.'),sec('Riesgo de redundancia','La regla se replica en tres lenguajes por finalidad demostrativa. domain/rules.json y fixture compartido evitan cambios manuales divergentes. Laravel verifica ranking remoto contra su cálculo; esto añade trabajo duplicado que debe incluirse en las mediciones.')),
page('Secuencias técnicas principales',sec('Registro e inicio','React POST /api/register -> validación client/technician -> usuario y perfil en transacción -> 201 sin token. Login verifica hash y acceso -> crea token aleatorio, persiste hash y expiración -> actor. React consulta /state; recién entonces habilita panel. Logout elimina token; 401 borra sesión local.'),sec('Creación y matching','Cliente POST actions/create -> permisos -> validación -> transacción de solicitud -> filtrar candidatos -> llamada Python -> comprobar versión, orden y score -> fallback si corresponde -> insertar hasta tres ofertas -> persistir eventos -> devolver ok -> React refresca estado.'),sec('Aceptación y confirmación','Técnico POST accept -> lock solicitud -> validar oferta y reloj -> lock técnico -> verificar disponibilidad -> marcar oferta accepted, cancelar otras y fijar agreed_fee -> proposed. Cliente propietario POST confirm -> confirmed. Técnico asignado puede iniciar. Probar dos aceptaciones concurrentes con conexiones diferentes en PostgreSQL.'),sec('Finalización y valoración','complete solo asignado y desde in_progress -> completed + completed_at + rating_until; libera disponibilidad. rate solo propietario antes del límite y una vez -> actualiza promedio/reviews con bloqueo + rated. El backend rechaza transición repetida aunque UI se manipule.'),sec('Consistencia pendiente','create no incluye actualmente clave de idempotencia; se documenta como brecha de reintentos. El esquema no añade CHECK a todos los catálogos. Antes del lanzamiento se exige prueba concurrente y revisión de orden de bloqueos, no solo suite SQLite.')),
page('Decisiones arquitectónicas',table('Registro ADR',['Decisión','Motivo','Consecuencia'],[['ADR-01 Mantener políglota','Convención académica y motor independiente','Más contratos y pruebas de paridad'],['ADR-02 PostgreSQL referencia','Stack y Compose existentes','SQLite local no cierra pruebas de concurrencia'],['ADR-03 Matching determinista','Trazabilidad y falta de dataset local','Calibrar pesos; no afirmar optimalidad'],['ADR-04 Aislamiento por propiedad','Marketplace actual, tres roles','No multitenencia implícita'],['ADR-05 Asistencia opcional','A22 advierte sobre proveedores inventados','LLM no ejecuta decisiones ni sustituye catálogo'],['ADR-06 Pagos desacoplados','Modelo comercial aún no aprobado','Núcleo funciona sin checkout ni suscripción']]),sec('Observabilidad propuesta','Medir latencia del ranking, uso de fallback, número de ofertas, vencimientos y errores por acción. Usar IDs de correlación; no guardar contraseñas, tokens, direcciones ni texto libre sensible en logs. Las métricas de producto son distintas de latencia HTTP.'),sec('Gobernanza del cambio','Cambio -> ADR -> historia -> prueba -> implementación -> QA -> evidencia -> aceptación. Un artículo inspira una hipótesis; el Product Owner decide su incorporación y el equipo la valida. Preservar versiones de reglas y migraciones.')),
page('Riesgos y responsabilidades de seguridad',table('Riesgo','Riesgo|Control|Prueba'.split('|'),[['Acceso ajeno','Servidor comprueba rol, propiedad y estado','Pruebas 403 y respuesta sin dirección'],['Suplantación de habilitación','verify solo admin; no mass assignment','Enviar verified/role en formularios públicos'],['Sesión suspendida','Revocar tokens y comprobar is_active','Token antiguo no vuelve a servir'],['Competencia por oferta','Bloqueos y restricciones','Dos clientes DB aceptan al mismo tiempo'],['Inyección y contenido de anuncio','Validación, escape React, URL restringida','XSS, MIME incorrecto, URL javascript'],['Caída del motor','Fallback y reglas versionadas','Timeout, score inválido y versión distinta'],['Sesgo de reputación','Medición, transparencia y revisión propuesta','Comparar exposición de perfiles nuevos']]),sec('Alcance de protección','No se declara seguridad completa ni cumplimiento certificado. El control de verificación profesional todavía necesita criterios operativos y evidencia. A12, A13 y A18 fundamentan la necesidad de gobernanza; no reemplazan un análisis de amenazas del sistema concreto.'),sec('Fuentes',REFS+' Código: Permissions.php, ApiToken.php, Marketplace.php, Matching.php y python/api/app.py.'))])

doc('07-Diseno-tecnico-integracion-servidor-y-pruebas.pdf','Diseño técnico: integración, servidor y calidad',[
page('Contratos e infraestructura',sec('Control',CONTROL),table('API actual',['Ruta','Acceso','Resultado'],[['GET /api/health','Público','status y nombre servicio'],['POST /api/register','Público, limitado','201, sin sesión automática'],['POST /api/login','Público, limitado','token y actor'],['POST /api/logout','Bearer','Revocación'],['GET /api/state','Bearer','Datos filtrados y permisos'],['POST /api/actions/{action}','Bearer + permisos','Mutación validada'],['POST /match; GET /health','FastAPI interno','Ranking/version y salud']]),sec('Entorno actual','Compose referencia postgres:16-alpine, API, matching y web; expone web en 5173. PHP usa timeout 2 s hacia Python; frontend espera hasta 12 s. Autenticación limitada 10/min y rutas con token 120/min. Revisar esos límites al diseñar prueba de carga, sin desactivarlos en producción para aprobar una métrica.'),sec('Servidor: decisión informada','Ningún artículo del corpus dimensiona esta aplicación React/Laravel/FastAPI ni justifica un proveedor concreto. Se propone QA con contenedores en una máquina controlada y BD persistente; medir CPU, memoria, I/O, pool de conexiones y latencia. El tamaño final se decide por ensayo y costo, no copiando el hardware de HomeServe o métricas de Reparo.'),sec('Alternativas','Host único: menor complejidad y punto único de fallo. Aplicación y BD separadas: mejor aislamiento, mayor operación. BD administrada: respaldos y servicio externo con costo y dependencia. Elegir mediante ADR, presupuesto y restauración verificada; no contratar infraestructura en esta tarea.')),
page('Plan transversal de pruebas',table('Nivel',['Nivel','Prueba','Oráculo','Evidencia'],[['Unidad','Ranking, validación y estado','Fixture y límites temporales','Log, commit, dataset'],['Integración','Laravel + PostgreSQL + FastAPI','Contrato y persistencia','HTTP, consultas y fallos inyectados'],['Sistema','Tres roles en navegador','Casos de I08','Capturas y IDs sintéticos'],['Seguridad','Rol, propiedad, sesión y entrada','Matriz de permisos','Negativas y no modificación'],['Operación','Worker, backup y rollback','Plazos e integridad','Log de restauración y smoke'],['Aceptación','Tareas con participantes locales','Criterio acordado','Acta, observaciones y pendientes']]),sec('Pruebas existentes','Frontend: npm test y npm run build desde frontend/web. Laravel: php artisan test desde backend/api, sobre SQLite de pruebas. Python: python -m pytest -q desde python/api. No ejecutar semillas ni refresh/fresh sobre datos reales. Los 30/19 resultados del 28/09 son un antecedente, no certificación global.'),sec('Vínculo con plan anterior','El plan maestro anterior y los originales se conservan en historico/v1-previa-2026-09-29 y plan-de-pruebas/. Las matrices RF/RNF originales permanecen para trazabilidad. Este diseño y la iteración 10 complementan el plan; no convierten automáticamente los 33 RF y 14 RNF en aprobados.'),sec('Registro obligatorio','Caso, requisito, riesgo, precondiciones, pasos, esperado, observado, entorno, commit, fecha, ejecutor, estado y evidencia. Defecto: ID, severidad, reproducción, corrección, retest y regresión. TDD registra RED/GREEN si se ejecuta; no reconstruir falsamente un RED histórico.')),
page('Referencias normativas y método',sec('Uso responsable','Las normas orientan la organización y verificación. No se compró ni auditó aquí todo el texto normativo; se consultaron fichas oficiales el 29/09/2026. No se asignan números de cláusula sin cotejo ni se declara certificación ISO.'),table('Marco de referencia',['Documento','Aplicación'],[[x[0],x[1]] for x in STANDARDS]),sec('Cambio respecto de la documentación anterior','La ficha oficial de ISO presenta ISO 9001:2026 como edición publicada en septiembre de 2026. La referencia a 2015 queda histórica; la adopción formal de la nueva edición debe acordarse con el docente. ISO 25010:2023 se usa para calidad de producto; no mezclar automáticamente su estructura con las ocho características de 2011.'),sec('Fuentes oficiales','\n'.join(x[0]+': '+x[2] for x in STANDARDS))),
page('Puertas de despliegue y reversión',sec('Pipeline esperado','Checkout de commit -> instalar dependencias bloqueadas -> tests de los tres módulos -> build -> imagen identificada -> QA -> migración controlada -> smoke con worker -> evidencia -> aprobación. .gitlab-ci.yml delega en plantilla externa: su existencia no demuestra ejecución ni despliegue exitoso.'),sec('Antes de QA','Configurar secretos fuera de Git, APP_DEBUG=false, red privada para BD/Python, salud y volúmenes persistentes. Distinguir liveness de readiness: /api/health actual no comprueba todos los servicios. Comprobar configuración de DB y no asumir entorno por nombre de archivo.'),sec('Antes de producción','TLS, autorización, restauración, observabilidad, política de retención, responsables de incidentes y prueba de carga aprobados. Exigir prueba real de 200 concurrentes si se mantiene RNF-02. El 99% mensual solo se valida en una ventana mensual observada; una prueba corta no basta.'),sec('Rollback','Conservar imagen anterior; preferir migraciones compatibles hacia adelante. Respaldar antes de cambio y ensayar restauración en QA. No usar down destructivo como reversión automática. Si hay pagos, detener nuevas operaciones y conciliar eventos antes de reintentar.'),sec('Registro de entrega','Nombre de versión, commit/digest, requisitos incluidos, exclusiones, migraciones, pruebas, defectos abiertos, plan de reversión, responsable y aceptación. Campos sin evidencia se marcan pendientes. No hay despliegue productivo ejecutado por generar este PDF.'))])

for it in ITER:
 n=it['n'];prefix=f'I{n:02}'
 pages=[page('Objetivo, alcance y preparación',sec('Control',CONTROL),sec('Objetivo',it['goal']),sec('Situación observada',it['state']),sec('Dependencias',it['deps']),table('Historias de usuario',['ID','Historia'],it['stories']),sec('Trazabilidad y antecedentes',it['refs']+' '+REFS),sec('Incluye',it['data']),sec('No incluye / riesgo principal',it['risk']),sec('Entrada a desarrollo','Product Owner aprueba alcance y criterio; equipo dispone de entorno QA, datos sintéticos y dependencias. Definir capacidad del sprint antes de comprometer fechas. Si esta iteración es propuesta, la documentación no significa aprobación de implementación.')),
 page('Implementación por capas',sec('Frontend',it['fe']),sec('Backend Laravel',it['be']),sec('Python',it['py']),sec('Base de datos y contrato',it['data']),sec('Secuencia para desarrollar','1. Reproducir situación actual y anotar commit. 2. Escribir caso negativo o límite que falle. 3. Implementar cambio mínimo en capa responsable. 4. Verificar respuesta y persistencia. 5. Refactorizar sin cambiar contrato. 6. Ejecutar regresión y revisar con otro integrante. 7. Actualizar evidencia y desplegar QA.'),sec('Errores y seguridad','La API vuelve a validar permisos y datos aunque la UI bloquee una acción. No usar localStorage como control real. Mantener mensajes comprensibles, datos de prueba sintéticos y secretos fuera de capturas/logs. No registrar un cambio como completo si solo existe en el frontend.')),
 page('Pruebas, entrega y finalización',table('Casos de aceptación',['ID','Procedimiento','Resultado esperado'],it['tests']),sec('Ejecución TDD','RED: ejecutar el caso que demuestra la falta o fallo, conservar resultado. GREEN: implementar y repetir. REFACTOR: limpiar código y ejecutar regresión pertinente. Para funciones ya implementadas, registrar prueba de caracterización y no inventar una fase RED anterior.'),sec('Despliegue de la iteración',it['deploy']),sec('Criterios de salida','Historias aceptadas, permisos negativos aprobados, contrato y diccionario actualizados, pruebas pertinentes sin fallos y QA verificable. Guardar build/commit, entorno, caso y observado. Riesgos pendientes con responsable por asignar; ninguna firma ni aceptación simulada.'),sec('Carpeta de evidencia','evidencias/v2/'+prefix+'/ contiene README de estado. En la ejecución se añadirán logs, casos, incidentes, retest, acta de revisión y registro de despliegue. Actualmente el estado es PLANIFICADO / NO EJECUTADO como iteración. No confundir pruebas previas con cierre de sprint.'))]
 if n==10:
  pages.append(page('Catálogo de calidad y discrepancias',table('Pendientes de alineación',['ID','Conflicto o riesgo','Resolución requerida'],[['D-01','RF-09: antigüedad; código: ID en último desempate','Aprobar regla y fixture'],['D-02','RF-24: cierre sin calificar; código conserva completed','Definir cierre de negocio sin puntuación inventada'],['D-03','RF-04 rango referencial; código usa tarifa de visita','Actualizar alcance o implementar rango con datos'],['D-04','RF-05/20 agenda y reprogramación ausentes','Mantener fuera del núcleo o nueva historia'],['D-05','RF-29 reintentos externos no implementados','Distinguir eventos internos y canal externo'],['D-06','RNF-12 >=70% ambiguo','Definir líneas, ramas o casos y medir'],['D-07','RNF-01 3 s vs referencia 5 s','Fijar operación, percentil y carga'],['D-08','RF-03/10/11/21/26 no cubiertos completamente','No cerrar fotos, subespecialidad, estimación, múltiples técnicos y apelación']]),sec('Pruebas de rendimiento propuestas','Baseline: 20 usuarios; escalamiento hasta 200 concurrentes si se mantiene requisito. Propuesta de ensayo de 15 min estables con mezcla 60% lectura, 20% creación, 20% acciones, a ajustar para no crear datos incoherentes. Registrar tasa de llegada, p50/p95/p99, errores, CPU/RAM/BD y saturación. No atribuir saturación del pool a falta de técnicos.'),sec('Liberación','Bloquear si existe acceso ajeno, pérdida de integridad, doble asignación o migración insegura. Defectos menores requieren aceptación explícita y fecha. La ausencia de medición nunca se registra como aprobado.')))
 doc(f'{n+7:02}-Iteracion-{n:02}-{it["slug"]}.pdf',f'Iteración {n}: {it["title"]}',pages)

# Render consistente, texto seleccionable y fuentes embebidas.
pdfmetrics.registerFont(TTFont('TY',r'C:/Windows/Fonts/arial.ttf'))
pdfmetrics.registerFont(TTFont('TY-Bold',r'C:/Windows/Fonts/arialbd.ttf'))
INK=colors.HexColor('#183c40');GOLD=colors.HexColor('#a7803c')
styles={
 'body':ParagraphStyle('body',fontName='TY',fontSize=10,leading=14,spaceAfter=8,textColor=colors.HexColor('#25363b')),
 'h1':ParagraphStyle('h1',fontName='TY-Bold',fontSize=22,leading=27,spaceAfter=16,textColor=INK),
 'h2':ParagraphStyle('h2',fontName='TY-Bold',fontSize=11,leading=15,spaceBefore=8,spaceAfter=5,textColor=INK,keepWithNext=True),
 'cell':ParagraphStyle('cell',fontName='TY',fontSize=8.6,leading=11.5,spaceAfter=0),
 'th':ParagraphStyle('th',fontName='TY-Bold',fontSize=8.7,leading=11.5,textColor=colors.white),
 'small':ParagraphStyle('small',fontName='TY',fontSize=8,leading=11,textColor=colors.HexColor('#607275'))}
def clean(s):return str(s).replace('\u2011','-').replace('\u2013','-').replace('\u2014','-').replace('\u2265','>=').replace('\u2264','<=')
def P(t,sty='body'):return Paragraph(escape(clean(t)).replace('\n','<br/>'),styles[sty])
def footer(canvas,d):
 canvas.setStrokeColor(GOLD);canvas.line(44,44,551,44)
 canvas.setFont('TY',8);canvas.setFillColor(INK);canvas.drawString(44,30,'TÉCNICOYA HUANCAYO | Documentación v2.0 | '+DATE)
 canvas.drawRightString(551,30,str(d.page))
 canvas.setFont('TY-Bold',8);canvas.drawString(44,809,'INGENIERÍA DE SOFTWARE / PRUEBAS Y CALIDAD')
def build(d,path):
 flow=[]
 for i,pg in enumerate(d['pages']):
  if i:flow.append(PageBreak())
  flow += [P(d['title'],'small'),Spacer(1,6),P(pg['title'],'h1')]
  for s in pg['sections']:
   flow.append(P(s['title'],'h2'))
   if 'text' in s:flow.append(P(s['text']))
   else:
    assert all(len(row)==len(s['heads']) for row in s['rows']), (d['name'],s['title'])
    count=len(s['heads']); widths={2:[150,357],3:[110,181,216],4:[100,130,145,132]}.get(count,[507/count]*count)
    if s['heads']==['Campo / tipo','Nulo','Regla / significado']:widths=[142,40,325]
    rows=[[P(x,'th') for x in s['heads']]]+[[P(x,'cell') for x in row] for row in s['rows']]
    t=Table(rows,colWidths=widths,repeatRows=1,hAlign='LEFT')
    t.setStyle(TableStyle([('BACKGROUND',(0,0),(-1,0),INK),('ROWBACKGROUNDS',(0,1),(-1,-1),[colors.HexColor('#f0f5f4'),colors.white]),('VALIGN',(0,0),(-1,-1),'TOP'),('LEFTPADDING',(0,0),(-1,-1),8),('RIGHTPADDING',(0,0),(-1,-1),8),('TOPPADDING',(0,0),(-1,-1),7),('BOTTOMPADDING',(0,0),(-1,-1),7),('LINEBELOW',(0,0),(-1,-1),.3,colors.HexColor('#dce5e3'))]))
    flow.extend([t,Spacer(1,8)])
 SimpleDocTemplate(str(path),pagesize=(595.28,841.89),leftMargin=44,rightMargin=44,topMargin=52,bottomMargin=59,title=d['title'],author='Equipo TécnicoYa Huancayo',pageCompression=1).build(flow,onFirstPage=footer,onLaterPages=footer)

def main():
 assert len(docs)==17
 stage=ROOT/'tmp/pdfs/v2-final';stage.mkdir(parents=True,exist_ok=True)
 for d in docs:
  build(d,stage/d['name']);d['page_count']=len(PdfReader(stage/d['name']).pages)
 (EDIT/'contenido.json').write_text(json.dumps(docs,ensure_ascii=False,indent=2),encoding='utf-8')
 (EDIT/'articulos.json').write_text(json.dumps(articles,ensure_ascii=False,indent=2),encoding='utf-8')
 (EDIT/'diccionario-fisico.json').write_text(json.dumps(schema,ensure_ascii=False,indent=2),encoding='utf-8')
 print(json.dumps([{'name':d['name'],'pages':d['page_count'],'planned':len(d['pages'])} for d in docs],ensure_ascii=False,indent=2))
if __name__=='__main__':main()
