"""Expediente académico reproducible. Los originales y evidencias no se modifican."""
from pathlib import Path
import csv, json, hashlib
from xml.sax.saxutils import escape
from reportlab.platypus import SimpleDocTemplate, Paragraph, Spacer, PageBreak, Table, TableStyle, KeepTogether
from reportlab.lib.styles import getSampleStyleSheet, ParagraphStyle
from reportlab.lib import colors
from reportlab.pdfbase import pdfmetrics
from reportlab.pdfbase.ttfonts import TTFont
from reportlab.graphics.shapes import Drawing, Rect, String, Line, Polygon
from pypdf import PdfReader

ROOT=Path(__file__).resolve().parents[1]
OUT=ROOT/'docs/documentacion'
EDIT=OUT/'editables';EDIT.mkdir(exist_ok=True)
DATE='22/09/2026'
docs=[]
def page(title,*sections):return {'title':title,'sections':list(sections)}
def sec(title,text):return {'title':title,'text':text}
def table(title,heads,rows):return {'title':title,'heads':heads,'rows':rows}
def doc(name,title,pages):docs.append({'name':name,'title':title,'pages':pages})
def source(name):
    with (OUT/'trazabilidad'/name).open(encoding='utf-8-sig',newline='') as f:return list(csv.reader(f))
rf=source('requisitos-funcionales.csv');rnf=source('requisitos-no-funcionales.csv');art=source('estado-del-arte.csv');dec=source('decisiones.csv')
refs='Base documental: fuentes/proyecto-final.pdf; fuentes/plan-de-pruebas-original.pdf; fuentes/ejemplos-practica.docx; fuentes/estado-del-arte-original.pdf. Código: rutas relativas a la raíz del repositorio. Fuentes conservadas con SHA-256 en fuentes/manifest.json.'
status='Versión 1.0 del expediente organizado. Propuesta para revisión académica; no acredita certificación ISO, aceptación firmada ni despliegue productivo. Se distingue código observado, prueba ejecutada, propuesta y pendiente.'

doc('01-Plan-maestro-de-pruebas.pdf','Plan maestro de pruebas',[
page('Control y alcance',sec('Propósito','Verificar que TécnicoYa conecta a clientes con técnicos verificados, protege sus datos y conserva la trazabilidad de cada servicio. Este plan organiza las pruebas del MVP y mantiene los 33 RF y 14 RNF del plan original sin declarar aprobaciones globales.'),sec('Control documental',status+' Este documento es la entrada de la colección. El plan original y el consolidado v1.1 previo permanecen en fuentes y plan-de-pruebas como antecedentes; una discrepancia se registra y resuelve antes de ejecutar el caso afectado.'),table('Alcance y exclusiones',['Incluye','No demuestra por sí solo'],[['React, Laravel, FastAPI y persistencia PostgreSQL','Las pruebas de SQLite no validan concurrencia PostgreSQL.'],['Cliente, técnico y administrador; acciones autorizadas y negativas','La demo no representa cuentas ni servicios reales.'],['Reglas de matching, plazos y estados del servicio','El frontend no reemplaza los controles de API.'],['Accesibilidad, seguridad, rendimiento y despliegue QA','La compilación no prueba carga, disponibilidad mensual o producción.']]),sec('Responsables','Se conserva la RACI propuesta del ejemplo: Delgado, Mayhuasca y Pimentel integran el equipo; el docente revisa la entrega. La aprobación nominal, el Product Owner y Scrum Master se formalizan antes del ciclo. No se incorporan firmas ficticias.')),
page('Estrategia y diseño de casos',table('Niveles y entornos',['Nivel','Qué comprobar','Evidencia'],[['Unidad','Ranking, desempate, estados y límites temporales','Log, datos, resultado esperado y build'],['Integración','Laravel con PostgreSQL y FastAPI reales; fallback','Respuestas HTTP y persistencia; logs sin secretos'],['Sistema','Solicitud a calificación por roles en navegador','Pasos, capturas y estado final'],['Aceptación','Tareas de usuarios y criterios de negocio','Resultado por criterio y revisión responsable']]),sec('Técnicas','Usar particiones para datos válidos e inválidos; valores límite a 10 min, 24 h y 48 h; tablas de decisión para elegibilidad; transiciones para el ciclo del servicio; y pruebas negativas por rol y propiedad. La aprobación parcial no cierra un RF con variantes pendientes.'),sec('Datos y oráculos','Crear cuentas sintéticas en dominios de prueba; técnicos no verificados, no disponibles y de otra zona; cuatro candidatos elegibles; empate de puntaje; ausencia de oferta; y servicios finalizados junto al límite de calificación. Usar reloj controlable. Comparar el ranking de JS, PHP y Python contra domain/matching-fixture.json.'),sec('Registro mínimo de un caso','ID CT/CNF, RF/RNF, riesgo, precondiciones, datos, pasos, esperado, observado, build, entorno, ejecutor, estado y enlace a evidencia. Si falla, registrar INC, severidad, corrección, retest y regresión. Nunca reemplazar el log fallido por el exitoso.')),
page('Casos prioritarios y ejecución',table('Especificaciones iniciales',['Caso','Procedimiento','Esperado'],[['CT-13-LIM','Crear solicitud con cuatro candidatos elegibles.','Como máximo tres ofertas pendientes simultáneas.'],['CT-16-LIM','Intentar aceptar antes, en y después del vencimiento de 10 min.','Antes es admisible; en el límite o después se rechaza.'],['CT-17-INT','Dejar vencer ofertas y ejecutar procesador de plazos.','Reasignación sin repetir candidato ni reiniciar la ventana global.'],['CT-23-LIM','Calificar a las 48 h exactas y repetir una calificación.','Rechazo al vencer y ante duplicado; promedio consistente.'],['CT-33-NEG','Cliente B intenta leer o cancelar una solicitud de A.','Acceso denegado; no divulgar dirección ni cambiar estado.'],['CNF-13-QA','Instalar el build y ejecutar smoke con PostgreSQL y Python.','Servicios saludables y flujo sintético persistido.']]),sec('Pruebas existentes','Frontend: src/domain/marketplace.test.js, src/forms.test.jsx, src/VideoExperience.test.jsx y src/scroll/scroll.test.jsx bajo frontend/web. Laravel: backend/api/tests/Feature/MarketplaceTest.php. Python: python/api/test_matching.py. Ejecutar respectivamente npm test, php artisan test y python -m pytest -q desde cada módulo.'),sec('Resultados documentados','La revisión del 22/09/2026 registra 14 pruebas frontend aprobadas y una suite fallida por auth.css ausente; restauración de estilos; retest de 15 pruebas aprobadas y build correcto. Evidencias en evidencias/revision-2026-09-22. No hay nueva ejecución adjunta de Laravel, Python, carga o despliegue. No se calcula cobertura a partir del número de pruebas.')),
page('Criterios de calidad y cierre',sec('Entrada','Build identificado, requisitos y datos aprobados, entorno disponible, cuentas por rol y smoke inicial. Los casos con reglas ambiguas se bloquean con su DP correspondiente; los demás pueden continuar.'),sec('Salida y suspensión','Propuesta: todos los casos críticos del alcance ejecutados y aprobados, cero defectos críticos o altos abiertos, riesgos residuales aceptados y trazabilidad completa. Suspender ante pérdida de datos, exposición de secretos o entorno inestable; reanudar con causa corregida y smoke repetido. Estos criterios requieren aprobación académica.'),sec('No funcionales','Conservar los umbrales documentados: matching de 3 s, 200 usuarios concurrentes, SUS de 70, disponibilidad mensual de 99% y 70% de automatización en módulos críticos con denominador pendiente. Resolver 3 s frente a 5 s y especificar percentil, carga y dataset. Complementar con WCAG 2.2 AA y controles ASVS seleccionados; no declarar conformidad sin evaluación.'),sec('Normas','ISO 9001 orienta control, responsabilidad y mejora; ISO/IEC 25010 orienta calidad del producto; ISO/IEC/IEEE 29119 orienta procesos, documentos y técnicas. Mantener la discrepancia de ediciones 25010:2011/2023 visible. Referencias oficiales: iso.org/standard/78176.html, iso.org/standard/79428.html, iso.org/standard/79429.html, w3.org/TR/WCAG22/ y owasp.org/projects/asvs.'),sec('Entregables y mantenimiento','Actualizar este plan al cambiar un requisito, contrato, riesgo, regla o entorno. Adjuntar resultados al informe del Sprint y conservar los originales. El catálogo completo está en el PDF 03 y CSV de trazabilidad; el procedimiento de liberación está en el PDF 12.'),sec('Fuentes',refs))])

objectives=[['OBJ-01','Registrar una necesidad comprensible','Solicitud con rubro, zona, dirección y descripción válida; revisar antes de enviar.','RF-01/02; RNF-05'],['OBJ-02','Proponer técnicos adecuados','Excluir no elegibles y producir ranking reproducible con pesos y desempate.','RF-06 a 14'],['OBJ-03','Controlar aceptación y continuidad','Hasta tres ofertas, expiración de 10 min y búsqueda hasta 24 h.','RF-13 a 19'],['OBJ-04','Trazar ejecución y reputación','Confirmación, inicio, cierre y calificación válida dentro de 48 h.','RF-18/19/22 a 25'],['OBJ-05','Proteger acceso y supervisar','Denegar acciones ajenas y habilitar técnicos solo por administrador.','RF-07/28/30/31/33'],['OBJ-06','Ofrecer experiencia verificable','Evaluar accesibilidad, usabilidad y tiempos con las métricas acordadas.','RNF-01 a 05'],['OBJ-07','Entregar incrementos reproducibles','Migraciones, pruebas, documentación y despliegue QA evidenciados.','RNF-11 a 14']]
doc('02-Producto-y-alcance-MVP.pdf','Definición del producto y alcance del MVP',[
page('Propósito y principio rector',sec('Contexto','TécnicoYa Huancayo es un marketplace de dos lados para hogares y MYPES, con técnicos independientes de cómputo, refrigeración comercial y electricidad. Sustituye la búsqueda informal por solicitudes, selección, respuesta y trazabilidad. No es un taller que presta directamente todos los servicios.'),sec('Principio rector','Una necesidad del cliente debe avanzar por estados comprensibles, con un técnico elegible, decisiones verificables y protección de datos. Toda función debe vincularse con un objetivo, requisito y prueba; una animación o un dashboard no sustituyen el flujo de negocio.'),sec('Usuarios y administradores','Cliente: solicita, confirma y califica. Técnico: administra disponibilidad y atiende ofertas según perfil y zona. Administrador del marketplace: verifica perfiles, supervisa solicitudes y cobertura. Operador de plataforma: despliegue, backups y observabilidad; es responsabilidad operativa propuesta, no un cuarto rol funcional ya implementado.'),sec('Límites del MVP','Incluye el ciclo básico conectado a Laravel, ranking FastAPI con fallback, tres roles y administración básica. Diferir explícitamente fotografías, agenda compleja, varios técnicos por servicio, apelaciones, pagos y canales externos hasta priorizarlos. No eliminar sus RF del plan. Excluye inicialmente aplicación móvil nativa, pasarela de pagos, nómina y múltiples organizaciones aisladas.'),sec('Uso como contexto para IA','Leer este documento antes del backlog. No inventar reglas, terceros, permisos o metas. Consultar domain/rules.json y los contratos. Si hay conflicto con una fuente, abrir una decisión DP; no alterar el alcance por inferencia. Todos los objetivos son compromisos propuestos a implementar y validar, no resultados logrados.')),
page('Objetivos específicos verificables',table('Objetivos y criterios',['ID','Objetivo','Criterio verificable','Relación'],objectives),sec('Objetivo general','Facilitar la conexión trazable de hogares y MYPES con técnicos independientes adecuados, mediante una plataforma web que permita solicitar, coordinar, supervisar y evaluar servicios en Huancayo.'),sec('Cómo cerrar un objetivo','El Product Owner confirma el criterio y alcance; Developers implementan; QA adjunta evidencia; el equipo revisa el resultado. Para OBJ-06, ejecutar los ensayos RNF; para OBJ-07, disponer de evidencia real de QA. Una implementación parcial conserva el objetivo abierto.')),
page('Reglas y finalización',sec('Reglas clave','Respuesta: 10 min. Ofertas: máximo 3. Búsqueda pendiente: 24 h desde creación. Calificación: 48 h desde finalización. Pesos 35/20/30/15 para cercanía, tarifa, historial y experiencia. Desempate por mejor calificación; identificador establece orden final estable. Las cifras deben ser idénticas en los tres lenguajes.'),sec('Modelo conceptual resumido','Usuario tiene un rol y puede tener perfil técnico; cliente registra solicitudes; solicitud genera ofertas a técnicos; una aceptación conduce a propuesta y posterior confirmación. La solicitud conserva eventos, finalización y puntuación. El técnico acumula reputación. Sesiones pertenecen al usuario. Véase PDF 05.'),sec('Flujo principal','Registrar cuenta, autenticar, describir falla, ordenar candidatos, notificar internamente, aceptar oferta, confirmar servicio, iniciar, finalizar y calificar. Las alternativas incluyen rechazo, vencimiento, ausencia de disponibilidad y cancelación autorizada.'),sec('Riesgos','Reglas ambiguas, concurrencia, exposición de direcciones, resultados de demo confundidos con producción, dependencia de servicios, datos insuficientes y sobrecarga académica. Mitigar con DP, transacciones y pruebas PostgreSQL, matriz de permisos, rótulos de entorno y backlog priorizado.'),sec('TDD y Definition of Done','Para nueva lógica, escribir prueba que falla, implementar mínimo y refactorizar. Finalizar una historia solo con criterios cubiertos, revisión, regresión, contratos y datos coherentes, documentación y evidencia. El código previo no se declara desarrollado con TDD sin historial que lo demuestre.'),sec('Fuentes',refs))])

stories=[['HU-01','Cliente','Registrar y confirmar una falla','Datos válidos crean una solicitud; faltantes bloquean y conservan campos.','OBJ-01 / RF-01/02'],['HU-02','Cliente','Conocer al técnico propuesto','Comparar perfil y tarifa de visita; confirmar antes del inicio.','OBJ-02/04 / RF-18'],['HU-03','Técnico','Responder ofertas','Aceptar o rechazar antes del vencimiento; no aceptar oferta ajena.','OBJ-03 / RF-16/17'],['HU-04','Técnico','Gestionar disponibilidad','Solo perfil verificado puede quedar disponible; reserva evita doble atención.','OBJ-02 / RF-07/10'],['HU-05','Cliente','Calificar un servicio finalizado','Una nota válida dentro de 48 h; rechazar duplicación o nota ajena.','OBJ-04 / RF-23/25'],['HU-06','Administrador','Verificar y supervisar','Cliente no habilita técnicos; listar solicitudes y cobertura por rol.','OBJ-05 / RF-07/30/31'],['HU-07','Usuario','Acceder a mi cuenta','Credenciales válidas permiten sesión; logout revoca token.','OBJ-05 / RF-28/33'],['HU-08','Operador','Instalar y recuperar una versión','Build identificado, migración verificada, smoke y rollback documentados.','OBJ-07 / RNF-13/14']]
reqpages=[page('Requisitos e historias',sec('Clasificación','RF describe una conducta: registrar o confirmar. RNF expresa una calidad medible: tiempo, seguridad o accesibilidad. Regla de negocio impone una condición del dominio: 10 minutos. Restricción fija una elección: monorepo React/Laravel/FastAPI. No mezclar estos cuatro conceptos.'),sec('Línea base','Se preservan los 33 RF y 14 RNF del documento de ejemplos. Sus condiciones se reproducen en las páginas siguientes para revisión; no se afirma ejecución completa. La propuesta MVP del PDF 02 debe ratificarse sin borrar requisitos diferidos.'),sec('Casos de uso principales','CU-01 Registro y acceso. CU-02 Solicitud y matching. CU-03 Respuesta de técnico y confirmación de cliente. CU-04 Ejecución y cierre. CU-05 Calificación. CU-06 Verificación y supervisión. En cada CU documentar actor, disparador, precondiciones, curso normal, alternativas, permisos y postcondiciones.'),sec('Especificación ejemplo CU-03','Precondición: oferta pendiente no vencida para técnico habilitado. Técnico acepta; el servidor valida y reserva; solicitud pasa a propuesta; cliente confirma. Alternativas: 10 min vencidos, oferta ajena, otro técnico ya aceptó, cancelación o indisponibilidad. Postcondición: un único técnico confirmado o rechazo explícito, sin cambio parcial.'),sec('Estándar de requisitos','Usar ISO/IEC/IEEE 29148 como guía de claridad y verificabilidad. Catálogo oficial: https://www.iso.org/standard/72089.html. No asignar aprobación a un requisito cuyo criterio aún dependa de una decisión.'))]
for k in range(0,len(stories),4):reqpages.append(page('Historias de usuario',table('Historias propuestas',['ID y actor','Necesidad','Criterio de aceptación','Trazabilidad'],[[r[0]+' / '+r[1],r[2],r[3],r[4]] for r in stories[k:k+4]]),sec('Formato de aceptación','Especificar Dado un estado y usuario, Cuando se realiza una acción, Entonces se obtiene resultado observable y no cambia información ajena. Añadir variante negativa y de frontera. Estimaciones y prioridad final se acuerdan en refinamiento.')))
for k in range(1,len(rf),7):reqpages.append(page('Catálogo de requisitos funcionales',table('Condiciones conservadas del ejemplo',['Requisito y prioridad','Condición de prueba','Caso'],[[r[0],r[1],r[2]] for r in rf[k:k+7]]),sec('Estado','Especificaciones de la fuente; ejecución integral pendiente. El código existente aporta evidencia parcial, indicada en el PDF 01. Cada caso debe detallar datos, pasos, esperado, observado, entorno y build.')))
for k in range(1,len(rnf),5):reqpages.append(page('Catálogo de requisitos no funcionales',table('Metas y decisiones pendientes',['RNF','Criterio de fuente','Verificación y decisión'],[[r[0],r[1],r[3]] for r in rnf[k:k+5]]),sec('Control','No reducir umbrales para ajustarlos al resultado. Acordar método de medición y registrar desviaciones. '+refs)))
doc('03-Requisitos-e-historias-de-usuario.pdf','Requisitos e historias de usuario',reqpages)

doc('04-Procesos-y-procedimientos-BPMN.pdf','Procesos de negocio y procedimientos',[
page('Proceso actual y propuesto',sec('AS IS','Cliente busca recomendaciones o avisos; contacta técnicos por canales dispersos; explica la falla; acuerda informalmente visita y precio; recibe atención y emite opinión fuera de un registro común. Los problemas documentados son comparación limitada, disponibilidad incierta y falta de trazabilidad.'),sec('TO BE','Cliente registra necesidad; sistema valida y busca candidatos; técnicos reciben ofertas; uno acepta; cliente confirma; técnico ejecuta y finaliza; cliente califica. El administrador interviene en habilitación y supervisión. El operador mantiene la disponibilidad del servicio tecnológico.'),sec('Alcance del proceso','Inicio: necesidad de servicio del cliente. Fin: servicio calificado o finalizado sin nota, cancelado o sin asignación. Cómputo, refrigeración y electricidad usan el mismo ciclo; diagnóstico y reparación física son responsabilidad del técnico, fuera de la automatización de la plataforma.'),sec('Procedimiento y Bizagi','El archivo editables/proceso-principal.bpmn representa el camino principal para revisión e importación. Es BPMN 2.0 XML, no archivo nativo .bpm validado en Bizagi. Completar y validar en el modelador los eventos temporales, mensajes, excepciones y subprocesos antes de aprobar el TO BE completo. El procedimiento textual de las páginas siguientes es la referencia de esos recorridos.'),{'title':'Flujo principal','flow':True}),
page('Procedimiento operativo',table('Pasos y responsabilidades',['Paso','Responsable','Entrada y acción','Salida'],[['1','Cliente','Acceder y completar rubro, zona, dirección y falla','Solicitud válida o errores corregibles'],['2','Sistema','Aplicar elegibilidad y ranking','Candidatos ordenados'],['3','Sistema','Generar hasta tres ofertas pendientes','Vencimiento individual de 10 min'],['4','Técnico','Aceptar o rechazar dentro del plazo','Propuesta o búsqueda siguiente'],['5','Cliente','Revisar técnico y confirmar','Servicio confirmado'],['6','Técnico','Iniciar y finalizar atención','Estado y eventos persistidos'],['7','Cliente','Calificar dentro de 48 h','Puntuación e historial actualizado'],['8','Administrador','Revisar habilitación y cobertura','Decisión autorizada y supervisión']]),sec('Registros','Solicitud, ofertas, técnico seleccionado, tarifa acordada, eventos y calificación. Registrar tiempos del servidor. Un evento de interfaz o clic no es evidencia suficiente de persistencia: comprobar API y base de datos.')),
page('Excepciones y control del proceso',sec('Sin respuesta o sin candidatos','A los 10 min vence la oferta. Reasignar a candidatos elegibles no notificados previamente. Sin candidatos, conservar pendiente hasta 24 h desde la creación. No reiniciar esa ventana en cada ronda. La búsqueda ampliada por distancia GPS no debe dibujarse como implementada.'),sec('Aceptaciones concurrentes','Validar oferta y disponibilidad dentro de transacción. Solo un técnico queda asociado; las otras ofertas se cancelan. Ensayar carrera de dos aceptaciones en PostgreSQL; los tests SQLite no cierran ese riesgo.'),sec('Sin calificación','Pasadas 48 h impedir nueva nota y no inventar puntuación cero. El comportamiento de cierre y estado final debe conciliarse con RF-24; actualmente se conserva finalización y se rechaza calificación tardía.'),sec('Gestión documental del proceso','Cada procedimiento aprobado tiene código, versión, responsable, entradas, actividades, decisiones, salida, riesgos y evidencia. ISO 9001 orienta ese control; BPMN expresa visualmente el flujo. Registrar cambios del proceso y su impacto en RF, pruebas y formación de usuarios.'),sec('Fuentes',refs))])

doc('05-Modelo-de-datos-y-reglas.pdf','Modelo de datos y reglas de negocio',[
page('Modelo conceptual y relaciones',table('Entidades y cardinalidades',['Entidad','Relación conceptual','Observación'],[['Usuario','1 usuario tiene 0..1 perfil técnico y 0..N sesiones','Roles: cliente, técnico y administrador'],['Cliente','1 cliente registra 0..N solicitudes','Cada solicitud pertenece a un cliente'],['Técnico','1 técnico recibe 0..N ofertas','Perfil con especialidades y cobertura'],['Solicitud','1 solicitud genera 0..N ofertas','0..1 técnico asignado en el modelo actual'],['Oferta','Relaciona una solicitud con un técnico','Pareja única; plazo y estado propios'],['Evento','0..N eventos por solicitud','Actualmente JSON dentro de requests'],['Calificación','0..1 puntuación por solicitud finalizada','Actualmente atributo de requests, no tabla aparte']]),sec('Conceptual frente a físico','El modelo conceptual explica el negocio. El físico observado usa users, api_tokens, technicians, requests y offers. Especialidades, zonas y eventos usan JSON. Normalizarlos en tablas auxiliares sería una evolución, no un hecho de esta versión.'),sec('Fuente de instalación','Usar migraciones de backend/api/database/migrations. database/init.sql es esquema de referencia: no ejecutarlo y después volver a crear las mismas tablas con migraciones sobre la misma base.')),
page('Diccionario resumido y reglas',table('Datos principales',['Tabla','Campos relevantes','Control'],[['users','id, name, email, password, role','Correo único; contraseña hash; rol permitido'],['api_tokens','user_id, token_hash, expires_at','Token hash único, vencimiento y revocación'],['technicians','user_id, zone, zones, specialties, fee, rating, reviews, years','Usuario único; verificado y disponible'],['requests','client_id, specialty, zone, address, description, status, technician_id','Propiedad, transiciones y asignación'],['requests','created_ms, pending_until, completed_at, rating_until, rating, events','Plazos y nota única'],['offers','request_id, technician_id, status, sent_at, expires_at, score','Unicidad request_id + technician_id']]),sec('Ranking','Filtrar verificados, disponibles, especialidad y cobertura. Cercanía: 1 en zona principal, 0,5 en adicional; tarifa inversa normalizada entre elegibles; calificación / 5; experiencia limitada a 10 años / 10. Pesos 0,35/0,20/0,30/0,15. Redondeo documentado a seis decimales; desempate por calificación y luego identificador.'),sec('Reglas temporales','No aceptar oferta vencida; no volver a notificar al mismo técnico para esa solicitud; reservar al aceptar y liberar al cancelar antes de ejecución o finalizar; rechazar calificación tardía y duplicada. Fuente común: domain/rules.json y servicios del backend.')),
page('Integridad y evolución',sec('Pruebas de base de datos','Verificar claves y referencias, unicidad de correo y oferta, rechazo de datos inválidos en API, persistencia de estados, atomicidad y concurrencia real. Probar migración en base vacía y sobre copia de la versión anterior, comparando conteos, relaciones y datos significativos.'),sec('Seguridad y privacidad','El cliente accede a sus solicitudes; el técnico a ofertas y atenciones autorizadas; administración supervisa según permisos. Evitar direcciones ajenas, contraseñas, tokens y datos reales en logs o capturas. Retención y eliminación requieren política aprobada, no se presume plazo legal.'),sec('Respaldo y recuperación','Antes de un cambio de esquema: identificar build, crear respaldo controlado y comprobar restauración en entorno aislado. Registrar RPO y RTO objetivo antes del ensayo. No ejecutar migraciones destructivas o rollback sobre datos reales como experimento.'),sec('Cambios propuestos','Evaluar índices según consultas y carga; separar eventos y especialidades cuando exista necesidad justificada; definir auditoría persistente de acciones administrativas. Cada cambio requiere decisión arquitectónica, migración versionada, caso de integridad y actualización del diccionario.'),sec('Fuentes',refs+' Esquema inspeccionado: database/init.sql.'))])

doc('06-Arquitectura-y-diseno-tecnico.pdf','Arquitectura y diseño técnico',[
page('Componentes y responsabilidades',table('Monorepo',['Módulo','Responsabilidad','No le corresponde'],[['frontend/web','React y Vite; presentación, formularios, sesión y navegación','Autorizar operaciones o ser fuente de verdad'],['backend/api','Laravel; autenticación, reglas, transacciones y persistencia','Delegar permisos al navegador'],['python/api','FastAPI; ranking de candidatos por HTTP','Gestionar sesiones o almacenar solicitudes'],['PostgreSQL','Persistencia de cuentas, solicitudes, ofertas y estados','Sustituir validaciones y permisos de API']]),sec('Flujo de colaboración','React llama /api; Laravel valida token y actor, aplica acción y persiste. Para matching consulta Python con timeout de dos segundos; si falla o devuelve resultado inválido usa PHP. JS mantiene lógica de demo, separada de cuentas reales. El fallback debe conservar el mismo contrato de ranking.'),sec('Dependencias y decisiones','Mantener manifiesto, Dockerfile y .env.example por módulo. Compartir reglas mediante scripts/sync-rules.py, no editar copias manualmente. Documentar versión de regla, cambio, motivo, alternativas y consecuencias. No publicar secretos en archivos de ejemplo.')),
page('Contratos e interacciones',table('Rutas observadas',['Ruta','Acceso','Uso'],[['GET /api/health','Público','Estado del servicio Laravel'],['POST /api/register','Público limitado','Alta cliente o técnico; nunca administrador'],['POST /api/login','Público limitado','Validar credenciales y emitir sesión'],['POST /api/logout','Token','Revocar sesión'],['GET /api/state','Token','Estado filtrado por actor'],['POST /api/actions/{action}','Token y autorización','Crear, aceptar, confirmar, iniciar, finalizar y otras acciones'],['POST /match y GET /health','Microservicio interno','Ranking y salud FastAPI']]),sec('Contrato de solicitud','create recibe specialty, zone, address y description. El servidor valida y atribuye propiedad al actor autenticado. No confiar en un clientId arbitrario del navegador. Para cada acción registrar esquema, campos obligatorios, errores y estados admisibles.'),sec('Seguridad y errores','Las rutas de acceso tienen límite 10 por minuto; rutas autenticadas 120 por minuto según routes/api.php. El frontend envía Bearer token desde sessionStorage y timeout de 12 s. Deben evaluarse XSS, expiración y tratamiento de 401. 403 indica prohibición, 409 conflicto de estado y 422 validación según los casos del backend.')),
page('Decisiones y verificación',sec('ADR 01 Arquitectura políglota','Se conserva React/Laravel/FastAPI por contexto académico y separación del ranking. Ventaja: módulos independientes; costo: contratos y reglas duplicadas que requieren fixture común, integración y sincronización.'),sec('ADR 02 Persistencia','PostgreSQL es la fuente de verdad conectada. SQLite en memoria acelera pruebas locales pero no valida bloqueos PostgreSQL. Decisión: mantener ambos niveles y no intercambiar sus conclusiones.'),sec('ADR 03 Disponibilidad del matching','PHP permite continuar ante caída de Python. Deben probarse timeout, respuesta inválida, divergencia de regla y recuperación. Registrar fallo técnico sin filtrar información sensible al usuario.'),sec('Diagramas necesarios','El presente documento describe componentes y secuencias en texto. Para próximas revisiones, añadir diagramas de componentes, secuencia de aceptación concurrente y despliegue, conservando fuente editable y vinculación al contrato real. No atribuir al código colas, WebSockets o servicios externos no implementados.'),sec('Fuentes',refs+' Contratos: backend/api/routes/api.php, frontend/web/src/marketplace-api.js y python/api/app.py.'))])

doc('07-Experiencia-y-accesibilidad.pdf','Experiencia de usuario y accesibilidad',[
page('Recorridos y diseño',sec('Principio de experiencia','El usuario debe comprender qué servicio solicita, quién lo atenderá, cuánto representa la tarifa de visita y qué paso sigue. Mantener la paleta petróleo, crema y dorado, sin depender del color o las animaciones para comunicar estados.'),table('Recorridos',['Rol','Tarea principal','Señal de éxito'],[['Cliente','Acceder, solicitar, revisar, confirmar y calificar','Estado claro y solicitud propia persistida'],['Técnico','Completar perfil, quedar habilitado y responder','Oferta aceptada antes de vencer y atención trazable'],['Administrador','Verificar perfil y supervisar cobertura','Acción autorizada y resultado verificable']]),sec('Landing y cuenta','La landing presenta especialidades y proceso. El panel de operaciones se abre en la vista de cuenta; iniciar sesión y registro comparten una tarjeta con transición. Evitar mostrar datos operativos de demo como si fueran servicios reales. Las animaciones se desactivan con movimiento reducido.'),sec('Contenido de interfaz','Etiquetas visibles, mensajes específicos y lenguaje claro. Indicar tarifa de visita y que otros costos se acuerdan. El plazo de 10 minutos es para responder, no una promesa de llegada. Mostrar pendientes, carga, vacío, error, éxito y sesión vencida.')),
page('Accesibilidad y evaluación',sec('Objetivo WCAG','Se propone WCAG 2.2 nivel AA como objetivo, pendiente de auditoría completa. Verificar teclado, orden de foco, foco visible, nombres accesibles, errores asociados a campos, contraste, zoom y reflujo. Fuente: https://www.w3.org/TR/WCAG22/ . Una herramienta automática solo detecta parte de los problemas.'),sec('Movimiento y video','No hacer obligatoria la introducción animada para acceder. Pausar contenido fuera de pantalla o con preferencia de movimiento reducido. Comprobar que el formulario no pierda foco al alternar acceso/registro y que la escena de scroll no impida alcanzar contenido con teclado.'),sec('Prueba de usabilidad propuesta','Convocar usuarios representativos de hogares, MYPES y técnicos. Tareas: crear cuenta, registrar falla, comprender tarifa, confirmar técnico y consultar estado. Medir éxito, tiempo, pasos, errores y ayuda. Aplicar SUS sin inventar respuestas. La muestra y consentimiento se acuerdan antes del estudio.'),sec('Criterios y evidencias','Conservar SUS de 70 y solicitud en hasta cinco pasos o tres minutos de la fuente; aclarar la condición alternativa antes de evaluar. Guardar resultados anonimizados, navegador, resolución, build y hallazgos. Repetir las tareas fallidas tras corregir.'),sec('Mejoras propuestas','Priorizar preservación de campos ante error, mensajes de red y sesión vencida, retorno al punto previo y comprensión de disponibilidad. No incorporar chat, recordatorios o notificaciones externas sin requisitos y casos nuevos.'),sec('Fuentes',refs))])

artpages=[page('Investigación y método de comparación',sec('Propósito','Relacionar antecedentes académicos con decisiones de matching, reputación, experiencia e infraestructura. Se conserva el trabajo de investigación entregado; esta síntesis usa las relaciones del documento de ejemplos y no presenta una búsqueda bibliográfica nueva.'),sec('Método','Por antecedente registrar referencia original, problema, método, aporte, limitación, relación con RF/RNF y decisión local. Verificar DOI, año y publicación en la bibliografía original antes de reutilizar citas. No inferir que el algoritmo del artículo ya está implementado.'),sec('Estado del arte e infraestructura','Los estudios orientan patrones de asignación y servicio. La selección de servidor exige además presupuesto, carga medida, disponibilidad, ubicación, respaldo y capacidad operativa. No elegir proveedor solo porque aparece en un artículo o porque se usó en un prototipo.'),sec('Fuentes','Investigación completa: fuentes/estado-del-arte-original.pdf. Matriz derivada: trazabilidad/estado-del-arte.csv. Comparación tecnológica del sistema actual: PDF 06. Decisiones de infraestructura: PDF 09.'))]
for k in range(1,len(art),4):artpages.append(page('Antecedentes y aplicación',table('Relación conservada del ejemplo',art[0][:3],[r[:3] for r in art[k:k+4]]),sec('Límite de interpretación','Los aportes son orientaciones de diseño y prueba. La validez bibliográfica y la aplicabilidad al contexto local deben revisarse con el artículo original. No se han medido sus resultados en TécnicoYa.')))
doc('08-Estado-del-arte-y-tecnologia.pdf','Estado del arte y justificación tecnológica',artpages)

doc('09-Infraestructura-y-servidor.pdf','Infraestructura y operación del servidor',[
page('Criterios y alternativas',sec('Propósito','Definir un entorno reproducible de QA y una futura operación productiva. El laboratorio académico mantiene su propia convención de módulos. No se ha seleccionado ni contratado un proveedor mediante este documento.'),table('Alternativas a evaluar',['Alternativa','Ventaja','Costo o riesgo'],[['Servidor del laboratorio','Alineación con evaluación y pipeline institucional','Disponibilidad y permisos sujetos al laboratorio'],['VPS con contenedores','Control de red y configuración','Equipo mantiene parches, backups y monitoreo'],['Servicios administrados','Menor carga de operación de datos y plataforma','Costo recurrente y dependencia de proveedor']]),sec('Dimensionamiento','No fijar CPU o RAM como capacidad garantizada sin ensayo. Estimar candidatos por solicitud, usuarios concurrentes, tamaño de datos, tráfico del video y frecuencia de consultas. Probar la meta de 200 usuarios con mezcla realista y medir latencia, errores, CPU, memoria y conexiones de base de datos.'),sec('Relación con el estado del arte','El PDF 08 ayuda a justificar patrones y riesgos. El PDF 01 define pruebas; los resultados deciden capacidad. Registrar alternativas, fecha, costo cotizado y límites de cada servicio antes de aprobar. No se incluyen precios inventados.')),
page('Ambientes y operación',table('Separación',['Ambiente','Datos','Propósito'],[['Desarrollo','Sintéticos','Trabajo local y pruebas rápidas'],['QA','Sintéticos representativos y reiniciables','Integración, carga, seguridad y aceptación'],['Producción','Datos autorizados','Servicios reales; acceso controlado']]),sec('Red y secretos','Exponer solo la entrada web necesaria con HTTPS. PostgreSQL y matching deben quedar internos. Variables, APP_KEY y contraseñas fuera del repositorio y evidencias. Mantener privilegio mínimo, actualización de dependencias y acceso administrativo identificable.'),sec('Observabilidad','Registrar request ID, endpoint, estado HTTP, latencia, error y servicio. Evitar direcciones, contraseñas y tokens. Vigilar salud de API/matching/base, fallos de autenticación, vencimientos y fallback. Definir retención y responsable de alertas antes de producción.'),sec('Respaldo','Proponer respaldo automatizado y ensayo de restauración; acordar RPO, RTO, frecuencia y retención antes de cerrar operación. Verificar integridad en base aislada y registrar duración real. Tener archivo de backup sin restaurarlo no valida recuperación.'),sec('Configuración existente','infrastructure/docker-compose.yml define PostgreSQL 16, matching, API y web. .gitlab-ci.yml incluye pipeline del laboratorio. Debe verificarse el pipeline remoto y ejecución; su archivo local no demuestra despliegue ni health.')),
page('Ensayos y aceptación del entorno',sec('Prueba de carga','Acordar rampa, duración y porcentaje de solicitudes, consultas de estado y acceso. No ejecutar carga contra usuarios reales. Reportar percentiles, tasa de errores, recursos y dataset. Si no cumple, identificar cuello de botella antes de aumentar recursos.'),sec('Prueba de fallos','Interrumpir matching en QA y comprobar fallback coherente; ensayar reinicio de API y recuperación de base; comprobar procesador de plazos. Identificar qué operaciones admiten reintento y cómo se evita duplicar solicitudes.'),sec('Criterio de aceptación','Servicios y red verificados, secretos protegidos, migraciones y smoke aprobados, carga según meta acordada, restauración demostrada y responsable operativo asignado. La disponibilidad mensual del 99% requiere observación mensual; un smoke no la demuestra.'),sec('Registro de servidor','Proveedor o laboratorio, región, recursos, sistema, imágenes y versiones, costo, fecha, DNS/TLS, puertos públicos, ubicación de secretos, backup, alertas, métricas y resultado. Campos no conocidos quedan pendientes.'),sec('Fuentes',refs+' Referencia técnica: infrastructure/docker-compose.yml.'))])

backlog=[('S01','Acceso y perfiles',['HU-07','HU-04','HU-06'],'OBJ-05'),('S02','Solicitud y matching',['HU-01','HU-02'],'OBJ-01/02'),('S03','Ofertas y ejecución',['HU-03','HU-02'],'OBJ-03/04'),('S04','Calificación y entrega',['HU-05','HU-06','HU-08'],'OBJ-04/06/07')]
doc('10-Backlog-y-planificacion-Scrum.pdf','Backlog y planificación Scrum',[
page('Organización del trabajo',sec('Propuesta Scrum','Sprints de una semana sujetos al calendario académico. Definir Product Owner, Scrum Master y Developers; no asignar nombres sin acuerdo. El objetivo es entregar una porción funcional integrada en cada sprint, con datos, API, UI y pruebas, no separar un sprint completo solo para frontend y otro para backend.'),table('Plan de iteraciones',['Sprint','Objetivo','Historias','Entrega prevista'],[[n,g,', '.join(h),o+'; incremento QA'] for n,g,h,o in backlog]),sec('Refinamiento','Seleccionar RF y criterios del PDF 03; aclarar decisiones; dividir historias grandes; estimar con el equipo; priorizar riesgo y valor. Las fechas, puntos y capacidad no se inventan. El código previo puede reducir tareas, pero no acredita que esos sprints hayan sucedido.'),sec('Preparado para desarrollar','Historia comprensible, criterio observable, datos y permisos definidos, contrato acordado y dependencias identificadas. Si una decisión bloquea un caso, registrar DP y trabajar otra historia lista.')),
page('Desglose para desarrolladores junior',table('Ejemplo HU-01',['Tarea','Pasos concretos','Comprobación'],[['FE-01 Formulario','Leer contrato; crear etiquetas; validar; conservar datos; mostrar carga y error.','Datos inválidos no envían; red fallida no borra campos.'],['BE-01 Crear solicitud','Validar token y rol; validar payload; generar ID; persistir en transacción.','Cliente no crea solicitud a nombre ajeno.'],['DB-01 Datos','Revisar migración; relaciones e índices; preparar semillas sintéticas.','Persistencia y relaciones comprobadas en QA.'],['PY-01 Ranking','Validar entrada; filtrar candidatos; ordenar con reglas compartidas.','Fixture y desempate idénticos a PHP.'],['QA-01 Pruebas','Escribir caso positivo, negativo y límite; ejecutar y adjuntar log.','Esperado y observado por build.'],['DOC-01 Evidencia','Actualizar historia, contrato, caso y registro de despliegue.','Trazabilidad completa y sin secretos.']]),sec('Cómo tomar una tarea','Leer objetivo y criterio; reproducir entorno; escribir o revisar prueba; cambiar una responsabilidad; ejecutar pruebas relevantes; revisar diff; pedir revisión; adjuntar evidencia. No copiar rutas o campos de ejemplo sin verificar el contrato actual.')),
page('Seguimiento y cierre',sec('Tablero','Propuesto, listo, en desarrollo, revisión, pruebas, bloqueado y terminado. Registrar bloqueos concretos; no marcar terminado porque la interfaz se vea bien. Al cambiar alcance, actualizar objetivo e impacto en pruebas.'),sec('Eventos','Planning: objetivo y selección. Daily: avance hacia objetivo e impedimentos. Review: incremento y feedback. Retrospectiva: mejora con responsable y fecha. Las fichas S01-S04 son plantillas planificadas; no contienen reuniones ficticias.'),sec('Dependencias','S02 requiere acceso y perfiles; S03 requiere solicitud/matching; S04 requiere ejecución y estados. Accesibilidad, seguridad y documentación atraviesan todos los sprints. QA debe prepararse desde S01, no solo al final.'),sec('Definition of Done','Criterios cumplidos, código revisado, tests y regresión relevantes, datos coherentes, documentación actualizada, defectos críticos resueltos y evidencia de incremento. El despliegue QA se registra por separado con éxito o bloqueo. Producción requiere liberación del PDF 12.'),sec('Fuente Scrum','https://scrumguides.org/scrum-guide.html. Se adopta Scrum como marco propuesto; la entrega utilizable no implica que una liberación deba esperar a la Review.'),sec('Fuentes',refs))])

doc('11-Desarrollo-y-estrategia-TDD.pdf','Guía de desarrollo y estrategia TDD',[
page('Preparación y ciclo',sec('Entorno','Abrir TecnicoYa.code-workspace. Instalar dependencias de cada módulo según manifiestos y documentación técnica; copiar .env.example a configuración local y nunca versionar secretos. Verificar que las reglas coincidan mediante scripts/sync-rules.py --check.'),sec('Rojo','Partir de una historia y criterio. Escribir una prueba pequeña con entrada, acción y esperado. Ejecutarla y comprobar que falla por la conducta faltante, no por importación rota o entorno incorrecto. Guardar la identificación del caso.'),sec('Verde','Implementar el mínimo que cumple el criterio y ejecutar de nuevo. No endurecer datos solo para satisfacer el test ni cambiar el esperado para ocultar un defecto. Mantener permisos en el servidor.'),sec('Refactorizar','Mejorar nombres, duplicación y responsabilidades sin cambiar conducta. Repetir tests. Revisar contratos, migraciones y reglas compartidas. Un refactor no agrega alcance sin historia.'),sec('Límite histórico','Las pruebas existentes son base de regresión. No se afirma que todo el código anterior fue creado con TDD. Para nuevas tareas conservar evidencia del ciclo y revisión.')),
page('Ejemplos de TDD del dominio',table('Criterios y pruebas',['Historia','Prueba inicial','Implementación esperada'],[['Respuesta de oferta','A los 10 min exactos aceptar devuelve conflicto y no asigna.','Comparar tiempo servidor con expires_at antes de transacción final.'],['Matching','Dos candidatos con score igual se ordenan por mejor rating.','Orden secundario determinista; fixture común.'],['Privacidad','Cliente B cancela ID de A y obtiene prohibición.','Autorizar propiedad antes de modificar estado.'],['Calificación','Segunda nota no cambia promedio ni reviews.','Rechazar duplicado de forma atómica.'],['Frontend','Error HTTP conserva dirección y descripción.','Estado de campos separado del estado de envío.']]),sec('Niveles de dobles','Mock de red sirve para error de interfaz; fake HTTP valida fallback de Laravel; no demuestra conexión Python real. Usar integración aparte con PostgreSQL y FastAPI. Controlar reloj para límites; no esperar 24 horas reales en pruebas unitarias.'),sec('Casos concurrentes','Crear test de dos aceptaciones sobre una solicitud en PostgreSQL aislado. Esperado: una propuesta ganadora y ninguna reserva duplicada. Verificar resultado persistido, no solo código HTTP.')),
page('Comandos y revisión',table('Ejecución desde cada módulo',['Carpeta','Comando','Resultado a guardar'],[['frontend/web','npm test','Suite y casos'],['frontend/web','npm run build','Build o error'],['backend/api','php artisan test','Casos y entorno de base'],['python/api','python -m pytest -q','Casos de ranking y validación'],['Raíz','python scripts/sync-rules.py --check','Consistencia de reglas']]),sec('Revisión de código','Verificar alcance, legibilidad, autorización, datos, errores, pruebas significativas y ausencia de secretos. Revisar que los tests fallarían ante un defecto real. Evitar pruebas que solo repiten la implementación sin evaluar comportamiento.'),sec('Evidencia','Guardar comando, fecha, build/commit, entorno y salida íntegra. Vincular CT o CNF; registrar defectos y retest por separado. No afirmar cobertura de líneas o ramas sin reporte de herramienta y denominador definido.'),sec('Fuentes',refs+' Guía técnica del repositorio: docs/TECNICOYA.md.'))])

doc('12-Despliegue-y-aceptacion.pdf','Despliegue y aceptación de versiones',[
page('Preparación de una entrega',sec('Propósito','Instalar un incremento reproducible y comprobarlo antes de declararlo disponible. QA y producción tienen decisiones separadas. Este procedimiento no es evidencia de que el despliegue ya ocurrió.'),sec('Entradas','Build/commit identificado; pruebas aprobadas; imágenes y dependencias registradas; variables preparadas en almacén seguro; migraciones revisadas; backup y recuperación ensayados; responsable y ventana acordados.'),sec('Pipeline','La configuración .gitlab-ci.yml incluye root/laboratorio-devops y gitlab/student-pipeline.yml. Verificar acceso, jobs, reportes y políticas en GitLab. No afirmar Quality Gate o despliegue exitoso sin URL e ID de pipeline. Preservar logs como evidencia.'),sec('Checklist previo','Confirmar destino QA; comprobar variables obligatorias; revisar puertos y TLS; preparar dataset sintético; comprobar que el cambio no exige una migración incompatible. No usar credenciales predeterminadas para administrador.'),sec('Control de versiones','Asignar versión del producto y relacionar versión de reglas y esquema. Registrar artefactos exactos para rollback; no usar solo etiquetas mutables sin digest o referencia estable.')),
page('Procedimiento QA',table('Secuencia',['Paso','Acción','Evidencia'],[['1','Validar configuración Compose y variables sin publicar secretos.','Resultado de validación y entorno'],['2','Construir imágenes desde build identificado.','Logs y referencias de imágenes'],['3','Levantar PostgreSQL y servicios internos.','Estado de contenedores y health'],['4','Aplicar migraciones una sola vez sobre la base prevista.','Migraciones y comprobación de integridad'],['5','Crear cuentas sintéticas autorizadas y verificar técnico.','IDs de prueba sin contraseñas'],['6','Ejecutar solicitud, oferta, confirmación, ejecución y nota.','API, UI y persistencia del flujo'],['7','Comprobar scheduler de plazos, logs y fallos.','Resultados de vencimiento y fallback'],['8','Registrar URL, versión, fecha y decisión.','Informe de despliegue y riesgos']]),sec('Comandos orientativos','Desde infrastructure, revisar docker compose config y realizar build/up según el entorno aprobado. Las migraciones se ejecutan dentro del servicio API con php artisan migrate, usando la configuración correcta. Verificar cómo se inicia el scheduler; no asumir que existe por levantar la API. Adaptar comandos a la infraestructura institucional.'),sec('Smoke','Health de API y matching; autenticación válida e inválida; vista por rol; solicitud persistida; recursos web; conexión PostgreSQL. Smoke aprobado habilita pruebas amplias, no aceptación definitiva.')),
page('Rollback y aceptación',sec('Rollback','Detener entrega si hay exposición de datos, corrupción, error de migración o fallo crítico. Conservar logs. Volver a artefacto compatible; restaurar base solo con procedimiento autorizado y considerando pérdida de datos. Registrar el resultado y repetir smoke.'),sec('Aceptación','Confirmar alcance entregado, casos críticos aprobados, defectos abiertos y riesgos aceptados, accesibilidad y seguridad evaluadas, documentación y operación listas. El docente o responsable formal registra su decisión y fecha; no rellenar firmas automáticamente.'),sec('Formato de liberación','Versión; commit; pipeline; entorno; URL; imágenes; esquema; reglas; casos; fallos; riesgos; backup; rollback; resultado; responsable; aceptación. Campos sin evidencia permanecen pendientes.'),sec('Después de entregar','Vigilar errores, latencia y disponibilidad; revisar incidentes; actualizar backlog. El informe del Sprint referencia el despliegue y sus límites. No confundir un localhost funcional con operación pública.'),sec('Fuentes',refs+' Configuración inspeccionada: infrastructure/docker-compose.yml y .gitlab-ci.yml.'))])

for n,goal,h,objective in backlog:
    doc(f'{n}-Informe-de-sprint.pdf',f'Informe de sprint {n}',[
    page('Plan de la iteración',sec('Estado','Plantilla planificada, no acta de un Sprint ejecutado. Fechas, responsables, estimación, commit y despliegue pendientes de registro. La existencia de código no acredita ejecución del Sprint.'),sec('Objetivo',goal+'. Trazabilidad: '+objective+'. Historias: '+', '.join(h)+'. Seleccionar los RF y criterios concretos del PDF 03 antes del Planning.'),table('Trabajo previsto',['Área','Tarea','Salida'],[['Diseño','Revisar flujo, contrato y permisos de historias','Decisiones y criterios listos'],['Datos','Revisar migración y dataset sintético','Datos de prueba e integridad'],['Backend y Python','Implementar acciones y ranking que correspondan','Contrato y pruebas de dominio'],['Frontend','Integrar recorrido, validación y estados','UI accesible y errores claros'],['QA','Casos positivos, negativos y límites','Logs por build y defectos'],['Operación','Preparar y verificar entrega QA','Despliegue o bloqueo documentado']]),sec('Dependencias','Consultar el orden del PDF 10. No asumir que todas las tareas aplican por igual; el equipo concreta el alcance y capacidad. Las funciones diferidas permanecen en el backlog.')),
    page('Evidencias y cierre',table('Registro a completar',['Campo','Estado actual'],[['Periodo y participantes','Pendientes de formalización'],['Historias terminadas y diferidas','Sin ejecución atribuida a este Sprint'],['Build, commit y pipeline','No registrados'],['Casos y resultados','Pendientes; no trasladar tests históricos sin contexto'],['Defectos y retest','Pendientes de ejecución'],['Despliegue QA y URL','Pendiente'],['Review y aceptación','No realizadas/documentadas'],['Retrospectiva y acción de mejora','Pendientes']]),sec('Procedimiento de cierre','Adjuntar evidencias reales bajo sprints/'+n+'/evidencias; indicar qué criterio cubre cada archivo. Registrar comandos, entorno, resultado y limitaciones. Conservar fallo y retest. Actualizar Plan de Pruebas, matriz y backlog. Completar review y retrospectiva con participantes reales.'),sec('Definition of Done','Criterios verificados, revisión y regresión aprobadas, datos íntegros, documentación actualizada, defectos críticos resueltos y entrega identificable. Si el despliegue falla, registrar bloqueado aunque parte del código esté terminada.'),sec('Relación con revisión existente','evidencias/revision-2026-09-22 corresponde a una revisión local; no demuestra por sí misma la ejecución de '+n+'.'))])

pdfmetrics.registerFont(TTFont('Arial','C:/Windows/Fonts/arial.ttf'))
pdfmetrics.registerFont(TTFont('Arial-Bold','C:/Windows/Fonts/arialbd.ttf'))
styles=getSampleStyleSheet()
styles.add(ParagraphStyle(name='DocTitle',fontName='Helvetica-Bold',fontSize=22,leading=27,textColor=colors.HexColor('#162e31'),spaceAfter=12))
styles.add(ParagraphStyle(name='PageTitle',fontName='Helvetica-Bold',fontSize=15,leading=19,spaceAfter=12,textColor=colors.HexColor('#162e31')))
styles['Heading2'].fontSize=11.5;styles['Heading2'].leading=15;styles['Heading2'].spaceBefore=11;styles['Heading2'].spaceAfter=5
styles['BodyText'].fontSize=10;styles['BodyText'].leading=14;styles['BodyText'].spaceAfter=8
styles.add(ParagraphStyle(name='Cell',fontName='Helvetica',fontSize=8.6,leading=11.7,spaceAfter=0))
styles.add(ParagraphStyle(name='CellHead',parent=styles['Cell'],fontName='Helvetica-Bold',textColor=colors.white))
styles.add(ParagraphStyle(name='Meta',fontSize=8.5,leading=12,textColor=colors.HexColor('#536466'),spaceAfter=14))
for style in styles.byName.values():
    if hasattr(style,'fontName'):
        style.fontName='Arial-Bold' if 'Bold' in style.fontName else 'Arial'
def para(t,style='BodyText'):return Paragraph(escape(t).replace('\n','<br/>'),styles[style])
def flow():
    d=Drawing(490,150)
    labels=['Solicitud','Matching','Oferta','Confirmar','Ejecutar','Calificar']
    for i,label in enumerate(labels):
        x=(i%3)*165;y=100-(i//3)*75
        d.add(Rect(x,y,145,40,rx=8,ry=8,fillColor=colors.HexColor('#e8efed'),strokeColor=colors.HexColor('#365e5c')))
        d.add(String(x+72,y+15,label,textAnchor='middle',fontName='Helvetica',fontSize=10))
        if i%3<2:d.add(Line(x+145,y+20,x+164,y+20,strokeColor=colors.HexColor('#365e5c')))
    return d
def footer(c,d):
    c.setFillColor(colors.HexColor('#536466'));c.setFont('Helvetica',8)
    c.drawString(44,27,'TécnicoYa Huancayo | '+DATE+' | Propuesta académica')
    c.drawRightString(551,27,str(d.page))
manifest=[]
for item in docs:
    story=[]
    for i,p in enumerate(item['pages']):
        if i:story.append(PageBreak())
        else:
            story+=[para(item['title'],'DocTitle'),para('Ingeniería de Sistemas e Informática · Universidad Continental\nExpediente organizado v1.0 | '+DATE,'Meta')]
        story.append(para(p['title'],'PageTitle'))
        for s in p['sections']:
            story.append(para(s['title'],'Heading2'))
            if 'text' in s:story.append(para(s['text']))
            elif 'flow' in s:story.append(flow())
            else:
                data=[[para(x,'CellHead') for x in s['heads']]]+[[para(str(x),'Cell') for x in r] for r in s['rows']]
                count=len(s['heads']);widths={2:[145,362],3:[115,196,196],4:[73,123,213,98]}[count]
                t=Table(data,colWidths=widths,repeatRows=1,hAlign='LEFT')
                t.setStyle(TableStyle([('BACKGROUND',(0,0),(-1,0),colors.HexColor('#244448')),('ROWBACKGROUNDS',(0,1),(-1,-1),[colors.HexColor('#f0f4f3'),colors.white]),('VALIGN',(0,0),(-1,-1),'TOP'),('LEFTPADDING',(0,0),(-1,-1),7),('RIGHTPADDING',(0,0),(-1,-1),7),('TOPPADDING',(0,0),(-1,-1),7),('BOTTOMPADDING',(0,0),(-1,-1),7),('LINEBELOW',(0,0),(-1,0),.5,colors.HexColor('#244448'))]))
                story.extend([t,Spacer(1,9)])
    target=OUT/item['name']
    SimpleDocTemplate(str(target),pagesize=(595,842),leftMargin=44,rightMargin=44,topMargin=40,bottomMargin=48,title=item['title'],author='Equipo TécnicoYa Huancayo').build(story,onFirstPage=footer,onLaterPages=footer)
    count=len(PdfReader(target).pages)
    manifest.append({'archivo':item['name'],'titulo':item['title'],'paginas':count,'sha256':hashlib.sha256(target.read_bytes()).hexdigest()})
    print(item['name'],count)
(EDIT/'contenido-expediente.json').write_text(json.dumps(docs,ensure_ascii=False,indent=2),encoding='utf-8')
(OUT/'catalogo-pdfs.json').write_text(json.dumps(manifest,ensure_ascii=False,indent=2),encoding='utf-8')
index='# Expediente de TécnicoYa Huancayo\n\nLos PDF numerados se encuentran en esta misma carpeta. Estado: propuesta académica, con implementación y evidencias diferenciadas.\n\n'
for m in manifest:index+=f"- [{m['archivo']}]({m['archivo']}) — {m['titulo']} ({m['paginas']} páginas).\n"
index+='\n## Fuentes y mantenimiento\n\nLos cuatro originales permanecen en `fuentes/`; las matrices en `trazabilidad/`; los logs en `evidencias/`. Los informes S01-S04 son plantillas planificadas, no actas ejecutadas. El plan consolidado previo sigue en `plan-de-pruebas/`.\n\nFuente editable de los nuevos PDF: `editables/contenido-expediente.json`. Generador: `scripts/generar-expediente-pdfs.py` desde la raíz. Procedimiento BPMN del camino principal: `editables/proceso-principal.bpmn`; requiere validación en Bizagi antes de aprobación.\n'
(OUT/'README.md').write_text(index,encoding='utf-8')

# Modelo BPMN de camino principal, con DI para importación en modeladores.
import xml.etree.ElementTree as ET
NS={'bpmn':'http://www.omg.org/spec/BPMN/20100524/MODEL','bpmndi':'http://www.omg.org/spec/BPMN/20100524/DI','dc':'http://www.omg.org/spec/DD/20100524/DC','di':'http://www.omg.org/spec/DD/20100524/DI'}
for prefix,uri in NS.items():ET.register_namespace(prefix,uri)
def elem(prefix,name):return '{'+NS[prefix]+'}'+name
root=ET.Element(elem('bpmn','definitions'),{'id':'TecnicoYaDefinitions','targetNamespace':'https://tecnicoya.example/bpmn'})
process=ET.SubElement(root,elem('bpmn','process'),{'id':'ProcesoPrincipal','name':'TécnicoYa camino principal para revisión','isExecutable':'false'})
nodes=[('startEvent','inicio','Necesidad de servicio'),('task','solicitud','Cliente registra solicitud'),('task','ranking','Sistema ordena candidatos'),('task','oferta','Sistema genera ofertas'),('task','acepta','Técnico acepta'),('task','confirma','Cliente confirma'),('task','ejecuta','Técnico ejecuta y finaliza'),('task','nota','Cliente califica'),('endEvent','fin','Servicio evaluado')]
for typ,id,name in nodes:ET.SubElement(process,elem('bpmn',typ),{'id':id,'name':name})
for i in range(len(nodes)-1):ET.SubElement(process,elem('bpmn','sequenceFlow'),{'id':f'f{i}','sourceRef':nodes[i][1],'targetRef':nodes[i+1][1]})
diagram=ET.SubElement(root,elem('bpmndi','BPMNDiagram'),{'id':'diagrama'});plane=ET.SubElement(diagram,elem('bpmndi','BPMNPlane'),{'id':'plano','bpmnElement':'ProcesoPrincipal'})
for i,(typ,id,name) in enumerate(nodes):
    shape=ET.SubElement(plane,elem('bpmndi','BPMNShape'),{'id':id+'_di','bpmnElement':id});size=36 if 'Event' in typ else 120
    ET.SubElement(shape,elem('dc','Bounds'),{'x':str(30+i*155),'y':'80','width':str(size),'height':str(36 if 'Event' in typ else 70)})
for i in range(len(nodes)-1):
    edge=ET.SubElement(plane,elem('bpmndi','BPMNEdge'),{'id':f'f{i}_di','bpmnElement':f'f{i}'})
    ET.SubElement(edge,elem('di','waypoint'),{'x':str(30+i*155+(36 if i==0 else 120)),'y':'110'});ET.SubElement(edge,elem('di','waypoint'),{'x':str(30+(i+1)*155),'y':'110'})
ET.ElementTree(root).write(EDIT/'proceso-principal.bpmn',encoding='utf-8',xml_declaration=True)
